GRANT EXECUTE ON [ODS].[isp_RPT_CC_APPROVAL] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_CC_APPROVAL] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_CC_INPROGRESS] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_CC_INPROGRESS] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_GIN_SUMMARY] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_GIN_SUMMARY] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_INBOUND_RECEIVING] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_INBOUND_RECEIVING] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_INBOUND_SHORTAGE] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_INBOUND_SHORTAGE] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_INBOUND_SUMMARY] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_INBOUND_SUMMARY] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_OUTBOUND_BILLING] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_OUTBOUND_BILLING] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_OUTBOUND_ITEM_LEVEL_REPORT] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_OUTBOUND_ITEM_LEVEL_REPORT] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_OUTBOUND_ORDER_LEVEL_REPORT] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_OUTBOUND_ORDER_LEVEL_REPORT] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_RECEIPT_DETAILS] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_RECEIPT_DETAILS] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_SHIPPING] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_SHIPPING] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_SKU_SUMMARY] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_SKU_SUMMARY] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_STORAGE_BILLING] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_STORAGE_BILLING] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_VAS] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_VAS] TO LogiReportRoleWM
GO
GRANT EXECUTE ON [ODS].[isp_RPT_WAVE_ALLOCATION] TO [NSQL]
GO
GRANT EXECUTE ON [ODS].[isp_RPT_WAVE_ALLOCATION] TO LogiReportRoleWM
GO
