

--isp_PackConfirmALL
exec API.TouchPadDropMsg 1001401 , 1001450

execute API.TouchPadAddMsg 1001401, 10, 'Invalid SKU. Scanned SKU not found in SKU table. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001402, 10, 'Invalid SKU. Scanned SKU not found in SKU table. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001403, 10, 'Cannot select more than these items:  Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001404, 10, 'Pickslip No is already Closed/Packed. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001405, 10, 'Carton No is already Closed/Packed. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001406, 10, 'Incorrect dynamic E-Comm Carton Weight column setup. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001407, 10, 'Incorrect dynamic E-Comm Carton Weight column setup. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001408, 10, 'Fail to insert into PackHeader. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001409, 10, 'No SKU entered. Please enter or scan valid SKU. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001410, 10, 'No Quantity entered. Please enter valid Quantity. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001411, 10, 'Invalid Quantity entered. Please enter valid Quantity. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001412, 10, 'Closed Quantity > Pick Quantity. Please enter valid Quantity. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001413, 10, 'Fail to insert into PackDetail. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001414, 10, 'Fail to update into PackDetail. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001415, 10, 'Fail to insert into PackDetail. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001416, 10, 'Fail to update into PackDetail. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001417, 10, 'Fail to insert into PackDetail. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001418, 10, 'Fail to update into PackDetail. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001419, 10, 'Fail to update into SKU. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001420, 10, 'Fail to update into SKU. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001421, 10, 'Fail to insert into PackInfo. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001422, 10, 'Fail to update into PackInfo. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001423, 10, 'Fail to insert into PackInfo. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001424, 10, 'Fail to update into PackInfo. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001425, 10, 'Fail to update into PackHeader. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001426, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001427, 10, 'Paper Printer setup not done. Please setup the Label Printer. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001428, 10, 'INS QTask Fail. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001429, 10, 'UPD QTask Fail . Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001430, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001431, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001432, 10, 'No Session context found. Function : isp_PackConfirmALL',    'us_english'
execute API.TouchPadAddMsg 1001433, 10, 'Invalid Post Extended Update SP Name Function : isp_PackConfirmALL',    'us_english'