

--isp_PackConfirm
exec API.TouchPadDropMsg 1000000 , 1000050

execute API.TouchPadAddMsg 1000000, 10, 'Negative Quantity Detected Failed to Proceed PackConfirm. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000001, 10, 'Invalid SKU. Scanned SKU not found in SKU table. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000002, 10, 'Carton No in On-Hold Status. Unable to proceed to Closed Carton. Please Unhold this Carton. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000003, 10, 'Pickslip No is already Closed/Packed. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000004, 10, 'Carton No is already Closed/Packed. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000005, 10, 'Incorrect dynamic E-Comm Carton Weight column setup. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000006, 10, 'Incorrect dynamic E-Comm Carton Weight column setup. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000007, 10, 'Fail to insert into PackHeader. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000008, 10, 'Fail to insert into PackInfo. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000009, 10, 'Fail to update into PackInfo. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000010, 10, 'Fail to insert into PackInfo. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000011, 10, 'Fail to update into PackInfo. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000012, 10, 'No SKU entered. Please enter or scan valid SKU. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000013, 10, 'No Quantity entered. Please enter valid Quantity. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000014, 10, 'Invalid Quantity entered. Please enter valid Quantity. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000015, 10, 'Closed Quantity > Pick Quantity. Please enter valid Quantity. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000016, 10, 'Fail to insert into PackDetail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000017, 10, 'Fail to update into PackDetail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000018, 10, 'Fail to update into SKU. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000019, 10, 'Fail to update into SKU. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000020, 10, 'Fail to update into PackHeader. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000021, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000022, 10, 'Paper Printer setup not done. Please setup the Paper Printer. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000023, 10, 'TCPQueueTask Insert Fail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000024, 10, 'QTask Update PackHeader Fail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000025, 10, 'Cannot select more than these items:  Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000026, 10, 'Fail to insert into PackDetail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000027, 10, 'Fail to update into PackDetail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000028, 10, 'Fail to insert into PackDetail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000029, 10, 'Fail to update into PackDetail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000030, 10, 'Fail to update into PackDetail. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000031, 10, 'Paper Printer setup not done. Please setup the Paper Printer. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000032, 10, 'No records found in WMReport. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000033, 10, 'No value found in table(WMReport); column(keyFieldname1), this column cannot be empty or null. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000034, 10, 'No records found in WMReport. Function : isp_PackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000035, 10, 'No value found in table(WMReport); column(keyFieldname1), this column cannot be empty or null. Function : isp_PackConfirm',    'us_english'
