--isp_Print
exec API.TouchPadDropMsg 1002801 , 1002850

execute API.TouchPadAddMsg 1002801, 10, 'Fail Insert to Table RDT.RDTMOBREC. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002802, 10, 'Fail Update to Table RDT.RDTMOBREC. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002803, 10, 'ReportNotSetup. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002804, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002805, 10, 'Paper Printer setup not done. Please setup the Paper Printer. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002806, 10, 'No Default Printer Found. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002807, 10, 'PrinterNoSetup. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002808, 10, 'ParamNotMatch. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002809, 10, 'Bad ProcessSP. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002810, 10, 'SpoolNot Setup. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002811, 10, 'INS PrnJobFail. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002812, 10, 'INS QTaskFail. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002813, 10, 'UPD QTask Fail. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002814, 10, 'UPD PrnJobFail. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002815, 10, 'SpoolNot Setup. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002816, 10, 'Error Code : INS PrnJobFail. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002817, 10, 'UPD PrnJobFail. Please contact Touch Pack Super User. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002818, 10, 'INS PrnJobFail. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002819, 10, 'BarTender Fail. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002820, 10, 'DirectPrn Fail. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002821, 10, 'DW not setup. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002822, 10, 'INS PrnJobFail. Function : isp_Print',    'us_english'
execute API.TouchPadAddMsg 1002823, 10, 'INS PrnLogFail. Function : isp_Print',    'us_english'
