--isp_UCCPackConfirm
exec API.TouchPadDropMsg 1000051 , 1000100

execute API.TouchPadAddMsg 1000051, 10, 'Cannot select more than these items:  Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000052, 10, 'Carton No in On-Hold Status. Unable to proceed to Closed Carton. Please Unhold this Carton. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000053, 10, 'Pickslip No is already Closed/Packed. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000054, 10, 'Carton No is already Closed/Packed. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000055, 10, 'Incorrect dynamic E-Comm Carton Weight column setup. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000056, 10, 'Fail to insert into PackHeader. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000057, 10, 'No SKU entered. Please enter or scan valid SKU. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000058, 10, 'No Quantity entered. Please enter valid Quantity. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000059, 10, 'Invalid Quantity entered. Please enter valid Quantity. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000060, 10, 'Fail to insert into PackDetail. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000061, 10, 'Fail to update into PackDetail. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000062, 10, 'Fail to Insert into PackInfo. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000063, 10, 'Fail to UPDATE into PackInfo. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000064, 10, 'Fail to Insert into PackInfo. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000065, 10, 'Fail to update into PackInfo. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000066, 10, 'INS QTask Fail. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000067, 10, 'UPD QTask Fail. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000068, 10, 'Fail to update into PackHeader. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000069, 10, 'No records found in WMReport. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000070, 10, 'No value found in table(WMReport); column(keyFieldname1), this column cannot be empty or null. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000071, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000072, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000073, 10, 'Paper Printer setup not done. Please setup the Paper Printer. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000074, 10, 'No records found in WMReport. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000075, 10, 'No value found in table(WMReport); column(keyFieldname1), this column cannot be empty or null. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000076, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_UCCPackConfirm',    'us_english'
execute API.TouchPadAddMsg 1000077, 10, 'Fail to UPDATE into UCCNO Function : isp_UCCPackConfirm',    'us_english'