--isp_ResetCarton
exec API.TouchPadDropMsg 1000701 , 1000750

execute API.TouchPadAddMsg 1000701, 10, 'Unable to update PackInfo. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000702, 10, 'Unable to delete PackInfo. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000703, 10, 'Unable to update UCCNo. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000704, 10, 'Unable to delete PackDetail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000705, 10, 'Unable to delete PackSerialNo. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000706, 10, 'Update SerialNO Fail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000707, 10, 'Update packheader Fail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000708, 10, 'Unable to delete PackSerialNo. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000709, 10, 'Update SerialNo Fail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000710, 10, 'Update SerialNo Fail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000711, 10, 'Unable to delete PackDetail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000712, 10, 'Unable to delete PackInfo. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000713, 10, 'Unable to update UCC. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000714, 10, 'Packed Pickslip not able to reset. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000715, 10, 'Update SerialNO Fail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000716, 10, 'Unable to delete PackSerialNo. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000717, 10, 'Update SerialNo Fail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000718, 10, 'Unable to update UCC. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000719, 10, 'Unable to delete PackInfo. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000720, 10, 'Unable to delete PackDetail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000721, 10, 'Update packheader Fail. Function : isp_ResetCarton',    'us_english'
execute API.TouchPadAddMsg 1000722, 10, 'No Session context found. Function : isp_ResetCarton',    'us_english'