--isp_HoldCarton
exec API.TouchPadDropMsg 1001351 , 1001400

execute API.TouchPadAddMsg 1001351, 10, 'Invalid SKU. Scanned SKU not found in SKU table. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001352, 10, 'Carton No is already in On-Hold Status. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001353, 10, 'Carton No is already Closed/Packed. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001354, 10, 'Pickslip No is already Closed/Packed. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001355, 10, 'Fail to insert into PackHeader. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001356, 10, 'No SKU entered. Please enter or scan valid SKU. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001357, 10, 'No Quantity entered. Please enter valid Quantity. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001358, 10, 'Invalid Quantity entered. Please enter valid Quantity. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001359, 10, 'Closed Quantity > Pick Quantity. Please enter valid Quantity. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001360, 10, 'Fail to insert into PackDetail. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001361, 10, 'Fail to update into PackDetail. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001362, 10, 'Fail to insert into PackDetail. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001363, 10, 'Fail to update into PackDetail. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001364, 10, 'Fail to insert into PackDetail. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001365, 10, 'Fail to update into PackDetail. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001366, 10, 'Fail to update into SKU. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001367, 10, 'Fail to update into SKU. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001368, 10, 'Fail to insert into PackInfo. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001369, 10, 'Fail to update into PackInfo. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001370, 10, 'No records found in WMReport. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001371, 10, 'No value found in table(WMReport); column(keyFieldname1), this column cannot be empty or null. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001372, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001373, 10, 'Label Printer setup not done. Please setup the Label Printer. Function : isp_HoldCarton',    'us_english'
execute API.TouchPadAddMsg 1001374, 10, 'Paper Printer setup not done. Please setup the Paper Printer. Function : isp_HoldCarton',    'us_english'
