SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO


CREATE VIEW [dbo].[V_0000_GENERIC_PUR_DET_UNICODE]
AS 
SELECT *
FROM INDTSITF..V_0000_GENERIC_PUR_DET_UNICODE (NOLOCK) 

GO
GRANT DELETE ON  [dbo].[V_0000_GENERIC_PUR_DET_UNICODE] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_0000_GENERIC_PUR_DET_UNICODE] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_0000_GENERIC_PUR_DET_UNICODE] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_0000_GENERIC_PUR_DET_UNICODE] TO [NSQL]
GO
