SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO


 

CREATE View [dbo].[V_ABCANALYSIS]
as
SELECT * from ABCANALYSIS (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_ABCANALYSIS] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ABCANALYSIS] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ABCANALYSIS] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ABCANALYSIS] TO [NSQL]
GO
