SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

--storerconfig
--not needed
--AdjustmentDetail
CREATE OR ALTER VIEW [dbo].[V_ADJUSTMENTDETAIL] AS SELECT * FROM ADJUSTMENTDETAIL WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_ADJUSTMENTDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ADJUSTMENTDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ADJUSTMENTDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ADJUSTMENTDETAIL] TO [NSQL]
GO
