SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
--storerconfig
--not needed 

--AdjustmentDetail
CREATE VIEW [dbo].[V_ADJUSTMENTDETAIL] AS SELECT * FROM ADJUSTMENTDETAIL WITH (NOLOCK)  
GO
GRANT DELETE ON  [dbo].[V_ADJUSTMENTDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ADJUSTMENTDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ADJUSTMENTDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ADJUSTMENTDETAIL] TO [NSQL]
GO
