SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_BATCHPICK] 
AS 
SELECT [Loadkey]
, [QTYAllocated]
, [QtyScanned]
FROM [BATCHPICK] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_BATCHPICK] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_BATCHPICK] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_BATCHPICK] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_BATCHPICK] TO [NSQL]
GO
