SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_BILL_STOCKMOVEMENT]
AS
SELECT [StorerKey]
, [Sku]
, [Lot]
, [Qty]
, [EffectiveDate]
, [AddWho]
FROM [BILL_STOCKMOVEMENT] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_BILL_STOCKMOVEMENT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_BILL_STOCKMOVEMENT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_BILL_STOCKMOVEMENT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_BILL_STOCKMOVEMENT] TO [NSQL]
GO
