SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_BILL_STOCKMOVEMENT_DETAIL]
AS
SELECT [StorerKey]
, [Company]
, [Sku]
, [Descr]
, [Lot]
, [Qty]
, [EffectiveDate]
, [Flag]
, [TranType]
, [RunningTotal]
, [record_number]
FROM [BILL_STOCKMOVEMENT_DETAIL] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_BILL_STOCKMOVEMENT_DETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_BILL_STOCKMOVEMENT_DETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_BILL_STOCKMOVEMENT_DETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_BILL_STOCKMOVEMENT_DETAIL] TO [NSQL]
GO
