SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_BILLING_SUMMARY_CUT]
AS
SELECT [StorerKey]
, [Sku]
, [Lot]
, [Qty]
, [EffectiveDate]
, [Flag]
, [TranType]
, [RunningTotal]
, [AddWho]
FROM [BILLING_SUMMARY_CUT] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_BILLING_SUMMARY_CUT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_BILLING_SUMMARY_CUT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_BILLING_SUMMARY_CUT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_BILLING_SUMMARY_CUT] TO [NSQL]
GO
