SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_BILLING_DETAIL_CUT] 
AS 
SELECT [StorerKey]
, [Sku]
, [Lot]
, [Qty]
, [EffectiveDate]
, [Flag]
, [TranType]
, [RunningTotal]
FROM [BILLING_DETAIL_CUT] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_BILLING_DETAIL_CUT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_BILLING_DETAIL_CUT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_BILLING_DETAIL_CUT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_BILLING_DETAIL_CUT] TO [NSQL]
GO
