SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_BRIO_SECURITY_USER] as
select * from JPTSecure..Brio_Security_User
GO
GRANT DELETE ON  [dbo].[V_BRIO_SECURITY_USER] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_BRIO_SECURITY_USER] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_BRIO_SECURITY_USER] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_BRIO_SECURITY_USER] TO [NSQL]
GO
