SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_BRIO_SECURITY_GROUP] as
select * from JPTSecure..Brio_Security_Group

GO
GRANT DELETE ON  [dbo].[V_BRIO_SECURITY_GROUP] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_BRIO_SECURITY_GROUP] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_BRIO_SECURITY_GROUP] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_BRIO_SECURITY_GROUP] TO [NSQL]
GO
