SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_CALENDAR]
AS
SELECT [CalendarGroup]
, [Description]
, [AddDate]
, [AddWho]
, [EditDate]
, [EditWho]
FROM [CALENDAR] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_CALENDAR] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_CALENDAR] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_CALENDAR] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_CALENDAR] TO [NSQL]
GO
