SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

--ChannelItran
CREATE OR ALTER VIEW [dbo].[V_ChannelITran] AS SELECT * FROM ChannelITran WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_ChannelITran] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ChannelITran] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ChannelITran] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ChannelITran] TO [NSQL]
GO
