SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
  
CREATE VIEW [dbo].[V_GUIDETAIL]   
AS   
SELECT *  
FROM [GUIDETAIL] (NOLOCK)   
  
GO
GRANT DELETE ON  [dbo].[V_GUIDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_GUIDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_GUIDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_GUIDETAIL] TO [NSQL]
GO
