SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO


CREATE VIEW [dbo].[v_GVTLog] 
AS
SELECT * FROM dbo.GVTLog (NOLOCK)
GO
GRANT DELETE ON  [dbo].[v_GVTLog] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[v_GVTLog] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[v_GVTLog] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[v_GVTLog] TO [NSQL]
GO
