SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_HIERROR]
AS
SELECT [HiErrorGroup]
, [ErrorText]
, [ErrorType]
, [SourceKey]
, [AddDate]
, [AddWho]
, [EditDate]
, [EditWho]
, [TrafficCop]
, [TimeStamp]
FROM [HIERROR] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_HIERROR] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_HIERROR] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_HIERROR] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_HIERROR] TO [NSQL]
GO
