SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_idsPallet] AS SELECT * FROM idsPallet WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_idsPallet] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_idsPallet] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_idsPallet] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_idsPallet] TO [NSQL]
GO
