SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_IN_LINE]
AS
SELECT *
FROM INDTSITF..IN_LINE (NOLOCK)

GO
GRANT DELETE ON  [dbo].[V_IN_LINE] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_IN_LINE] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_IN_LINE] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_IN_LINE] TO [NSQL]
GO
