SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [dbo].[V_Index]
AS 
   select TABLE_NAME, CONSTRAINT_NAME,  ORDINAL_POSITION , COLUMN_NAME
   from INFORMATION_SCHEMA.KEY_COLUMN_USAGE



GO
GRANT DELETE ON  [dbo].[V_Index] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_Index] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_Index] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_Index] TO [NSQL]
GO
