SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

--ITRN
CREATE OR ALTER VIEW [dbo].[V_ITRN] AS SELECT * FROM ITRN WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_ITRN] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ITRN] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ITRN] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ITRN] TO [NSQL]
GO
