SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_LOT] AS SELECT * FROM LOT WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_LOT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_LOT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_LOT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_LOT] TO [NSQL]
GO
