SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_LOTNEWBILLTHRUDATE]
AS
SELECT [Lot]
, [BillThruDate]
, [AddWho]
FROM [LOTNEWBILLTHRUDATE] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_LOTNEWBILLTHRUDATE] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_LOTNEWBILLTHRUDATE] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_LOTNEWBILLTHRUDATE] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_LOTNEWBILLTHRUDATE] TO [NSQL]
GO
