SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_MBOLShipLog]
AS
SELECT [StorerKey]
, [MBOLKey]
, [Status]
FROM [MBOLShipLog] (NOLOCK)



GO
GRANT DELETE ON  [dbo].[V_MBOLShipLog] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_MBOLShipLog] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_MBOLShipLog] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_MBOLShipLog] TO [NSQL]
GO
