SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_MESSAGE_TEXT]
AS
SELECT [MsgId]
, [MsgLangId]
, [MsgTitle]
, [MsgText]
FROM [MESSAGE_TEXT] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_MESSAGE_TEXT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_MESSAGE_TEXT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_MESSAGE_TEXT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_MESSAGE_TEXT] TO [NSQL]
GO
