SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_NCOUNTERTRACE]
AS
SELECT [keyname]
, [keycount]
FROM [NCOUNTERTRACE] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_NCOUNTERTRACE] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_NCOUNTERTRACE] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_NCOUNTERTRACE] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_NCOUNTERTRACE] TO [NSQL]
GO
