SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_NSQLCONFIG]
AS
SELECT [ConfigKey]
, [NSQLValue]
, [NSQLDefault]
, [NSQLDescrip]
, [AddDate]
, [AddWho]
, [EditDate]
, [EditWho]
, [TrafficCop]
, [Timestamp]
FROM [NSQLCONFIG] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_NSQLCONFIG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_NSQLCONFIG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_NSQLCONFIG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_NSQLCONFIG] TO [NSQL]
GO
