SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW DBO.V_ORDERDETAIL_SUM
AS SELECT ORDERS.Orderkey,
ORDERS.StorerKey,
TotalOrderQty = SUM(Orderdetail.Openqty),
NoOrderLine = COUNT(1)
FROM ORDERS WITH (NOLOCK)
LEFT JOIN ORDERDETAIL WITH (NOLOCK) ON ORDERDETAIL.orderkey = ORDERS.orderkey
GROUP BY ORDERS.Orderkey,
ORDERS.StorerKey
GO
GRANT SELECT ON [dbo].[V_ORDERDETAIL_SUM] TO NSQL
GO
