SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_ORDERS]
AS
SELECT *
      ,ltrim(rtrim(BillToKey)) + ltrim(rtrim(ConsigneeKey)) AS ShipToCode
FROM [dbo].[ORDERS] WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_ORDERS] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ORDERS] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ORDERS] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ORDERS] TO [NSQL]
GO
