SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
--ORDERDETAIL  
CREATE VIEW [dbo].[V_ORDERDETAIL] AS SELECT * FROM ORDERDETAIL WITH (NOLOCK)    
GO
GRANT DELETE ON  [dbo].[V_ORDERDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ORDERDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ORDERDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ORDERDETAIL] TO [NSQL]
GO
