SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_ORDERS_STATUS] AS SELECT * FROM ORDERS_STATUS WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_ORDERS_STATUS] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ORDERS_STATUS] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ORDERS_STATUS] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ORDERS_STATUS] TO [NSQL]
GO
