SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
--orderinfo
CREATE VIEW [dbo].[V_ORDERinfo] AS SELECT * FROM ORDERinfo WITH (NOLOCK)  
GO
GRANT DELETE ON  [dbo].[V_ORDERinfo] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_ORDERinfo] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_ORDERinfo] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_ORDERinfo] TO [NSQL]
GO
