SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_PALLETMGMTDETAIL]
AS
SELECT *
FROM dbo.PALLETMGMTDETAIL WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_PALLETMGMTDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PALLETMGMTDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PALLETMGMTDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PALLETMGMTDETAIL] TO [NSQL]
GO
