SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [dbo].[V_PackHeader] AS SELECT * FROM dbo.PackHeader WITH (NOLOCK)  
GO
GRANT DELETE ON  [dbo].[V_PackHeader] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PackHeader] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PackHeader] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PackHeader] TO [NSQL]
GO
