SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_PHY_INV2A_LOT]
AS
SELECT [StorerKey]
, [Sku]
, [Lot]
, [QtyTeamA]
, [QtyLOTxLOCxID]
FROM [PHY_INV2A_LOT] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_PHY_INV2A_LOT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PHY_INV2A_LOT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PHY_INV2A_LOT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PHY_INV2A_LOT] TO [NSQL]
GO
