SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_PHY_POST_DETAIL] 
AS 
SELECT [StorerKey]
, [Sku]
, [Loc]
, [Lot]
, [Id]
, [QtyTeamA]
, [QtyLOTxLOCxID]
FROM [PHY_POST_DETAIL] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_PHY_POST_DETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PHY_POST_DETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PHY_POST_DETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PHY_POST_DETAIL] TO [NSQL]
GO
