SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_PHY_A2B_SKU] 
AS 
SELECT [StorerKey]
, [Sku]
, [QtyTeamA]
, [QtyTeamB]
FROM [PHY_A2B_SKU] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_PHY_A2B_SKU] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PHY_A2B_SKU] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PHY_A2B_SKU] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PHY_A2B_SKU] TO [NSQL]
GO
