SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_PHY_INV2A_ID] 
AS 
SELECT [StorerKey]
, [Sku]
, [Id]
, [QtyTeamA]
, [QtyLOTxLOCxID]
FROM [PHY_INV2A_ID] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_PHY_INV2A_ID] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PHY_INV2A_ID] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PHY_INV2A_ID] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PHY_INV2A_ID] TO [NSQL]
GO
