SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_PHY_POSTED]
AS
SELECT [StorerKey]
, [Sku]
, [QtyTeamA]
, [QtyLOTxLOCxID]
, [ErrorMessage]
FROM [PHY_POSTED] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_PHY_POSTED] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PHY_POSTED] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PHY_POSTED] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PHY_POSTED] TO [NSQL]
GO
