SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_PHY_A2B_LOT] 
AS 
SELECT [StorerKey]
, [Sku]
, [Loc]
, [Lot]
, [QtyTeamA]
, [QtyTeamB]
FROM [PHY_A2B_LOT] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_PHY_A2B_LOT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PHY_A2B_LOT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PHY_A2B_LOT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PHY_A2B_LOT] TO [NSQL]
GO
