SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE   VIEW [dbo].[V_PICKDETAIL]      
AS  
SELECT  * 
FROM [dbo].[PICKDETAIL] WITH (NOLOCK)        

GO
GRANT DELETE ON  [dbo].[V_PICKDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PICKDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PICKDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PICKDETAIL] TO [NSQL]
GO
