SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_POLL_ALLOCATE]
AS
SELECT [orderkey]
, [EffectiveDate]
, [RetryCount]
, [AddDate]
, [AddWho]
, [EditDate]
, [EditWho]
, [TrafficCop]
, [ArchiveCop]
, [TimeStamp]
FROM [POLL_ALLOCATE] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_POLL_ALLOCATE] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_POLL_ALLOCATE] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_POLL_ALLOCATE] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_POLL_ALLOCATE] TO [NSQL]
GO
