SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
--PODETAIL
CREATE VIEW [dbo].[V_PODetail] AS SELECT * FROM PODETAIL WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_PODetail] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PODetail] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PODetail] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PODetail] TO [NSQL]
GO
