SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_POLL_SHIP]
AS
SELECT [Caseid]
, [RetryCount]
, [EffectiveDate]
, [AddDate]
, [AddWho]
, [EditDate]
, [EditWho]
, [TrafficCop]
, [ArchiveCop]
FROM [POLL_SHIP] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_POLL_SHIP] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_POLL_SHIP] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_POLL_SHIP] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_POLL_SHIP] TO [NSQL]
GO
