SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_PTRACEDETAIL] 
AS 
SELECT [PTRACETYPE]
, [PTRACEHEADKey]
, [PA_PutawayStrategyKey]
, [PA_PutawayStrategyLineNumber]
, [PTraceDetailKey]
, [LocKey]
, [Reason]
FROM [PTRACEDETAIL] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_PTRACEDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PTRACEDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PTRACEDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PTRACEDETAIL] TO [NSQL]
GO
