SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_PTRACEHEAD] 
AS 
SELECT [PTRACETYPE]
, [PTRACEHEADKey]
, [Userid]
, [StorerKey]
, [Sku]
, [Lot]
, [ID]
, [PackKey]
, [Qty]
, [PA_MultiProduct]
, [PA_MultiLot]
, [StartTime]
, [EndTime]
, [PA_LocsReviewed]
, [PA_LocFound]
FROM [PTRACEHEAD] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_PTRACEHEAD] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_PTRACEHEAD] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_PTRACEHEAD] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_PTRACEHEAD] TO [NSQL]
GO
