SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_RDT_StdEventLog]
AS
SELECT     RDT.rdtSTDEventLog.*
FROM         RDT.rdtSTDEventLog

GO
GRANT DELETE ON  [dbo].[V_RDT_StdEventLog] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_RDT_StdEventLog] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_RDT_StdEventLog] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_RDT_StdEventLog] TO [NSQL]
GO
