SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_RDT_StdEventLog]
AS
SELECT     RDT.rdtSTDEventLog.*
FROM         RDT.rdtSTDEventLog

GO
GRANT DELETE ON  [dbo].[V_RDT_StdEventLog] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_RDT_StdEventLog] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_RDT_StdEventLog] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_RDT_StdEventLog] TO [NSQL]
GO
