SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_RDTPrintJob]
AS
SELECT     RDT.RDTPrintJob.*
FROM         RDT.RDTPrintJob

GO
GRANT DELETE ON  [dbo].[V_RDTPrintJob] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_RDTPrintJob] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_RDTPrintJob] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_RDTPrintJob] TO [NSQL]
GO
