SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_RDTPickLock]
AS
SELECT     RDT.rdtPickLock.*
FROM         RDT.rdtPickLock   (NOLOCK)

GO
GRANT DELETE ON  [dbo].[V_RDTPickLock] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_RDTPickLock] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_RDTPickLock] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_RDTPickLock] TO [NSQL]
GO
