SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_rdtPTLStationLogQueue]
AS
SELECT *
FROM rdt.rdtPTLStationLogQueue WITH (NOLOCK)
GO
GRANT SELECT ON  [dbo].[V_rdtPTLStationLogQueue] TO [NSQL]
GO
