SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_RECUPLOAD] 
AS 
SELECT [STORERKEY]
, [SKU]
, [Qty]
, [LOC]
, [Flag]
, [Message]
FROM [RECUPLOAD] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_RECUPLOAD] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_RECUPLOAD] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_RECUPLOAD] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_RECUPLOAD] TO [NSQL]
GO
