SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO


CREATE View [dbo].[V_RFIDMaster]
as
SELECT * from dbo.RFIDMaster (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_RFIDMaster] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_RFIDMaster] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_RFIDMaster] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_RFIDMaster] TO [NSQL]
GO
