SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_RFDB_LOG] 
AS 
SELECT [adddate]
, [user_id]
, [message]
FROM [RFDB_LOG] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_RFDB_LOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_RFDB_LOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_RFDB_LOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_RFDB_LOG] TO [NSQL]
GO
