SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_RouteMaster] 
AS 
SELECT *
FROM [RouteMaster] WITH (NOLOCK) 

--SELECT TOP 30 * FROM V_RouteMaster ORDER BY 1 DESC
GO
GRANT DELETE ON  [dbo].[V_RouteMaster] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_RouteMaster] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_RouteMaster] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_RouteMaster] TO [NSQL]
GO
