SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_SerialNo] AS SELECT * FROM SerialNo WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_SerialNo] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_SerialNo] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_SerialNo] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_SerialNo] TO [NSQL]
GO
