SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [dbo].[V_SEQKey]
as
SELECT * from SEQKey
GO
GRANT DELETE ON  [dbo].[V_SEQKey] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_SEQKey] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_SEQKey] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_SEQKey] TO [NSQL]
GO
