SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_SKULog]
AS
SELECT [Person]
, [ActionTime]
, [ActionDescr]
FROM [SKULog] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_SKULog] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_SKULog] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_SKULog] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_SKULog] TO [NSQL]
GO
