SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_StoreToLocDetail] 
AS
	SELECT *
FROM StoreToLOCDetail WITH (NOLOCK)

GO
GRANT DELETE ON  [dbo].[V_StoreToLocDetail] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_StoreToLocDetail] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_StoreToLocDetail] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_StoreToLocDetail] TO [NSQL]
GO
