SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE View [dbo].[V_STORER]
as
SELECT * from Storer (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_STORER] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_STORER] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_STORER] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_STORER] TO [NSQL]
GO
