SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_TARIFFxFACILITY] 
AS 
SELECT [Facility]
, [StorerKey]
, [Sku]
, [Tariffkey]
, [AddDate]
, [AddWho]
, [EditDate]
, [EditWho]
, [TrafficCop]
, [ArchiveCop]
FROM [TARIFFxFACILITY] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_TARIFFxFACILITY] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_TARIFFxFACILITY] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_TARIFFxFACILITY] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_TARIFFxFACILITY] TO [NSQL]
GO
