SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

--TRANSFERDETAIL
CREATE OR ALTER VIEW [dbo].[V_TRANSFERDETAIL] AS SELECT * FROM TRANSFERDETAIL WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_TRANSFERDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_TRANSFERDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_TRANSFERDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_TRANSFERDETAIL] TO [NSQL]
GO
