SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_TrackingID] AS
   SELECT *
   FROM dbo.TrackingID WITH (NOLOCK)

GO
GRANT SELECT ON  [dbo].[V_TrackingID] TO [NSQL]
GO
