SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_UPLOADC4ORDERHEADER] AS SELECT * FROM UPLOADC4ORDERHEADER WITH (NOLOCK)  
GO
GRANT DELETE ON  [dbo].[V_UPLOADC4ORDERHEADER] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_UPLOADC4ORDERHEADER] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_UPLOADC4ORDERHEADER] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_UPLOADC4ORDERHEADER] TO [NSQL]
GO
