SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_UploadC4PODetail] AS SELECT * FROM UploadC4PODetail WITH (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_UploadC4PODetail] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_UploadC4PODetail] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_UploadC4PODetail] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_UploadC4PODetail] TO [NSQL]
GO
