SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_UPLOADPOHeader] 
AS 
SELECT [POkey]
, [ExternPOKey]
, [POGROUP]
, [Storerkey]
, [POType]
, [SellerName]
, [MODE]
, [STATUS]
, [REMARKS]
, [LoadingDate]
, [adddate]
FROM [UPLOADPOHeader] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_UPLOADPOHeader] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_UPLOADPOHeader] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_UPLOADPOHeader] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_UPLOADPOHeader] TO [NSQL]
GO
