SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_WAVEDETAIL]
AS
SELECT [WaveDetailKey]
, [WaveKey]
, [OrderKey]
, [ProcessFlag]
, [AddDate]
, [AddWho]
, [EditDate]
, [EditWho]
, [TrafficCop]
, [ArchiveCop]
FROM [WAVEDETAIL] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_WAVEDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_WAVEDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_WAVEDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_WAVEDETAIL] TO [NSQL]
GO
