SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_WMSEXPKIT]
AS
SELECT [KITKey]
, [KITLineNumber]
, [Type]
, [CustRef]
, [ReasonCode]
, [Sku]
, [LOTTABLE01]
, [LOTTABLE02]
, [LOTTABLE03]
, [LOTTABLE04]
, [LOTTABLE05]
, [Qty]
, [HostWHCode]
, [TransFlag]
FROM [WMSEXPKIT] (NOLOCK)
GO
GRANT DELETE ON  [dbo].[V_WMSEXPKIT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_WMSEXPKIT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_WMSEXPKIT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_WMSEXPKIT] TO [NSQL]
GO
