SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [dbo].[V_WMSEXPINVHOLD] 
AS 
SELECT [Transmitlogkey]
, [InventoryHoldKey]
, [Loc]
, [FromWhCode]
, [TOWhCode]
, [Lottable01]
, [Lottable02]
, [Lottable03]
, [Lottable04]
, [Lottable05]
, [Sku]
, [Qty]
, [TransFlag]
FROM [WMSEXPINVHOLD] (NOLOCK) 
GO
GRANT DELETE ON  [dbo].[V_WMSEXPINVHOLD] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[V_WMSEXPINVHOLD] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[V_WMSEXPINVHOLD] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[V_WMSEXPINVHOLD] TO [NSQL]
GO
