SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [dbo].[V_WorkOrderDetail] 
AS 
SELECT * FROM WorkOrderDetail WITH (NOLOCK)
GO

GRANT SELECT ON  [dbo].[V_WorkOrderDetail] TO [NSQL]
GO
