CREATE TABLE [dbo].[ADJUSTMENTDETAIL_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[AdjustmentKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AdjustmentLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ADJUSTMENTDETAIL_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_ADJUSTMENTDETAIL_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ADJUSTMENTDETAIL_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADJUSTMENTDETAIL_DELLOG] ADD CONSTRAINT [PK__ADJUSTMENTDETAIL__0623C4D8] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[ADJUSTMENTDETAIL_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[ADJUSTMENTDETAIL_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[ADJUSTMENTDETAIL_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[ADJUSTMENTDETAIL_DELLOG] TO [NSQL]
GO
