IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'DBO' AND TABLE_NAME = 'CartonTrack' AND COLUMN_NAME = 'Cost')
BEGIN
  ALTER TABLE dbo.CartonTrack ADD Cost FLOAT NULL DEFAULT 0
END;
GO