IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'RDT' AND TABLE_NAME = 'RDTUser' AND COLUMN_NAME = 'Password')
BEGIN
  ALTER TABLE RDT.RDTUser ALTER COLUMN Password NVARCHAR(32) NOT NULL
END;
GO