IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ARCHIVEPARAMETERSLOG' AND TABLE_SCHEMA = 'DBO' )
BEGIN

CREATE TABLE [dbo].[ARCHIVEPARAMETERSLOG](
   [RowRef] INT IDENTITY (1,1) NOT NULL,
	[Archivekey] [nvarchar](10) NOT NULL,
	[CopyRowsToArchiveDatabase] [nvarchar](1) NOT NULL,
	[ArchiveDataBaseName] [nvarchar](30) NULL,
	[LiveDataBaseName] [nvarchar](30) NULL,
	[ShipNumberofDaysToRetain] [int] NOT NULL,
	[ShipActive] [nvarchar](2) NOT NULL,
	[ShipStorerKeyStart] [nvarchar](15) NOT NULL,
	[ShipStorerKeyEnd] [nvarchar](15) NOT NULL,
	[ShipSysOrdStart] [nvarchar](10) NOT NULL,
	[ShipSysOrdEnd] [nvarchar](10) NOT NULL,
	[ShipExternOrderKeyStart] [nvarchar](30) NOT NULL,
	[ShipExternOrderKeyEnd] [nvarchar](30) NOT NULL,
	[ShipOrdTypStart] [nvarchar](10) NOT NULL,
	[ShipOrdTypEnd] [nvarchar](10) NOT NULL,
	[ShipOrdGrpStart] [nvarchar](20) NOT NULL,
	[ShipOrdGrpEnd] [nvarchar](20) NOT NULL,
	[ShipToStart] [nvarchar](15) NOT NULL,
	[ShipToEnd] [nvarchar](15) NOT NULL,
	[ShipBillToStart] [nvarchar](15) NOT NULL,
	[ShipBillToEnd] [nvarchar](15) NOT NULL,
	[ShipmentOrderDateType] [nvarchar](10) NOT NULL,
	[AdjNumberofDaysToRetain] [int] NOT NULL,
	[AdjActive] [nvarchar](2) NOT NULL,
	[AdjStart] [nvarchar](10) NOT NULL,
	[AdjEnd] [nvarchar](10) NOT NULL,
	[AdjustmentDateType] [nvarchar](10) NOT NULL,
	[TranNumberofDaysToRetain] [int] NOT NULL,
	[TranActive] [nvarchar](2) NOT NULL,
	[TranStart] [nvarchar](10) NOT NULL,
	[TranEnd] [nvarchar](10) NOT NULL,
	[TransferDateType] [nvarchar](10) NOT NULL,
	[PONumberofDaysToRetain] [int] NOT NULL,
	[POActive] [nvarchar](2) NOT NULL,
	[POStorerKeyStart] [nvarchar](15) NOT NULL,
	[POStorerKeyEnd] [nvarchar](15) NOT NULL,
	[POStart] [nvarchar](18) NOT NULL,
	[POEnd] [nvarchar](18) NOT NULL,
	[PODateType] [nvarchar](10) NOT NULL,
	[ReceiptNumberofDaysToRetain] [int] NOT NULL,
	[ReceiptActive] [nvarchar](2) NOT NULL,
	[ReceiptStorerKeyStart] [nvarchar](15) NOT NULL,
	[ReceiptStorerKeyEnd] [nvarchar](15) NOT NULL,
	[ReceiptStart] [nvarchar](10) NOT NULL,
	[ReceiptEnd] [nvarchar](10) NOT NULL,
	[ReceiptDateType] [nvarchar](10) NOT NULL,
	[ItrnNumberofDaysToRetain] [int] NOT NULL,
	[ItrnActive] [nvarchar](2) NOT NULL,
	[ItrnStorerKeyStart] [nvarchar](15) NOT NULL,
	[ItrnStorerKeyEnd] [nvarchar](15) NOT NULL,
	[ItrnSkuStart] [nvarchar](20) NOT NULL,
	[ItrnSkuEnd] [nvarchar](20) NOT NULL,
	[ItrnLotStart] [nvarchar](15) NOT NULL,
	[ItrnLotEnd] [nvarchar](15) NOT NULL,
	[ItrnDateType] [nvarchar](10) NOT NULL,
	[MAWBNumberofDaysToRetain] [int] NOT NULL,
	[MAWBActive] [nvarchar](2) NOT NULL,
	[MAWBStart] [nvarchar](15) NOT NULL,
	[MAWBEnd] [nvarchar](15) NOT NULL,
	[MAWBDateType] [nvarchar](10) NOT NULL,
	[HAWBNumberofDaysToRetain] [int] NOT NULL,
	[HAWBActive] [nvarchar](2) NOT NULL,
	[HAWBStart] [nvarchar](15) NOT NULL,
	[HAWBEnd] [nvarchar](15) NOT NULL,
	[HAWBDateType] [nvarchar](10) NOT NULL,
	[ContainerNumberofDaysToRetain] [int] NOT NULL,
	[ContainerActive] [nvarchar](2) NOT NULL,
	[ContainerStart] [nvarchar](20) NOT NULL,
	[ContainerEnd] [nvarchar](20) NOT NULL,
	[ContainerDateType] [nvarchar](10) NOT NULL,
	[PalletNumberofDaysToRetain] [int] NOT NULL,
	[PalletActive] [nvarchar](2) NOT NULL,
	[PalletStart] [nvarchar](10) NOT NULL,
	[PalletEnd] [nvarchar](10) NOT NULL,
	[PalletDateType] [nvarchar](10) NOT NULL,
	[CaseMNumberofDaysToRetain] [int] NOT NULL,
	[CaseMActive] [nvarchar](2) NOT NULL,
	[CaseMStorerKeyStart] [nvarchar](15) NOT NULL,
	[CaseMStorerKeyEnd] [nvarchar](15) NOT NULL,
	[CaseMStart] [nvarchar](20) NOT NULL,
	[CaseMEnd] [nvarchar](20) NOT NULL,
	[CaseMDateType] [nvarchar](10) NOT NULL,
	[MbolNumberofDaysToRetain] [int] NOT NULL,
	[MbolActive] [nvarchar](2) NOT NULL,
	[MbolStart] [nvarchar](10) NOT NULL,
	[MbolEnd] [nvarchar](10) NOT NULL,
	[MBOLDepDateStart] [datetime] NOT NULL,
	[MBOLDepDateEnd] [datetime] NOT NULL,
	[MBOLDelDateStart] [datetime] NOT NULL,
	[MBOLDelDateEnd] [datetime] NOT NULL,
	[MbolVoyageStart] [nvarchar](30) NOT NULL,
	[MbolVoyageEnd] [nvarchar](30) NOT NULL,
	[MBOLDateType] [nvarchar](10) NOT NULL,
	[PickDateType] [nvarchar](10) NOT NULL,
	[AddDate] [datetime] NOT NULL,
	[AddWho] [nvarchar](128) NOT NULL,
	[EditDate] [datetime] NOT NULL,
	[EditWho] [nvarchar](128) NOT NULL,
	[TrafficCop] [nvarchar](1) NULL,
	[ArchiveCop] [nvarchar](1) NULL,
	[Timestamp] [timestamp] NOT NULL,
	[CCNumberofDaysToRetain] [int] NOT NULL,
	[CCActive] [nvarchar](2) NOT NULL,
	[CCStart] [nvarchar](10) NOT NULL,
	[CCEnd] [nvarchar](10) NOT NULL,
	[CCDateType] [nvarchar](10) NOT NULL,
	[AlertNumberofDaysToRetain] [int] NOT NULL,
	[AlertActive] [nvarchar](2) NOT NULL,
	[AlertStart] [nvarchar](18) NOT NULL,
	[AlertEnd] [nvarchar](18) NOT NULL,
	[AlertDateType] [nvarchar](10) NOT NULL,
	[RFDBLogNumberofDaysToRetain] [int] NOT NULL,
	[RFDBLogActive] [nvarchar](2) NOT NULL,
	[RFDBLogDateType] [nvarchar](10) NOT NULL,
	[SKULogNumberofDaysToRetain] [int] NOT NULL,
	[SKULogActive] [nvarchar](2) NOT NULL,
	[SKULogDateType] [nvarchar](10) NOT NULL,
	[ErrLogNumberofDaysToRetain] [int] NOT NULL,
	[ErrLogActive] [nvarchar](2) NOT NULL,
	[ErrLogDateType] [nvarchar](10) NOT NULL,
	[PackLogNumberofDaysToRetain] [int] NOT NULL,
	[PackLogActive] [nvarchar](2) NOT NULL,
	[PackLogStart] [nvarchar](10) NOT NULL,
	[PackLogEnd] [nvarchar](10) NOT NULL,
	[PackLogDateType] [nvarchar](10) NOT NULL,
	[TranmLogNumberofDaysToRetain] [int] NOT NULL,
	[TranmLogActive] [nvarchar](2) NOT NULL,
	[TranmLogStart] [nvarchar](10) NOT NULL,
	[TranmLogEnd] [nvarchar](10) NOT NULL,
	[TranmLogDateType] [nvarchar](10) NOT NULL,
	[OrdersLogNumberofDaysToRetain] [int] NOT NULL,
	[OrdersLogActive] [nvarchar](2) NOT NULL,
	[OrdersLogStart] [nvarchar](10) NOT NULL,
	[OrdersLogEnd] [nvarchar](10) NOT NULL,
	[OrdersLogDateType] [nvarchar](10) NOT NULL,
	[InvrptLogNumberofDaysToRetain] [int] NOT NULL,
	[InvrptLogActive] [nvarchar](2) NOT NULL,
	[InvrptLogStart] [nvarchar](10) NOT NULL,
	[InvrptLogEnd] [nvarchar](10) NOT NULL,
	[InvrptLogDateType] [nvarchar](10) NOT NULL,
	[TrigLogNumberofDaysToRetain] [int] NOT NULL,
	[TrigLogActive] [nvarchar](2) NOT NULL,
	[TrigLogStart] [nvarchar](10) NOT NULL,
	[TrigLogEnd] [nvarchar](10) NOT NULL,
	[TrigLogDateType] [nvarchar](10) NOT NULL,
	[PTraceNumberofDaysToRetain] [int] NOT NULL,
	[PTraceActive] [nvarchar](2) NOT NULL,
	[PTraceStart] [nvarchar](10) NOT NULL,
	[PTraceEnd] [nvarchar](10) NOT NULL,
	[PTraceDateType] [nvarchar](10) NOT NULL,
	[REPLENISHNumberofDaysToRetain] [int] NOT NULL,
	[REPLENISHActive] [nvarchar](2) NOT NULL,
	[REPLENISHStart] [nvarchar](10) NOT NULL,
	[REPLENISHEnd] [nvarchar](10) NOT NULL,
	[REPLENISHDateType] [nvarchar](10) NOT NULL,
	[IDActive] [nvarchar](2) NOT NULL,
	[IDStart] [nvarchar](18) NOT NULL,
	[IDEnd] [nvarchar](18) NOT NULL,
	[InvQCNumberofDaysToRetain] [int] NOT NULL,
	[InvQCActive] [nvarchar](2) NOT NULL,
	[InvQCStart] [nvarchar](10) NOT NULL,
	[InvQCEnd] [nvarchar](10) NOT NULL,
	[InvQCDateType] [nvarchar](10) NOT NULL,
	[InvHoldNumberofDaysToRetain] [int] NOT NULL,
	[InvHoldActive] [nvarchar](2) NOT NULL,
	[InvHoldStart] [nvarchar](10) NOT NULL,
	[InvHoldEnd] [nvarchar](10) NOT NULL,
	[InvHoldDateType] [nvarchar](10) NOT NULL,
	[PLSNumberofDaysToRetain] [int] NOT NULL,
	[PLSActive] [nvarchar](2) NOT NULL,
	[PLSStart] [nvarchar](10) NOT NULL,
	[PLSEnd] [nvarchar](10) NOT NULL,
	[PLSDateType] [nvarchar](10) NOT NULL,
	[KITNumberofDaysToRetain] [int] NOT NULL,
	[KITActive] [nvarchar](2) NOT NULL,
	[KITStart] [nvarchar](10) NOT NULL,
	[KITEnd] [nvarchar](10) NOT NULL,
	[KITDateType] [nvarchar](10) NOT NULL,
	[GUINumberofDaysToRetain] [int] NOT NULL,
	[GUIActive] [nvarchar](2) NOT NULL,
	[GUIInvoiceNoStart] [nvarchar](10) NOT NULL,
	[GUIInvoiceNoEnd] [nvarchar](10) NOT NULL,
	[GUIDateType] [nvarchar](10) NOT NULL,
	[RdsPoNumberofDaysToRetain] [int] NULL,
	[RdsPodatetype] [nvarchar](10) NULL,
	[RdsPoActive] [nvarchar](2) NULL,
	[RdsPoStart] [int] NULL,
	[RdsPoEnd] [int] NULL,
	[RdsOrdersNumberofDaysToRetain] [int] NULL,
	[RdsOrdersdatetype] [nvarchar](10) NULL,
	[RdsOrdersActive] [nvarchar](2) NULL,
	[RdsOrdersStart] [int] NULL,
	[RdsOrdersEnd] [int] NULL,
	[DailyInvNoofDaysToRetain] [int] NULL,
	[DailyInvActive] [nvarchar](2) NULL,
	[DailyInvStart] [nvarchar](10) NULL,
	[DailyInvEnd] [nvarchar](10) NULL,
	[DailyInvDateType] [nvarchar](10) NULL,
	[DelPickslipNoofDaysToRetain] [int] NULL,
	[DelPickslipActive] [nvarchar](2) NULL,
	[DelPickslipStart] [nvarchar](10) NULL,
	[DelPickslipEnd] [nvarchar](10) NULL,
	[DelPickslipDateType] [nvarchar](10) NULL,
	[SMSPODNumberofDaysToRetain] [int] NULL,
	[SMSPODActive] [nvarchar](2) NULL,
	[SMSPODDateType] [nvarchar](10) NULL,
 CONSTRAINT [PK_ARCHIVEPARAMETERSLOG] PRIMARY KEY CLUSTERED 
(
	 [RowRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

END
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON [ARCHIVEPARAMETERSLOG] TO NSQL
GO