IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ARCHIVEPARAMETERS_LOG' AND TABLE_SCHEMA = 'dbo')
BEGIN
CREATE TABLE [dbo].[ARCHIVEPARAMETERS_LOG](
	[RowRef] [int] IDENTITY(1,1) NOT NULL,
	[ArchiveKey] [nvarchar](10) NOT NULL,
	[FieldName] [nvarchar](60) NULL CONSTRAINT [DF_ARCHIVEPARAMETERS_LOG_FieldName]  DEFAULT (''),
	[OldValue] [nvarchar](60) NULL CONSTRAINT [DF_ARCHIVEPARAMETERS_LOG_OldValue]  DEFAULT (''),
	[NewValue] [nvarchar](60) NULL  CONSTRAINT [DF_ARCHIVEPARAMETERS_LOG_NewValue]  DEFAULT (''),
   [ProgramName] [nvarchar](128) NULL CONSTRAINT [DF_ARCHIVEPARAMETERS_LOG_ProgramName]  DEFAULT (OBJECT_NAME(@@PROCID)),
	[EditWho] [nvarchar](128) NULL  CONSTRAINT [DF_ARCHIVEPARAMETERS_LOG_EditWho]  DEFAULT (SUSER_SNAME()),
	[EditDate] [datetime] NULL CONSTRAINT [DF_ARCHIVEPARAMETERS_LOG_EditDate]  DEFAULT (GETDATE()),
	[TrafficCop] [nvarchar](1) NULL,
	[ArchiveCop] [nvarchar](1) NULL,
 CONSTRAINT [PKARCHIVEPARAMETERS_LOG] PRIMARY KEY CLUSTERED 
(
	[RowRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80)
)ON [PRIMARY]
END
