IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ARCHIVEPARAMETERS_DELLOG' AND TABLE_SCHEMA = 'DBO' )
BEGIN

CREATE TABLE [dbo].[ARCHIVEPARAMETERS_DELLOG](
   [RowRef] INT IDENTITY (1,1) NOT NULL,
	[Archivekey] [nvarchar](10) NOT NULL,
   [Status] [nvarchar](1) NOT NULL CONSTRAINT DF_ARCHIVEPARAMETERS_DELLOG_Status DEFAULT ('0'),
   [AddDate]   datetime NOT NULL CONSTRAINT DF_ARCHIVEPARAMETERS_DELLOG_AddDate DEFAULT (getdate()),
   [AddWho]    nvarchar (128) NOT NULL  CONSTRAINT DF_ARCHIVEPARAMETERS_DELLOG_AddWho DEFAULT (suser_name()),
   [ArchiveCop]  nvarchar(1) NULL,
 CONSTRAINT [PK_ARCHIVEPARAMETERS_DELLOG] PRIMARY KEY CLUSTERED 
(
	 [RowRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
END
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON [ARCHIVEPARAMETERS_DELLOG] TO NSQL
GO