CREATE TABLE [dbo].[BTB_FTA_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[BTB_FTAKey] [int] NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_BTB_FTA_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_BTB_FTA_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_BTB_FTA_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BTB_FTA_DELLOG] ADD CONSTRAINT [PK__BTB_FTA___78C977972BCB7466] PRIMARY KEY CLUSTERED ([Rowref]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[BTB_FTA_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[BTB_FTA_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[BTB_FTA_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[BTB_FTA_DELLOG] TO [NSQL]
GO
