CREATE TABLE [dbo].[CARTONIZATION_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[CartonizationKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CARTONIZATION_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_CARTONIZATION_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CARTONIZATION_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARTONIZATION_DELLOG] ADD CONSTRAINT [PK__CARTONIZ__78C97797C9ADFE30] PRIMARY KEY CLUSTERED ([Rowref]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[CARTONIZATION_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[CARTONIZATION_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[CARTONIZATION_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[CARTONIZATION_DELLOG] TO [NSQL]
GO
