CREATE TABLE [dbo].[CCDetail_B4Post]
(
[CCKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CCDetailKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CCSheetNo] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_CCSheetNo] DEFAULT (' '),
[TagNo] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_TagNo] DEFAULT (' '),
[Storerkey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_StorerKey] DEFAULT (' '),
[Sku] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_Sku] DEFAULT (' '),
[Lot] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_Lot] DEFAULT (' '),
[Loc] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_Loc] DEFAULT (' '),
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_id] DEFAULT (' '),
[SystemQty] [int] NOT NULL CONSTRAINT [DF_CCDetail_B4Post_SystemQty] DEFAULT ((0)),
[Qty] [int] NOT NULL CONSTRAINT [DF_CCDetail_B4Post_Qty] DEFAULT ((0)),
[Lottable01] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable02] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable03] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable04] [datetime] NULL,
[Lottable05] [datetime] NULL,
[FinalizeFlag] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_FinalizeFlag] DEFAULT ('N'),
[Qty_Cnt2] [int] NOT NULL CONSTRAINT [DF_CCDetail_B4Post_Qty_Cnt2] DEFAULT ((0)),
[Lottable01_Cnt2] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable02_Cnt2] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable03_Cnt2] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable04_Cnt2] [datetime] NULL,
[Lottable05_Cnt2] [datetime] NULL,
[FinalizeFlag_Cnt2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_FinalizeFlag_Cnt2] DEFAULT ('N'),
[Qty_Cnt3] [int] NULL CONSTRAINT [DF_CCDetail_B4Post_Qty_Cnt3] DEFAULT ((0)),
[Lottable01_Cnt3] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable02_Cnt3] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable03_Cnt3] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottable04_Cnt3] [datetime] NULL,
[Lottable05_Cnt3] [datetime] NULL,
[FinalizeFlag_Cnt3] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_FinalizeFlag_Cnt3] DEFAULT ('N'),
[Status] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_Status] DEFAULT ('0'),
[StatusMsg] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_StatusMsg] DEFAULT (' '),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_CCDetail_B4Post_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_AddWho] DEFAULT (suser_sname()),
[EditDate] [datetime] NOT NULL CONSTRAINT [DF_CCDetail_B4Post_EditDate] DEFAULT (getdate()),
[EditWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CCDetail_B4Post_EditWho] DEFAULT (suser_sname()),
[TrafficCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Timestamp] [binary] (1) NOT NULL,
[RefNo] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_REFNO] DEFAULT (' '),
[EditDate_Cnt1] [datetime] NULL,
[EditWho_Cnt1] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditDate_Cnt2] [datetime] NULL,
[EditWho_Cnt2] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditDate_Cnt3] [datetime] NULL,
[EditWho_Cnt3] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Counted_Cnt1] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Counted_Cnt1] DEFAULT ('0'),
[Counted_Cnt2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Counted_Cnt2] DEFAULT ('0'),
[Counted_Cnt3] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Counted_Cnt3] DEFAULT ('0'),
[Lottable06] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable06] DEFAULT (''),
[Lottable07] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable07] DEFAULT (''),
[Lottable08] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable08] DEFAULT (''),
[Lottable09] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable09] DEFAULT (''),
[Lottable10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable10] DEFAULT (''),
[Lottable11] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable11] DEFAULT (''),
[Lottable12] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable12] DEFAULT (''),
[Lottable13] [datetime] NULL,
[Lottable14] [datetime] NULL,
[Lottable15] [datetime] NULL,
[Lottable06_Cnt2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable06_Cnt2] DEFAULT (''),
[Lottable07_Cnt2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable07_Cnt2] DEFAULT (''),
[Lottable08_Cnt2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable08_Cnt2] DEFAULT (''),
[Lottable09_Cnt2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable09_Cnt2] DEFAULT (''),
[Lottable10_Cnt2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable10_Cnt2] DEFAULT (''),
[Lottable11_Cnt2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable11_Cnt2] DEFAULT (''),
[Lottable12_Cnt2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable12_Cnt2] DEFAULT (''),
[Lottable13_Cnt2] [datetime] NULL,
[Lottable14_Cnt2] [datetime] NULL,
[Lottable15_Cnt2] [datetime] NULL,
[Lottable06_Cnt3] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable06_Cnt3] DEFAULT (''),
[Lottable07_Cnt3] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable07_Cnt3] DEFAULT (''),
[Lottable08_Cnt3] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable08_Cnt3] DEFAULT (''),
[Lottable09_Cnt3] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable09_Cnt3] DEFAULT (''),
[Lottable10_Cnt3] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable10_Cnt3] DEFAULT (''),
[Lottable11_Cnt3] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable11_Cnt3] DEFAULT (''),
[Lottable12_Cnt3] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CCDetail_B4Post_Lottable12_Cnt3] DEFAULT (''),
[Lottable13_Cnt3] [datetime] NULL,
[Lottable14_Cnt3] [datetime] NULL,
[Lottable15_Cnt3] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCDetail_B4Post] ADD CONSTRAINT [PKCCDETAIL_B4Post] PRIMARY KEY NONCLUSTERED ([CCDetailKey]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[CCDetail_B4Post] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[CCDetail_B4Post] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[CCDetail_B4Post] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[CCDetail_B4Post] TO [NSQL]
GO
