CREATE TABLE [dbo].[CODELKUP_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[LISTNAME] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Code] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CODELKUP_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_CODELKUP_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CODELKUP_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Storerkey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Codelkup_DELLOG_Storerkey] DEFAULT (' '),
[code2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Codelkup_DELLOG_code2] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CODELKUP_DELLOG] ADD CONSTRAINT [PK__CODELKUP_DELLOG__5AAF56EE] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[CODELKUP_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[CODELKUP_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[CODELKUP_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[CODELKUP_DELLOG] TO [NSQL]
GO
