CREATE TABLE [dbo].[CONTAINER_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[ContainerKey] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CONTAINER_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_CONTAINER_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CONTAINER_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTAINER_DELLOG] ADD CONSTRAINT [PK__CONTAINER_DELLOG__7F379B7E] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[CONTAINER_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[CONTAINER_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[CONTAINER_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[CONTAINER_DELLOG] TO [NSQL]
GO
