IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RFPutaway' AND COLUMN_NAME = 'EditDate') 
   ALTER TABLE RFPutaway ADD EditDate DATETIME NULL
GO
IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RFPutaway' AND COLUMN_NAME = 'EditWho') 
   ALTER TABLE RFPutaway ADD EditWho NVARCHAR(128) NULL
GO
IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RFPutaway_DELLOG' AND COLUMN_NAME = 'EditDate') 
   ALTER TABLE RFPutaway_DELLOG ADD EditDate DATETIME NULL
GO
IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RFPutaway_DELLOG' AND COLUMN_NAME = 'EditWho') 
   ALTER TABLE RFPutaway_DELLOG ADD EditWho NVARCHAR(128) NULL
GO


