IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[DEL_RECEIPTDETAIL]') and OBJECTPROPERTY(id, N'IsTable') = 1)
DROP TABLE [dbo].[DEL_RECEIPTDETAIL]
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEL_RECEIPTDETAIL](
	[ReceiptKey] [nvarchar](10) NOT NULL,
	[ReceiptLineNumber] [nvarchar](5) NOT NULL,
	[ExternReceiptKey] [nvarchar](50) NULL,
	[ExternLineNo] [nvarchar](20) NOT NULL,
	[StorerKey] [nvarchar](15) NOT NULL,
	[POKey] [nvarchar](18) NOT NULL,
	[Sku] [nvarchar](20) NOT NULL,
	[AltSku] [nvarchar](20) NOT NULL,
	[Id] [nvarchar](18) NOT NULL,
	[Status] [nvarchar](10) NOT NULL,
	[DateReceived] [datetime] NOT NULL,
	[QtyExpected] [int] NOT NULL,
	[QtyAdjusted] [int] NOT NULL,
	[QtyReceived] [int] NOT NULL,
	[UOM] [nvarchar](10) NOT NULL,
	[PackKey] [nvarchar](10) NOT NULL,
	[VesselKey] [nvarchar](18) NULL,
	[VoyageKey] [nvarchar](18) NULL,
	[XdockKey] [nvarchar](18) NULL,
	[ContainerKey] [nvarchar](18) NULL,
	[ToLoc] [nvarchar](10) NOT NULL,
	[ToLot] [nvarchar](10) NULL,
	[ToId] [nvarchar](18) NULL,
	[ConditionCode] [nvarchar](10) NOT NULL,
	[Lottable01] [nvarchar](18) NOT NULL,
	[Lottable02] [nvarchar](18) NOT NULL,
	[Lottable03] [nvarchar](18) NOT NULL,
	[Lottable04] [datetime] NULL,
	[Lottable05] [datetime] NULL,
	[CaseCnt] [int] NOT NULL,
	[InnerPack] [int] NOT NULL,
	[Pallet] [int] NOT NULL,
	[Cube] [float] NOT NULL,
	[GrossWgt] [float] NOT NULL,
	[NetWgt] [float] NOT NULL,
	[OtherUnit1] [float] NOT NULL,
	[OtherUnit2] [float] NOT NULL,
	[UnitPrice] [float] NULL,
	[ExtendedPrice] [float] NULL,
	[EffectiveDate] [datetime] NOT NULL,
	[AddDate] [datetime] NOT NULL,
	[AddWho] [nvarchar](128) NOT NULL,
	[EditDate] [datetime] NOT NULL,
	[EditWho] [nvarchar](128) NOT NULL,
	[TrafficCop] [nvarchar](1) NULL,
	[ArchiveCop] [nvarchar](1) NULL,
	[TariffKey] [nvarchar](10) NULL,
	[FreeGoodQtyExpected] [int] NULL,
	[FreeGoodQtyReceived] [int] NULL,
	[SubReasonCode] [nvarchar](10) NULL,
	[FinalizeFlag] [nvarchar](1) NULL,
	[DuplicateFrom] [nvarchar](5) NULL,
	[BeforeReceivedQty] [int] NULL,
	[PutawayLoc] [nvarchar](10) NULL,
	[ExportStatus] [nvarchar](1) NULL,
	[SplitPalletFlag] [nvarchar](1) NULL,
	[POLineNumber] [nvarchar](5) NULL,
	[LoadKey] [nvarchar](10) NULL,
	[ExternPoKey] [nvarchar](20) NULL,
	[UserDefine01] [nvarchar](30) NULL,
	[UserDefine02] [nvarchar](30) NULL,
	[UserDefine03] [nvarchar](30) NULL,
	[UserDefine04] [nvarchar](30) NULL,
	[UserDefine05] [nvarchar](30) NULL,
	[UserDefine06] [datetime] NULL,
	[UserDefine07] [datetime] NULL,
	[UserDefine08] [nvarchar](30) NULL,
	[UserDefine09] [nvarchar](30) NULL,
	[UserDefine10] [nvarchar](30) NULL,
	[Lottable06] [nvarchar](30) NOT NULL,
	[Lottable07] [nvarchar](30) NOT NULL,
	[Lottable08] [nvarchar](30) NOT NULL,
	[Lottable09] [nvarchar](30) NOT NULL,
	[Lottable10] [nvarchar](30) NOT NULL,
	[Lottable11] [nvarchar](30) NOT NULL,
	[Lottable12] [nvarchar](30) NOT NULL,
	[Lottable13] [datetime] NULL,
	[Lottable14] [datetime] NULL,
	[Lottable15] [datetime] NULL,
	[Channel] [nvarchar](20) NULL,
	[Channel_ID] [bigint] NULL,
	[RowVer] [timestamp] NULL,
 CONSTRAINT [PKDEL_RECEIPTDETAIL] PRIMARY KEY CLUSTERED 
(
	[ReceiptKey] ASC,
	[ReceiptLineNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_XrecKey]  DEFAULT (' ') FOR [ExternReceiptKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_XLineNo]  DEFAULT (' ') FOR [ExternLineNo]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_StorerKey]  DEFAULT (' ') FOR [StorerKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_POKey]  DEFAULT (' ') FOR [POKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Sku]  DEFAULT (' ') FOR [Sku]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_AltSku]  DEFAULT (' ') FOR [AltSku]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Id]  DEFAULT (' ') FOR [Id]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Status]  DEFAULT ('0') FOR [Status]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Date]  DEFAULT (getdate()) FOR [DateReceived]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_QtyExpected]  DEFAULT ((0)) FOR [QtyExpected]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_QtyAdjusted]  DEFAULT ((0)) FOR [QtyAdjusted]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_QtyReceived]  DEFAULT ((0)) FOR [QtyReceived]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UOM]  DEFAULT (' ') FOR [UOM]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_PackKey]  DEFAULT ('STD') FOR [PackKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_VesselKey]  DEFAULT (' ') FOR [VesselKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_VoyageKey]  DEFAULT (' ') FOR [VoyageKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_XdockKey]  DEFAULT (' ') FOR [XdockKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_ContainerKey]  DEFAULT (' ') FOR [ContainerKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_ToId]  DEFAULT (' ') FOR [ToId]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_ConditionCode]  DEFAULT ('OK') FOR [ConditionCode]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_LOTTABLE01]  DEFAULT (' ') FOR [Lottable01]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_LOTTABLE02]  DEFAULT (' ') FOR [Lottable02]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_LOTTABLE03]  DEFAULT (' ') FOR [Lottable03]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_CaseCnt]  DEFAULT ((0)) FOR [CaseCnt]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Innerpack]  DEFAULT ((0)) FOR [InnerPack]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Pallet]  DEFAULT ((0)) FOR [Pallet]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Cube]  DEFAULT ((0)) FOR [Cube]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_GrossWgt]  DEFAULT ((0)) FOR [GrossWgt]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_NetWgt]  DEFAULT ((0)) FOR [NetWgt]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_OtherUnit1]  DEFAULT ((0)) FOR [OtherUnit1]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_OtherUnit2]  DEFAULT ((0)) FOR [OtherUnit2]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UnitPrice]  DEFAULT ((0)) FOR [UnitPrice]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_xtendedprice]  DEFAULT ((0)) FOR [ExtendedPrice]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_EffectiveDate]  DEFAULT (getdate()) FOR [EffectiveDate]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_AddDate]  DEFAULT (getdate()) FOR [AddDate]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_AddWho]  DEFAULT (suser_sname()) FOR [AddWho]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_EditDate]  DEFAULT (getdate()) FOR [EditDate]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_EditWho]  DEFAULT (suser_sname()) FOR [EditWho]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_FreeGoodQtyExpected]  DEFAULT ((0)) FOR [FreeGoodQtyExpected]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_FreeGoodQtyReceived]  DEFAULT ((0)) FOR [FreeGoodQtyReceived]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_SubReasonCode]  DEFAULT (' ') FOR [SubReasonCode]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_FinalizeFlag]  DEFAULT ('N') FOR [FinalizeFlag]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_BeforeReceivedQty]  DEFAULT ((0)) FOR [BeforeReceivedQty]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_PutawayLoc]  DEFAULT (' ') FOR [PutawayLoc]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_ExportStatus]  DEFAULT ('0') FOR [ExportStatus]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_SplitPalletFlag]  DEFAULT ('N') FOR [SplitPalletFlag]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_POLN]  DEFAULT (' ') FOR [POLineNumber]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_ExternPoKey]  DEFAULT ('') FOR [ExternPoKey]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UserDefine01]  DEFAULT (' ') FOR [UserDefine01]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UserDefine02]  DEFAULT (' ') FOR [UserDefine02]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UserDefine03]  DEFAULT (' ') FOR [UserDefine03]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UserDefine04]  DEFAULT (' ') FOR [UserDefine04]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UserDefine05]  DEFAULT (' ') FOR [UserDefine05]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UserDefine08]  DEFAULT (' ') FOR [UserDefine08]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UserDefine09]  DEFAULT (' ') FOR [UserDefine09]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_UserDefine10]  DEFAULT (' ') FOR [UserDefine10]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Lottable06]  DEFAULT (' ') FOR [Lottable06]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Lottable07]  DEFAULT (' ') FOR [Lottable07]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Lottable08]  DEFAULT (' ') FOR [Lottable08]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Lottable09]  DEFAULT (' ') FOR [Lottable09]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Lottable10]  DEFAULT (' ') FOR [Lottable10]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Lottable11]  DEFAULT (' ') FOR [Lottable11]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Lottable12]  DEFAULT (' ') FOR [Lottable12]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Channel]  DEFAULT ('') FOR [Channel]
GO

ALTER TABLE [dbo].[DEL_RECEIPTDETAIL] ADD  CONSTRAINT [DF_DEL_RECEIPTDETAIL_Channel_ID]  DEFAULT ((0)) FOR [Channel_ID]
GO


