CREATE TABLE [dbo].[EC_RECEIPTDETAIL]
(
[ReceiptKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ReceiptLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExternReceiptKey] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_ExternReceiptKey] DEFAULT (' '),
[ExternLineNo] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_ExternLineNo] DEFAULT (' '),
[StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_StorerKey] DEFAULT (' '),
[POKey] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_POKey] DEFAULT (' '),
[Sku] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Sku] DEFAULT (' '),
[AltSku] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_AltSku] DEFAULT (' '),
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Id] DEFAULT (' '),
[Status] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Status] DEFAULT ('0'),
[DateReceived] [datetime] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_DateReceived] DEFAULT (getdate()),
[QtyExpected] [int] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_QtyExpected] DEFAULT ((0)),
[QtyAdjusted] [int] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_QtyAdjusted] DEFAULT ((0)),
[QtyReceived] [int] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_QtyReceived] DEFAULT ((0)),
[UOM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UOM] DEFAULT (' '),
[PackKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_PackKey] DEFAULT ('STD'),
[VesselKey] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_VesselKey] DEFAULT (' '),
[VoyageKey] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_VoyageKey] DEFAULT (' '),
[XdockKey] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_XdockKey] DEFAULT (' '),
[ContainerKey] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_ContainerKey] DEFAULT (' '),
[ToLoc] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ToLot] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_ToId] DEFAULT (' '),
[ConditionCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_ConditionCode] DEFAULT ('OK'),
[Lottable01] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_LOTTABLE01] DEFAULT (' '),
[Lottable02] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_LOTTABLE02] DEFAULT (' '),
[Lottable03] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_LOTTABLE03] DEFAULT (' '),
[Lottable04] [datetime] NULL,
[Lottable05] [datetime] NULL,
[CaseCnt] [int] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_CaseCnt] DEFAULT ((0)),
[InnerPack] [int] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Innerpack] DEFAULT ((0)),
[Pallet] [int] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Pallet] DEFAULT ((0)),
[Cube] [float] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Cube] DEFAULT ((0)),
[GrossWgt] [float] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_GrossWgt] DEFAULT ((0)),
[NetWgt] [float] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_NetWgt] DEFAULT ((0)),
[OtherUnit1] [float] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_OtherUnit1] DEFAULT ((0)),
[OtherUnit2] [float] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_OtherUnit2] DEFAULT ((0)),
[UnitPrice] [float] NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UnitPrice] DEFAULT ((0)),
[ExtendedPrice] [float] NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_ExtendedPrice] DEFAULT ((0)),
[EffectiveDate] [datetime] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_EffectiveDate] DEFAULT (getdate()),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_AddWho] DEFAULT (suser_sname()),
[EditDate] [datetime] NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_EditDate] DEFAULT (getdate()),
[EditWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_EditWho] DEFAULT (suser_sname()),
[TrafficCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TariffKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FreeGoodQtyExpected] [int] NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_FreeGoodQtyExpected] DEFAULT ((0)),
[FreeGoodQtyReceived] [int] NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_FreeGoodQtyReceived] DEFAULT ((0)),
[SubReasonCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_SubReasonCode] DEFAULT (' '),
[FinalizeFlag] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_FinalizeFlag] DEFAULT ('N'),
[DuplicateFrom] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BeforeReceivedQty] [int] NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_BeforeReceivedQty] DEFAULT ((0)),
[PutawayLoc] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_PutawayLoc] DEFAULT (' '),
[ExportStatus] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_ExportStatus] DEFAULT ('0'),
[SplitPalletFlag] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_SplitPalletFlag] DEFAULT ('N'),
[POLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_POLineNumber] DEFAULT (' '),
[LoadKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternPoKey] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefine01] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UserDefine01] DEFAULT (' '),
[UserDefine02] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UserDefine02] DEFAULT (' '),
[UserDefine03] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UserDefine03] DEFAULT (' '),
[UserDefine04] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UserDefine04] DEFAULT (' '),
[UserDefine05] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UserDefine05] DEFAULT (' '),
[UserDefine06] [datetime] NULL,
[UserDefine07] [datetime] NULL,
[UserDefine08] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UserDefine08] DEFAULT (' '),
[UserDefine09] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UserDefine09] DEFAULT (' '),
[UserDefine10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_UserDefine10] DEFAULT (' '),
[Lottable06] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Lottable06] DEFAULT (' '),
[Lottable07] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Lottable07] DEFAULT (' '),
[Lottable08] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Lottable08] DEFAULT (' '),
[Lottable09] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Lottable09] DEFAULT (' '),
[Lottable10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Lottable10] DEFAULT (' '),
[Lottable11] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Lottable11] DEFAULT (' '),
[Lottable12] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EC_RECEIPTDETAIL_Lottable12] DEFAULT (' '),
[Lottable13] [datetime] NULL,
[Lottable14] [datetime] NULL,
[Lottable15] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EC_RECEIPTDETAIL] ADD CONSTRAINT [PKECRECEIPTDETAIL] PRIMARY KEY CLUSTERED ([ReceiptKey], [ReceiptLineNumber]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_EC_RECEIPTDETAIL_ExternReceiptKey] ON [dbo].[EC_RECEIPTDETAIL] ([ExternReceiptKey]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_EC_RECEIPTDETAIL_PO] ON [dbo].[EC_RECEIPTDETAIL] ([POKey], [POLineNumber]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EC_RECEIPTDETAIL3] ON [dbo].[EC_RECEIPTDETAIL] ([ReceiptKey], [ReceiptLineNumber], [QtyReceived], [BeforeReceivedQty]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_EC_RECEIPTDETAIL_STSKLot02XRecKey] ON [dbo].[EC_RECEIPTDETAIL] ([StorerKey], [Sku], [Lottable02], [ExternPoKey]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EC_RECEIPTDETAIL] ADD CONSTRAINT [FK_EC_RECEIPTDETAIL_SKU_01] FOREIGN KEY ([StorerKey], [Sku]) REFERENCES [dbo].[SKU] ([StorerKey], [Sku])
GO
GRANT DELETE ON  [dbo].[EC_RECEIPTDETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[EC_RECEIPTDETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[EC_RECEIPTDETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[EC_RECEIPTDETAIL] TO [NSQL]
GO
