CREATE TABLE [dbo].[FACILITY_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[Facility] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FACILITY_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_FACILITY_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FACILITY_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACILITY_DELLOG] ADD CONSTRAINT [PK__FACILITY_DELLOG__29F710FA] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[FACILITY_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[FACILITY_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[FACILITY_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[FACILITY_DELLOG] TO [NSQL]
GO
