CREATE TABLE [dbo].[GEEKPBOT_INTEG_CONFIG]
(
[InterfaceName] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_InterfaceName] DEFAULT (''),
[StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_StorerKey] DEFAULT (''),
[ReservedSQLQuery1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_ReservedSQLQuery1] DEFAULT (''),
[ReservedSQLQuery2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_ReservedSQLQuery2] DEFAULT (''),
[ReservedSQLQuery3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_ReservedSQLQuery3] DEFAULT (''),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_AddWho] DEFAULT (suser_sname()),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_AddDate] DEFAULT (getdate()),
[EditDate] [datetime] NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_EditDate] DEFAULT (getdate()),
[EditWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GEEKPBOT_INTEG_CONFIG_EditWho] DEFAULT (suser_sname())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEEKPBOT_INTEG_CONFIG] ADD CONSTRAINT [PK_GEEKPBOT_INTEG_CONFIG] PRIMARY KEY CLUSTERED ([InterfaceName], [StorerKey]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[GEEKPBOT_INTEG_CONFIG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[GEEKPBOT_INTEG_CONFIG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[GEEKPBOT_INTEG_CONFIG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[GEEKPBOT_INTEG_CONFIG] TO [NSQL]
GO
