CREATE TABLE [dbo].[IDS_LP_DRIVER_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[Loadkey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DriverCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_IDS_LP_DRIVER_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_IDS_LP_DRIVER_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_IDS_LP_DRIVER_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBOLKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IDS_LP_DRIVER_DELLOG] ADD CONSTRAINT [PK__IDS_LP_D__78C977972D68691A] PRIMARY KEY CLUSTERED ([Rowref]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[IDS_LP_DRIVER_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[IDS_LP_DRIVER_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[IDS_LP_DRIVER_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[IDS_LP_DRIVER_DELLOG] TO [NSQL]
GO
