CREATE TABLE [dbo].[ITRNKey]
(
[ITRNKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITRNKey] ADD CONSTRAINT [PK_ITRNKEY] PRIMARY KEY CLUSTERED ([ITRNKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[ITRNKey] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[ITRNKey] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[ITRNKey] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[ITRNKey] TO [NSQL]
GO
