CREATE TABLE [dbo].[KITDETAIL_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[KITKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KITLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Type] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_KITDETAIL_DELLOG_Type] DEFAULT ('F'),
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_KITDETAIL_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_KITDETAIL_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_KITDETAIL_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KITDETAIL_DELLOG] ADD CONSTRAINT [PK__KITDETAIL_DELLOG__000BC426] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[KITDETAIL_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[KITDETAIL_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[KITDETAIL_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[KITDETAIL_DELLOG] TO [NSQL]
GO
