CREATE TABLE [dbo].[LOC_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[Loc] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_LOC_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_LOC_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_LOC_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOC_DELLOG] ADD CONSTRAINT [PK__LOC_DELLOG__7EAD8B99] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[LOC_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[LOC_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[LOC_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[LOC_DELLOG] TO [NSQL]
GO
