CREATE TABLE [dbo].[LOTKey]
(
[LOTKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOTKey] ADD CONSTRAINT [PK_LOTKEY] PRIMARY KEY CLUSTERED ([LOTKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[LOTKey] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[LOTKey] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[LOTKey] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[LOTKey] TO [NSQL]
GO
