CREATE TABLE [dbo].[MailQSMSDet]
(
[QDetid] [int] NOT NULL IDENTITY(1, 1),
[Qid] [int] NOT NULL,
[C01Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C01Name] DEFAULT (''),
[C01] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C01] DEFAULT (''),
[C02Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C02Name] DEFAULT (''),
[C02] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C02] DEFAULT (''),
[C03Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C03Name] DEFAULT (''),
[C03] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C03] DEFAULT (''),
[C04Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C04Name] DEFAULT (''),
[C04] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C04] DEFAULT (''),
[C05Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C05Name] DEFAULT (''),
[C05] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C05] DEFAULT (''),
[C06Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C06Name] DEFAULT (''),
[C06] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C06] DEFAULT (''),
[C07Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C07Name] DEFAULT (''),
[C07] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C07] DEFAULT (''),
[C08Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C08Name] DEFAULT (''),
[C08] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C08] DEFAULT (''),
[C09Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C09Name] DEFAULT (''),
[C09] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C09] DEFAULT (''),
[C10Name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C10Name] DEFAULT (''),
[C10] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MailQSMSDet_C10] DEFAULT (''),
[OrderKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MailQSMSDet] ADD CONSTRAINT [QSMSDetid_MustBeUnique] PRIMARY KEY CLUSTERED ([QDetid]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MailQSMSDet] ADD CONSTRAINT [FK_MailQSMSDet_MailQSMS] FOREIGN KEY ([Qid]) REFERENCES [dbo].[MailQSMS] ([Qid])
GO
GRANT DELETE ON  [dbo].[MailQSMSDet] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[MailQSMSDet] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[MailQSMSDet] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[MailQSMSDet] TO [NSQL]
GO
