CREATE TABLE [dbo].[MailQ]
(
[Qid] [int] NOT NULL IDENTITY(1, 1),
[mailitem_id] [int] NOT NULL,
[StorerKey] [nvarchar] (15) NOT NULL,
[UniqueKey] [nvarchar] (100) NOT NULL,
[UniqueKeyName] [nvarchar] (1024) NOT NULL,
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_MailQ_AddDate] DEFAULT (getdate()),
[AddWho] [sys].[sysname] NOT NULL CONSTRAINT [DF_MailQ_AddWho] DEFAULT (suser_sname()),
[AddObj] [nvarchar] (128) NOT NULL CONSTRAINT [DF_MailQ_AddObj] DEFAULT (isnull(object_name(@@procid),'')),
[SendTo] [varchar] (4000) NULL,
[Cc] [varchar] (4000) NULL,
[Bcc] [varchar] (4000) NULL,
[Subject] [nvarchar] (255) NULL,
[Header] [nvarchar] (2000) NOT NULL,
[Footer] [nvarchar] (2000) NOT NULL,
[THColor] [char] (6) NOT NULL,
[R01Name] [nvarchar] (128) NOT NULL,
[R01] [nvarchar] (1000) NOT NULL,
[R02Name] [nvarchar] (128) NOT NULL,
[R02] [nvarchar] (1000) NOT NULL,
[R03Name] [nvarchar] (128) NOT NULL,
[R03] [nvarchar] (1000) NOT NULL,
[R04Name] [nvarchar] (128) NOT NULL,
[R04] [nvarchar] (1000) NOT NULL,
[R05Name] [nvarchar] (128) NOT NULL,
[R05] [nvarchar] (1000) NOT NULL,
[R06Name] [nvarchar] (128) NOT NULL,
[R06] [nvarchar] (1000) NOT NULL,
[R07Name] [nvarchar] (128) NOT NULL,
[R07] [nvarchar] (1000) NOT NULL,
[R08Name] [nvarchar] (128) NOT NULL,
[R08] [nvarchar] (1000) NOT NULL,
[R09Name] [nvarchar] (128) NOT NULL,
[R09] [nvarchar] (1000) NOT NULL,
[R10Name] [nvarchar] (128) NOT NULL,
[R10] [nvarchar] (1000) NOT NULL,
[R11Name] [nvarchar] (128) NOT NULL,
[R11] [nvarchar] (1000) NOT NULL,
[R12Name] [nvarchar] (128) NOT NULL,
[R12] [nvarchar] (1000) NOT NULL,
[R13Name] [nvarchar] (128) NOT NULL,
[R13] [nvarchar] (1000) NOT NULL,
[R14Name] [nvarchar] (128) NOT NULL,
[R14] [nvarchar] (1000) NOT NULL,
[R15Name] [nvarchar] (128) NOT NULL,
[R15] [nvarchar] (1000) NOT NULL,
[C01Align] [char] (1) NOT NULL,
[C01Name] [nvarchar] (128) NOT NULL,
[C02Align] [char] (1) NOT NULL,
[C02Name] [nvarchar] (128) NOT NULL,
[C03Align] [char] (1) NOT NULL,
[C03Name] [nvarchar] (128) NOT NULL,
[C04Align] [char] (1) NOT NULL,
[C04Name] [nvarchar] (128) NOT NULL,
[C05Align] [char] (1) NOT NULL,
[C05Name] [nvarchar] (128) NOT NULL,
[C06Align] [char] (1) NOT NULL,
[C06Name] [nvarchar] (128) NOT NULL,
[C07Align] [char] (1) NOT NULL,
[C07Name] [nvarchar] (128) NOT NULL,
[C08Align] [char] (1) NOT NULL,
[C08Name] [nvarchar] (128) NOT NULL,
[C09Align] [char] (1) NOT NULL,
[C09Name] [nvarchar] (128) NOT NULL,
[C10Align] [char] (1) NOT NULL,
[C10Name] [nvarchar] (128) NOT NULL,
[C11Align] [char] (1) NOT NULL,
[C11Name] [nvarchar] (128) NOT NULL,
[C12Align] [char] (1) NOT NULL,
[C12Name] [nvarchar] (128) NOT NULL,
[C13Align] [char] (1) NOT NULL,
[C13Name] [nvarchar] (128) NOT NULL,
[C14Align] [char] (1) NOT NULL,
[C14Name] [nvarchar] (128) NOT NULL,
[C15Align] [char] (1) NOT NULL,
[C15Name] [nvarchar] (128) NOT NULL,
[C01Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C01Agg] DEFAULT (''),
[C02Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C02Agg] DEFAULT (''),
[C03Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C03Agg] DEFAULT (''),
[C04Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C04Agg] DEFAULT (''),
[C05Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C05Agg] DEFAULT (''),
[C06Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C06Agg] DEFAULT (''),
[C07Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C07Agg] DEFAULT (''),
[C08Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C08Agg] DEFAULT (''),
[C09Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C09Agg] DEFAULT (''),
[C10Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C10Agg] DEFAULT (''),
[C11Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C11Agg] DEFAULT (''),
[C12Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C12Agg] DEFAULT (''),
[C13Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C13Agg] DEFAULT (''),
[C14Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C14Agg] DEFAULT (''),
[C15Agg] [nvarchar] (25) NOT NULL CONSTRAINT [DF_MailQ_C15Agg] DEFAULT (''),
[ArchiveCop] [nvarchar] (1) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MailQ] ADD CONSTRAINT [DBMail_mail_id_MustBeUnique] PRIMARY KEY CLUSTERED ([Qid]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[MailQ] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[MailQ] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[MailQ] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[MailQ] TO [NSQL]
GO
