CREATE TABLE [dbo].[MBOLDETAIL_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[MbolKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MbolLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MBOLDETAIL_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_MBOLDETAIL_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MBOLDETAIL_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orderkey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MBOLDETAIL_DELLOG] ADD CONSTRAINT [PK__MBOLDETAIL_DELLO__702A6218] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[MBOLDETAIL_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[MBOLDETAIL_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[MBOLDETAIL_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[MBOLDETAIL_DELLOG] TO [NSQL]
GO
