CREATE TABLE [dbo].[MESSAGE_TEXT]
(
[MsgId] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MESSAGE_TEXT_MsgId] DEFAULT (' '),
[MsgLangId] [int] NOT NULL CONSTRAINT [DF_MESSAGE_TEXT_MsgLangId] DEFAULT ((0)),
[MsgTitle] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MESSAGE_TEXT_MsgTitle] DEFAULT (' '),
[MsgText] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MESSAGE_TEXT_MsgText] DEFAULT (' ')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MESSAGE_TEXT] ADD CONSTRAINT [PK_msgid_langid] PRIMARY KEY CLUSTERED ([MsgId], [MsgLangId]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MESSAGE_TEXT] WITH NOCHECK ADD CONSTRAINT [FK_msgid] FOREIGN KEY ([MsgId]) REFERENCES [dbo].[MESSAGE_ID] ([MsgId])
GO
GRANT DELETE ON  [dbo].[MESSAGE_TEXT] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[MESSAGE_TEXT] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[MESSAGE_TEXT] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[MESSAGE_TEXT] TO [NSQL]
GO
EXEC sp_addextendedproperty N'MS_Description', 'Unique code identifying Message.', 'SCHEMA', N'dbo', 'TABLE', N'MESSAGE_TEXT', 'COLUMN', N'MsgId'
GO
