CREATE TABLE [dbo].[NCOUNTER]
(
[keyname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[keycount] [int] NOT NULL,
[AlphaCount] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_NCOUNTER_AlphaCount] DEFAULT (''),
[EditDate] [datetime] NULL CONSTRAINT [DF_NCOUNTER_EditDate] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NCOUNTER] ADD CONSTRAINT [PKNCOUNTER] PRIMARY KEY CLUSTERED ([keyname]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[NCOUNTER] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[NCOUNTER] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[NCOUNTER] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[NCOUNTER] TO [NSQL]
GO
