CREATE TABLE [dbo].[ORDERS_TRACKNO_WIP]
(
[RowID] [int] NOT NULL IDENTITY(1, 1),
[TrackBatchNo] [int] NOT NULL,
[KeyName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ORDERS_TRACKNO_WIP_KeyName] DEFAULT (''),
[CarrierName] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ORDERS_TRACKNO_WIP_CarrierName] DEFAULT (''),
[OrderKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ORDERS_TRACKNO_WIP_OrderKey] DEFAULT (''),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_ORDERS_TRACKNO_WIP_AddDate] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERS_TRACKNO_WIP] ADD CONSTRAINT [PK_Order_TrackNo_WIP] PRIMARY KEY CLUSTERED ([RowID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Orders_TrackNo_WIP_02] ON [dbo].[ORDERS_TRACKNO_WIP] ([OrderKey]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Order_TrackNo_WIP] ON [dbo].[ORDERS_TRACKNO_WIP] ([TrackBatchNo], [RowID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[ORDERS_TRACKNO_WIP] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[ORDERS_TRACKNO_WIP] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[ORDERS_TRACKNO_WIP] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[ORDERS_TRACKNO_WIP] TO [NSQL]
GO
