CREATE TABLE [dbo].[ORDERDETAIL_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[OrderKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OrderLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ORDERDETAIL_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_ORDERDETAIL_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ORDERDETAIL_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERDETAIL_DELLOG] ADD CONSTRAINT [PK__ORDERDETAIL_DELL__1A209BE4] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[ORDERDETAIL_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[ORDERDETAIL_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[ORDERDETAIL_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[ORDERDETAIL_DELLOG] TO [NSQL]
GO
