CREATE TABLE [dbo].[PALLETIMAGE]
(
[Receiptkey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_Receiptkey] DEFAULT (''),
[PermitNo] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PALLETIMAGE_PermitNo] DEFAULT (''),
[LotNo] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PALLETIMAGE_LotNo] DEFAULT (''),
[ID] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_ID] DEFAULT (''),
[Storerkey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_Storerkey] DEFAULT (''),
[Sku] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_Sku] DEFAULT (''),
[Descr] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_Descr] DEFAULT (''),
[UOM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_UOM] DEFAULT (''),
[QtyReceived] [int] NULL CONSTRAINT [DF_PALLETIMAGE_QtyReceived] DEFAULT ((0)),
[ReceiptDate] [datetime] NOT NULL CONSTRAINT [DF_PALLETIMAGE_ReceiptDate] DEFAULT (''),
[ImageUrl01] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_ImageUrl01] DEFAULT (''),
[ImageUrl02] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_ImageUrl02] DEFAULT (''),
[ImageUrl03] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_ImageUrl03] DEFAULT (''),
[ImageUrl04] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_ImageUrl04] DEFAULT (''),
[ImageUrl05] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETIMAGE_ImageUrl05] DEFAULT (''),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PALLETIMAGE_AddWho] DEFAULT (suser_sname()),
[AddDate] [datetime] NULL CONSTRAINT [DF_PALLETIMAGE_AddDate] DEFAULT (getdate()),
[EditWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PALLETIMAGE_EditWho] DEFAULT (suser_sname()),
[EditDate] [datetime] NULL CONSTRAINT [DF_PALLETIMAGE_EditDate] DEFAULT (getdate()),
[TrafficCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PALLETIMAGE_Adddate] ON [dbo].[PALLETIMAGE] ([AddDate], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PALLETIMAGE_LotNo] ON [dbo].[PALLETIMAGE] ([LotNo], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PALLETIMAGE_PermitNo] ON [dbo].[PALLETIMAGE] ([PermitNo], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PALLETIMAGE_ReceiptDate] ON [dbo].[PALLETIMAGE] ([ReceiptDate], [ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PALLETIMAGE_Receiptkey] ON [dbo].[PALLETIMAGE] ([Receiptkey], [LotNo], [ID]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PALLETIMAGE] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PALLETIMAGE] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PALLETIMAGE] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PALLETIMAGE] TO [NSQL]
GO
