CREATE TABLE [dbo].[PALLETDETAIL_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[PalletKey] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PalletLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETDETAIL_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_PALLETDETAIL_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PALLETDETAIL_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PALLETDETAIL_DELLOG] ADD CONSTRAINT [PK__PALLETDETAIL_DEL__6521F869] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PALLETDETAIL_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PALLETDETAIL_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PALLETDETAIL_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PALLETDETAIL_DELLOG] TO [NSQL]
GO
