CREATE TABLE [dbo].[PHY_POST_DETAIL]
(
[StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PHY_POST_DETAIL_StorerKey] DEFAULT (' '),
[Sku] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PHY_POST_DETAIL_Sku] DEFAULT (' '),
[Loc] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PHY_POST_DETAIL_Loc] DEFAULT (' '),
[Lot] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PHY_POST_DETAIL_Lot] DEFAULT (' '),
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PHY_POST_DETAIL_Id] DEFAULT (' '),
[QtyTeamA] [int] NOT NULL CONSTRAINT [DF_PHY_POST_DETAIL_QtyTeamA] DEFAULT ((0)),
[QtyLOTxLOCxID] [int] NOT NULL CONSTRAINT [DF_PHY_POST_DETAIL_QtyLOTxLOCxID] DEFAULT ((0))
) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PHY_POST_DETAIL] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PHY_POST_DETAIL] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PHY_POST_DETAIL] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PHY_POST_DETAIL] TO [NSQL]
GO
EXEC sp_addextendedproperty N'MS_Description', 'Unique key to the Storer record.', 'SCHEMA', N'dbo', 'TABLE', N'PHY_POST_DETAIL', 'COLUMN', N'StorerKey'
GO
