CREATE TABLE [dbo].[PICKHEADER_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[PickHeaderKey] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PICKHEADER_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_PICKHEADER_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PICKHEADER_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PICKHEADER_DELLOG] ADD CONSTRAINT [PK__PICKHEADER_DELLO__3E48EDC1] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PICKHEADER_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PICKHEADER_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PICKHEADER_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PICKHEADER_DELLOG] TO [NSQL]
GO
