CREATE TABLE [dbo].[PICKDETAIL_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[PickDetailKey] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PICKDETAIL_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_PICKDETAIL_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PICKDETAIL_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PICKDETAIL_DELLOG] ADD CONSTRAINT [PK__PICKDETAIL_DELLO__1BFDF75E] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Pickdetail_dellog_Adddate] ON [dbo].[PICKDETAIL_DELLOG] ([AddDate]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PICKDETAIL_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PICKDETAIL_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PICKDETAIL_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PICKDETAIL_DELLOG] TO [NSQL]
GO
