CREATE TABLE [dbo].[PICKDETAILKEY]
(
[PickDetailKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PICKDETAILKEY] ADD CONSTRAINT [PK_PICKDETAILKEY] PRIMARY KEY CLUSTERED ([PickDetailKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PICKDETAILKEY] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PICKDETAILKEY] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PICKDETAILKEY] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PICKDETAILKEY] TO [NSQL]
GO
