CREATE TABLE [dbo].[PICKDET_LOG_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[PDetLogNo] [int] NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PICKDET_LOG_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_PICKDET_LOG_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PICKDET_LOG_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PICKDET_LOG_DELLOG] ADD CONSTRAINT [PK__PICKDET_LOG_DELL__61D155C9] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PICKDET_LOG_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PICKDET_LOG_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PICKDET_LOG_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PICKDET_LOG_DELLOG] TO [NSQL]
GO
