CREATE TABLE [dbo].[PICKSLIPKey]
(
[PICKSLIPKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PICKSLIPKey] ADD CONSTRAINT [PK_PICKSLIPKey] PRIMARY KEY CLUSTERED ([PICKSLIPKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PICKSLIPKey] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PICKSLIPKey] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PICKSLIPKey] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PICKSLIPKey] TO [NSQL]
GO
