CREATE TABLE [dbo].[POD_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[Mbolkey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Mbollinenumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_POD_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_POD_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_POD_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POD_DELLOG] ADD CONSTRAINT [PK__POD_DELLOG__51EFF3BB] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[POD_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[POD_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[POD_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[POD_DELLOG] TO [NSQL]
GO
