CREATE TABLE [dbo].[PODETAIL_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[POKey] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PODETAIL_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_PODETAIL_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PODETAIL_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PODETAIL_DELLOG] ADD CONSTRAINT [PK__PODETAIL_DELLOG__6D9742D9] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PODETAIL_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PODETAIL_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PODETAIL_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PODETAIL_DELLOG] TO [NSQL]
GO
