CREATE TABLE [dbo].[PreallocatePICKDETAILKEY]
(
[PreallocatePickDetailKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PreallocatePICKDETAILKEY] ADD CONSTRAINT [PK_PREALLOCATEPICKDET] PRIMARY KEY CLUSTERED ([PreallocatePickDetailKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[PreallocatePICKDETAILKEY] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[PreallocatePICKDETAILKEY] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[PreallocatePICKDETAILKEY] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[PreallocatePICKDETAILKEY] TO [NSQL]
GO
