CREATE TABLE [dbo].[rdsORDERS_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[rdsOrderNo] [int] NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_rdsORDERS_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_rdsORDERS_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_rdsORDERS_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[rdsORDERS_DELLOG] ADD CONSTRAINT [PK__rdsORDERS_DELLOG__1A94D1D9] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[rdsORDERS_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[rdsORDERS_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[rdsORDERS_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[rdsORDERS_DELLOG] TO [NSQL]
GO
