CREATE TABLE [dbo].[REPLENISHKEY]
(
[REPLENISHKEY] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NOT NULL
) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[REPLENISHKEY] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[REPLENISHKEY] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[REPLENISHKEY] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[REPLENISHKEY] TO [NSQL]
GO
