CREATE TABLE [dbo].[SEQKey]
(
[Rowref] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEQKey] ADD CONSTRAINT [PK__SEQKey__78C97797C5A005D9] PRIMARY KEY CLUSTERED ([Rowref]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[SEQKey] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[SEQKey] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[SEQKey] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[SEQKey] TO [NSQL]
GO
