CREATE TABLE [dbo].[SKUConfig_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ConfigType] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_SKUConfig_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_SKUConfig_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_SKUConfig_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SKUConfig_DELLOG] ADD CONSTRAINT [PK__SKUConfi__78C977976B63AB17] PRIMARY KEY CLUSTERED ([Rowref]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[SKUConfig_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[SKUConfig_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[SKUConfig_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[SKUConfig_DELLOG] TO [NSQL]
GO
