CREATE TABLE [dbo].[SKUxLOC_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sku] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Loc] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_SKUxLOC_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_SKUxLOC_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_SKUxLOC_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SKUxLOC_DELLOG] ADD CONSTRAINT [PK__SKUxLOC_DELLOG__2B203F5D] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[SKUxLOC_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[SKUxLOC_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[SKUxLOC_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[SKUxLOC_DELLOG] TO [NSQL]
GO
