CREATE TABLE [dbo].[STORER_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_STORER_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_STORER_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_STORER_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STORER_DELLOG] ADD CONSTRAINT [PK__STORER_DELLOG__4026493B] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[STORER_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[STORER_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[STORER_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[STORER_DELLOG] TO [NSQL]
GO
