CREATE TABLE [dbo].[TASKDETAILKEY]
(
[TaskdetailKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASKDETAILKEY] ADD CONSTRAINT [PK_TASKDETAILKEY] PRIMARY KEY CLUSTERED ([TaskdetailKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TASKDETAILKEY] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[TASKDETAILKEY] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[TASKDETAILKEY] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[TASKDETAILKEY] TO [NSQL]
GO
