CREATE TABLE [dbo].[TBL_PURGECONFIG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[Item] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TBLName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Description] [nvarchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TBL_PURGECONFIG_Description] DEFAULT (''),
[Threshold] [int] NOT NULL CONSTRAINT [DF_TBL_PURGECONFIG_Threshold] DEFAULT ('30'),
[Date_Col] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TBL_PURGECONFIG_Date_Col] DEFAULT (''),
[Condition] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TBL_PURGECONFIG_Condition] DEFAULT (''),
[PurgeGroup] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TBL_PURGECONFIG_PurgeGroup] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBL_PURGECONFIG] ADD CONSTRAINT [PK__TBL_PURG__78C9779777D3E469] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TBL_PURGECONFIG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[TBL_PURGECONFIG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[TBL_PURGECONFIG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[TBL_PURGECONFIG] TO [NSQL]
GO
