CREATE TABLE [dbo].[TCPOUTLogKey]
(
[TCPOUTLogKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCPOUTLogKey] ADD CONSTRAINT [PK_TCPOUTLogKey] PRIMARY KEY CLUSTERED ([TCPOUTLogKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TCPOUTLogKey] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[TCPOUTLogKey] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[TCPOUTLogKey] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[TCPOUTLogKey] TO [NSQL]
GO
