CREATE TABLE [dbo].[TPB_EXTRACTION_HISTORY]
(
[TEH_Key] [bigint] NOT NULL IDENTITY(1, 1),
[TEH_Batch_Key] [int] NOT NULL,
[TEH_TPB_Key] [int] NOT NULL,
[TEH_Datatime] [datetime] NULL CONSTRAINT [DF_TPB_EXTRACTION_HISTORY_TEH_Datatime] DEFAULT (getdate()),
[TEH_Row_Count] [bigint] NULL,
[TEH_SQLMsg] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillDate] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPB_EXTRACTION_HISTORY] ADD CONSTRAINT [PK__TPB_EXTR__560C1816B30A501D] PRIMARY KEY CLUSTERED ([TEH_Key]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TPB_EXTRACTION_HISTORY] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[TPB_EXTRACTION_HISTORY] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[TPB_EXTRACTION_HISTORY] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[TPB_EXTRACTION_HISTORY] TO [NSQL]
GO
