CREATE TABLE [dbo].[TRANSMITLOGKEY3]
(
[TransmitlogKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSMITLOGKEY3] ADD CONSTRAINT [PK_TRANSMITLOGKEY3] PRIMARY KEY CLUSTERED ([TransmitlogKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TRANSMITLOGKEY3] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[TRANSMITLOGKEY3] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[TRANSMITLOGKEY3] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[TRANSMITLOGKEY3] TO [NSQL]
GO
