CREATE TABLE [dbo].[UCC_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[UCCNo] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_UCC_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_UCC_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_UCC_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Storerkey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCC_RowRef] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UCC_DELLOG] ADD CONSTRAINT [PK__UCC_DELLOG__0F03EEF3] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[UCC_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[UCC_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[UCC_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[UCC_DELLOG] TO [NSQL]
GO
