CREATE TABLE [dbo].[UPC_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[UPC] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_UPC_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_UPC_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_UPC_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UPC_DELLOG] ADD CONSTRAINT [PK__UPC_DELLOG__33807B34] PRIMARY KEY CLUSTERED ([Rowref]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[UPC_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[UPC_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[UPC_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[UPC_DELLOG] TO [NSQL]
GO
