CREATE TABLE [dbo].[WCS_SORTATION]
(
[RowRef] [int] NOT NULL IDENTITY(1, 1),
[LP_LaneNumber] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WCS_SORTATION_LP_LaneNumber] DEFAULT (''),
[SeqNo] [int] NOT NULL,
[LabelNo] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WCS_SORTATION_Status] DEFAULT ('0'),
[ErrMsg] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WCS_SORTATION_ErrMsg] DEFAULT (''),
[AddDate] [datetime] NULL CONSTRAINT [DF_WCS_SORTATION_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WCS_SORTATION_AddWho] DEFAULT (suser_sname()),
[EditDate] [datetime] NULL CONSTRAINT [DF_WCS_SORTATION_EditDate] DEFAULT (getdate()),
[EditWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WCS_SORTATION_EditWho] DEFAULT (suser_sname())
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WCS_SORTATION] ADD CONSTRAINT [PK_WCS_SORTATION] PRIMARY KEY CLUSTERED ([RowRef]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[WCS_SORTATION] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[WCS_SORTATION] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[WCS_SORTATION] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[WCS_SORTATION] TO [NSQL]
GO
