CREATE TABLE [dbo].[WCSKey]
(
[WCSKey] [bigint] NOT NULL IDENTITY(1, 1),
[AddDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WCSKey] ADD CONSTRAINT [PK_WCSKEY] PRIMARY KEY CLUSTERED ([WCSKey]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[WCSKey] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[WCSKey] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[WCSKey] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[WCSKey] TO [NSQL]
GO
