CREATE TABLE [dbo].[WMS_TPB_BASE]
(
[SEQ] [bigint] NOT NULL IDENTITY(1, 1),
[INSERT_DATE] [datetime] NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_INSERT_DATE] DEFAULT (getdate()),
[UPDATE_DATE] [datetime] NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_UPDATE_DATE] DEFAULT (getdate()),
[STATUS] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_STATUS] DEFAULT ('0'),
[BatchNo] [bigint] NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_BatchNo] DEFAULT ('0'),
[CONFIG_ID] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_CONFIG_ID] DEFAULT ('0'),
[TPB_UPLOADED_DATE] [datetime] NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_TPB_UPLOADED_DATE] DEFAULT (''),
[TPB_UPLOADED_STATUS] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_TPB_UPLOADED_STATUS] DEFAULT (''),
[TRANSACTION_TYPE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_TRANSACTION_TYPE] DEFAULT ('A'),
[CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CODE] DEFAULT (''),
[COUNTRY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_COUNTRY] DEFAULT (''),
[SITE_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SITE_ID] DEFAULT (''),
[TO_SITE_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_TO_SITE_ID] DEFAULT (''),
[CLIENT_SITE_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CLIENT_SITE_ID] DEFAULT (''),
[ADD_DATE] [datetime] NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_ADD_DATE] DEFAULT (getdate()),
[ADD_WHO] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_ADD_WHO] DEFAULT (suser_sname()),
[EDIT_DATE] [datetime] NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_EDIT_DATE] DEFAULT (getdate()),
[EDIT_WHO] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TPB_BASE_EDIT_WHO] DEFAULT (suser_sname()),
[DOC_SOURCE] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOC_SOURCE] DEFAULT (''),
[DOC_STATUS] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOC_STATUS] DEFAULT (''),
[DOC_PRE_STATUS] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOC_PrE_STATUS] DEFAULT (''),
[DOC_TYPE] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOC_TYPE] DEFAULT (''),
[DOC_SUB_TYPE] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOC_SUB_TYPE] DEFAULT (''),
[DOC_GROUPING_1] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOC_GROUPING_1] DEFAULT (''),
[DOC_GROUPING_2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOC_GROUPING_2] DEFAULT (''),
[DOC_REASON] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOC_REASON] DEFAULT (''),
[DOCUMENT_ID] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOCUMENT_ID] DEFAULT (''),
[DOCUMENT_LINE_NO] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DOCUMENT_LINE_NO] DEFAULT (''),
[CLIENT_REF] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CLIENT_REF] DEFAULT (''),
[CLIENT_REF_LINE_NO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CLIENT_REF_LINE_NO] DEFAULT (''),
[CLIENT_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CLIENT_ID] DEFAULT (''),
[TO_CLIENT_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_TO_CLIENT_ID] DEFAULT (''),
[SHIP_FROM_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SHIP_FROM_ID] DEFAULT (''),
[SHIP_FROM_COMPANY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SHIP_FROM_COMPANY] DEFAULT (''),
[SHIP_FROM_COUNTRY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SHIP_FROM_COUNTRY] DEFAULT (''),
[SHIP_TO_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SHIP_TO_ID] DEFAULT (''),
[SHIP_TO_COMPANY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SHIP_TO_COMPANY] DEFAULT (''),
[SHIP_TO_COUNTRY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SHIP_TO_COUNTRY] DEFAULT (''),
[LOAD_PLAN_NO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOAD_PLAN_NO] DEFAULT (''),
[MBOL_NO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_MBOL_NO] DEFAULT (''),
[OTHER_REFERENCE_1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_OTHER_REFERENCE_1] DEFAULT (''),
[OTHER_REFERENCE_2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_OTHER_REFERENCE_2] DEFAULT (''),
[PRIORITY] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_PRIORITY] DEFAULT (''),
[PO_NO] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_PO_NO] DEFAULT (''),
[CLIENT_PO_NO] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CLIENT_PO_NO] DEFAULT (''),
[REFERENCE_DATE] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_REFERENCE_DATE] DEFAULT (''),
[SKU_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_ID] DEFAULT (''),
[LOCATION_TYPE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOCATION_TYPE] DEFAULT (''),
[BILLABLE_NO_OF_LOC] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_NO_OF_LOC] DEFAULT ((0)),
[BILLABLE_QUANTITY] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_QUANTITY] DEFAULT ((0)),
[QTY_UOM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_QTY_UOM] DEFAULT (''),
[BILLABLE_CARTON] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_CARTON] DEFAULT ((0)),
[CARTON_UOM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CARTON_UOM] DEFAULT (''),
[BILLABLE_WEIGHT] [float] NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_WEIGHT] DEFAULT ((0)),
[WEIGHT_UOM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_WEIGHT_UOM] DEFAULT (''),
[BILLABLE_CBM] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_CBM] DEFAULT ((0)),
[CBM_UOM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CBM_UOM] DEFAULT (''),
[BILLABLE_PALLET] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_PALLET] DEFAULT ((0)),
[BILLABLE_DROP] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_DROP] DEFAULT ((0)),
[BILLABLE_CONTAINER] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_CONTAINER] DEFAULT ((0)),
[VESSEL_ID] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_VESSEL_ID] DEFAULT (''),
[VOYAGE_ID] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_VOYAGE_ID] DEFAULT (''),
[VEHICLE_NO] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_VEHICLE_NO] DEFAULT (''),
[VEHICLE_DATE] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_VEHICLE_DATE] DEFAULT (''),
[CONTAINER_TYPE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CONTAINER_TYPE] DEFAULT (''),
[CONTAINER_ID] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CONTAINER_ID] DEFAULT (''),
[PALLET_ID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_PALLET_ID] DEFAULT (''),
[LOTTABLE_01] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_01] DEFAULT (''),
[LOTTABLE_02] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_02] DEFAULT (''),
[LOTTABLE_03] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_03] DEFAULT (''),
[LOTTABLE_04] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_04] DEFAULT (''),
[LOTTABLE_05] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_05] DEFAULT (''),
[LOTTABLE_06] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_06] DEFAULT (''),
[LOTTABLE_07] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_07] DEFAULT (''),
[LOTTABLE_08] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_08] DEFAULT (''),
[LOTTABLE_09] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_09] DEFAULT (''),
[LOTTABLE_10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_10] DEFAULT (''),
[LOTTABLE_11] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_11] DEFAULT (''),
[LOTTABLE_12] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_12] DEFAULT (''),
[LOTTABLE_13] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_13] DEFAULT (''),
[LOTTABLE_14] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_14] DEFAULT (''),
[LOTTABLE_15] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOTTABLE_15] DEFAULT (''),
[H_USD_01] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_01] DEFAULT (''),
[H_USD_02] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_02] DEFAULT (''),
[H_USD_03] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_03] DEFAULT (''),
[H_USD_04] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_04] DEFAULT (''),
[H_USD_05] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_05] DEFAULT (''),
[H_USD_06] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_06] DEFAULT (''),
[H_USD_07] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_07] DEFAULT (''),
[H_USD_08] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_08] DEFAULT (''),
[H_USD_09] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_09] DEFAULT (''),
[H_USD_10] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_H_USD_10] DEFAULT (''),
[D_USD_01] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_01] DEFAULT (''),
[D_USD_02] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_02] DEFAULT (''),
[D_USD_03] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_03] DEFAULT (''),
[D_USD_04] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_04] DEFAULT (''),
[D_USD_05] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_05] DEFAULT (''),
[D_USD_06] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_06] DEFAULT (''),
[D_USD_07] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_07] DEFAULT (''),
[D_USD_08] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_08] DEFAULT (''),
[D_USD_09] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_09] DEFAULT (''),
[D_USD_10] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_D_USD_10] DEFAULT (''),
[LP_TRF_ROOM] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LP_TRF_ROOM] DEFAULT (''),
[LP_DELIVERY_ZONE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LP_DELIVERY_ZONE] DEFAULT (''),
[PICK_SLIP_NO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_PICK_SLIP_NO] DEFAULT (''),
[PICK_METHOD] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_PICK_METHOD] DEFAULT (''),
[PCS_PICK_METHOD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_PCS_PICK_METHOD] DEFAULT (''),
[LOC] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOC] DEFAULT (''),
[TO_LOC] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_TO_LOC] DEFAULT (''),
[LOT] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT] DEFAULT (''),
[TO_LOT] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_TO_LOT] DEFAULT (''),
[ID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_ID] DEFAULT (''),
[TO_ID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_TO_ID] DEFAULT (''),
[DROP_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DROP_ID] DEFAULT (''),
[CASE_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_CASE_ID] DEFAULT (''),
[STR_SUSR1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_STR_SUSR1] DEFAULT (''),
[STR_SUSR2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_STR_SUSR2] DEFAULT (''),
[STR_SUSR3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_STR_SUSR3] DEFAULT (''),
[STR_SUSR4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_STR_SUSR4] DEFAULT (''),
[STR_SUSR5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_STR_SUSR5] DEFAULT (''),
[STR_CLIENT_GROUP] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_STR_CLIENT_GROUP] DEFAULT (''),
[STR_SEGMENT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_STR_SEGMENT] DEFAULT (''),
[SKU_DESCRIPTION] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_DESCRIPTION] DEFAULT (''),
[SKU_SUSR1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_SUSR1] DEFAULT (''),
[SKU_SUSR2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_SUSR2] DEFAULT (''),
[SKU_SUSR3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_SUSR3] DEFAULT (''),
[SKU_SUSR4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_SUSR4] DEFAULT (''),
[SKU_SUSR5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_SUSR5] DEFAULT (''),
[SKU_STDGROSSWGT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_STDGROSSWGT] DEFAULT (''),
[SKU_STDNETWGT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_STDNETWGT] DEFAULT (''),
[SKU_STDCUBE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_STDCUBE] DEFAULT (''),
[SKU_CLASS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_CLASS] DEFAULT (''),
[SKU_GROUP] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_GROUP] DEFAULT (''),
[SKU_ITEM_CLASS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_ITEM_CLASS] DEFAULT (''),
[SKU_STYLE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_STYLE] DEFAULT (''),
[SKU_COLOR] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_COLOR] DEFAULT (''),
[SKU_SIZE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_SIZE] DEFAULT (''),
[SKU_MEASUREMENT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_MEASUREMENT] DEFAULT (''),
[SKU_VAS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_VAS] DEFAULT (''),
[SKU_OVAS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_OVAS] DEFAULT (''),
[SKU_HAZARDOUSFLAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_HAZARDOUSFLAG] DEFAULT (''),
[SKU_TEMPERATUREFLAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_TEMPERATUREFLAG] DEFAULT (''),
[SKU_PRODUCTMODEL] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_PRODUCTMODEL] DEFAULT (''),
[SKU_PREPACKINDICATOR] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_PREPACKINDICATOR] DEFAULT (''),
[SKU_BUSR1] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR1] DEFAULT (''),
[SKU_BUSR2] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR2] DEFAULT (''),
[SKU_BUSR3] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR3] DEFAULT (''),
[SKU_BUSR4] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR4] DEFAULT (''),
[SKU_BUSR5] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR5] DEFAULT (''),
[SKU_BUSR6] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR6] DEFAULT (''),
[SKU_BUSR7] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR7] DEFAULT (''),
[SKU_BUSR8] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR8] DEFAULT (''),
[SKU_BUSR9] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR9] DEFAULT (''),
[SKU_BUSR10] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_BUSR10] DEFAULT (''),
[SKU_CASECNT] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_SKU_CASECNT] DEFAULT (''),
[FT_USD_01] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_01] DEFAULT (''),
[FT_USD_02] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_02] DEFAULT (''),
[FT_USD_03] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_03] DEFAULT (''),
[FT_USD_04] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_04] DEFAULT (''),
[FT_USD_05] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_05] DEFAULT (''),
[FT_USD_06] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_06] DEFAULT (''),
[FT_USD_07] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_07] DEFAULT (''),
[FT_USD_08] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_08] DEFAULT (''),
[FT_USD_09] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_09] DEFAULT (''),
[FT_USD_10] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_10] DEFAULT (''),
[FT_USD_11] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_11] DEFAULT (''),
[FT_USD_12] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_12] DEFAULT (''),
[FT_USD_13] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_13] DEFAULT (''),
[FT_USD_14] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_14] DEFAULT (''),
[FT_USD_15] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_15] DEFAULT (''),
[FT_USD_16] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_16] DEFAULT (''),
[FT_USD_17] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_17] DEFAULT (''),
[FT_USD_18] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_18] DEFAULT (''),
[FT_USD_19] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_19] DEFAULT (''),
[FT_USD_20] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_FT_USD_20] DEFAULT (''),
[LOT_LOTTABLE_01] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_01] DEFAULT (''),
[LOT_LOTTABLE_02] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_02] DEFAULT (''),
[LOT_LOTTABLE_03] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_03] DEFAULT (''),
[LOT_LOTTABLE_04] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_04] DEFAULT (''),
[LOT_LOTTABLE_05] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_05] DEFAULT (''),
[LOT_LOTTABLE_06] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_06] DEFAULT (''),
[LOT_LOTTABLE_07] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_07] DEFAULT (''),
[LOT_LOTTABLE_08] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_08] DEFAULT (''),
[LOT_LOTTABLE_09] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_09] DEFAULT (''),
[LOT_LOTTABLE_10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_10] DEFAULT (''),
[LOT_LOTTABLE_11] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_11] DEFAULT (''),
[LOT_LOTTABLE_12] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_12] DEFAULT (''),
[LOT_LOTTABLE_13] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_13] DEFAULT (''),
[LOT_LOTTABLE_14] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_14] DEFAULT (''),
[LOT_LOTTABLE_15] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_LOT_LOTTABLE_15] DEFAULT (''),
[BILLABLE_DATE] [datetime] NULL CONSTRAINT [DF_WMS_TPB_BASE_BILLABLE_DATE] DEFAULT (''),
[R_SKU_COUNT] [numeric] (14, 0) NULL CONSTRAINT [DF_WMS_TPB_BASE_R_SKU_COUNT] DEFAULT ((0)),
[R_LABEL_COUNT] [numeric] (14, 0) NULL CONSTRAINT [DF_WMS_TPB_BASE_R_LABEL_COUNT] DEFAULT ((0)),
[R_CC_WMS_QTY] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_R_CC_WMS_QTY] DEFAULT ((0)),
[R_SERVICE_PROVIDER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_R_SERVICE_PROVIDER] DEFAULT (''),
[R_SHIPMENT_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_R_SHIPMENT_ID] DEFAULT (''),
[R_LINE_PRICE] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_R_LINE_PRICE] DEFAULT ((0)),
[R_LINE_TOTAL] [numeric] (20, 6) NULL CONSTRAINT [DF_WMS_TPB_BASE_R_LINE_TOTAL] DEFAULT ((0)),
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_TPB_BASE_DBID] DEFAULT (db_name())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WMS_TPB_BASE] ADD CONSTRAINT [PK_WMS_TPB_BASE_SEQ] PRIMARY KEY CLUSTERED ([SEQ]) WITH (FILLFACTOR=80, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_WMS_TPB_BASE_01] ON [dbo].[WMS_TPB_BASE] ([BatchNo], [CODE], [DOCUMENT_ID]) WITH (FILLFACTOR=80, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_WMS_TPB_BASE_02] ON [dbo].[WMS_TPB_BASE] ([BatchNo], [STATUS]) WITH (FILLFACTOR=80, PAD_INDEX=ON) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[WMS_TPB_BASE] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[WMS_TPB_BASE] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[WMS_TPB_BASE] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[WMS_TPB_BASE] TO [NSQL]
GO
EXEC sp_addextendedproperty N'MS_Description', N'AddDate', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'ADD_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'AddWho', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'ADD_WHO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'QtyReceived/Pack.Casecnt', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_CARTON'
GO
EXEC sp_addextendedproperty N'MS_Description', N'QtyReceived*STDCUBE', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_CBM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ContainerQty', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_CONTAINER'
GO
EXEC sp_addextendedproperty N'MS_Description', N'EditDate', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Upon Request', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_DROP'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_NO_OF_LOC'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Count distinct(ToID)', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_PALLET'
GO
EXEC sp_addextendedproperty N'MS_Description', N'QtyReceived', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_QUANTITY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'GrossWgt', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'BILLABLE_WEIGHT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CARTON_UOM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CASE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CBM_UOM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'StorerKey', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CLIENT_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ExternPOKey', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CLIENT_PO_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ExternBASENumber', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CLIENT_REF'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ExternLineNo', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CLIENT_REF_LINE_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'HostWHCode', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CLIENT_SITE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BASE', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CODE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Source Query Config ID', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CONFIG_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ContainerKey', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CONTAINER_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ContainerType', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'CONTAINER_TYPE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'System Country (3 Char ISO)', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'COUNTRY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine01', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_01'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine02', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_02'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine03', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_03'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine04', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_04'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine05', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_05'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine06', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_06'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine07', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_07'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine08', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_08'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine09', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_09'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine10', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'D_USD_10'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BASEGroup', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOC_GROUPING_1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOC_GROUPING_2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOC_PRE_STATUS'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOC_REASON'
GO
EXEC sp_addextendedproperty N'MS_Description', N'WMS', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOC_SOURCE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ASNStatus', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOC_STATUS'
GO
EXEC sp_addextendedproperty N'MS_Description', N'RECType', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOC_SUB_TYPE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'DocType (A = ASN, R = Return)', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOC_TYPE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BASEKey', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOCUMENT_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BASELineNumber', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DOCUMENT_LINE_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'DROP_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'EditDate', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'EDIT_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'EditWho', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'EDIT_WHO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine01', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_01'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine02', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_02'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine03', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_03'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine04', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_04'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine05', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_05'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine06', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_06'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine07', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_07'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine08', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_08'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine09', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_09'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine10', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_10'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine11', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_11'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine12', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_12'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine13', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_13'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine14', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_14'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine15', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_15'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine16', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_16'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine17', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_17'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine18', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_18'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine19', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_19'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine20', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'FT_USD_20'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine01', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_01'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine02', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_02'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine03', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_03'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine04', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_04'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine05', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_05'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine06', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_06'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine07', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_07'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine08', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_08'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine09', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_09'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UserDefine10', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'H_USD_10'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Creation Date & Time', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'INSERT_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOAD_PLAN_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOC'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOCATION_TYPE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable01', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_01'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable02', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_02'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable03', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_03'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable04', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_04'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable05', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_05'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable06', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_06'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable07', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_07'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable08', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_08'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable09', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_09'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable10', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_10'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable11', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_11'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable12', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_12'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable13', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_13'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable14', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_14'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable15', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOT_LOTTABLE_15'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable01', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_01'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable02', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_02'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable03', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_03'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable04', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_04'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable05', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_05'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable06', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_06'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable07', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_07'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable08', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_08'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable09', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_09'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable10', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_10'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable11', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_11'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable12', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_12'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable13', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_13'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable14', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_14'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Lottable15', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LOTTABLE_15'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LP_DELIVERY_ZONE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'LP_TRF_ROOM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'MBOL_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'WarehouseReference', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'OTHER_REFERENCE_1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'WarehouseReference', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'OTHER_REFERENCE_2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'PALLET_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'PCS_PICK_METHOD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'PICK_METHOD'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'PICK_SLIP_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'POKey', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'PO_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'PRIORITY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'UOM', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'QTY_UOM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'R_CC_WMS_QTY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'R_LABEL_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'R_LINE_PRICE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'R_LINE_TOTAL'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'R_SERVICE_PROVIDER'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'R_SHIPMENT_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'R_SKU_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'DateReceived', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'REFERENCE_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Generated Running ID', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SEQ'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SellerCompany', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SHIP_FROM_COMPANY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SellerCountry', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SHIP_FROM_COUNTRY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SellerName', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SHIP_FROM_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SHIP_TO_COMPANY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SHIP_TO_COUNTRY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SHIP_TO_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SITE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR1', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR10', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR10'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR2', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR3', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR4', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR4'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR5', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR5'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR6', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR6'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR7', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR7'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR8', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR8'
GO
EXEC sp_addextendedproperty N'MS_Description', N'BUSR9', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_BUSR9'
GO
EXEC sp_addextendedproperty N'MS_Description', N'CASECNT', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_CASECNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'CLASS', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_CLASS'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Color', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_COLOR'
GO
EXEC sp_addextendedproperty N'MS_Description', N'DESCR', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_DESCRIPTION'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SKUGROUP', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_GROUP'
GO
EXEC sp_addextendedproperty N'MS_Description', N'HazardousFlag', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_HAZARDOUSFLAG'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SKU', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ItemClass', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_ITEM_CLASS'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Measurement', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_MEASUREMENT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'OVAS', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_OVAS'
GO
EXEC sp_addextendedproperty N'MS_Description', N'PrePackIndicator', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_PREPACKINDICATOR'
GO
EXEC sp_addextendedproperty N'MS_Description', N'ProductModel', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_PRODUCTMODEL'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Size', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_SIZE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'STDCUBE', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_STDCUBE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'STDGROSSWGT', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_STDGROSSWGT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'STDNETWGT', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_STDNETWGT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Style', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_STYLE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR1', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_SUSR1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR2', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_SUSR2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR3', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_SUSR3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR4', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_SUSR4'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR5', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_SUSR5'
GO
EXEC sp_addextendedproperty N'MS_Description', N'TemperatureFlag', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_TEMPERATUREFLAG'
GO
EXEC sp_addextendedproperty N'MS_Description', N'IVAS', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'SKU_VAS'
GO
EXEC sp_addextendedproperty N'MS_Description', N'0 = New; 1 = Processing, 9 = Processed, 5 = Error, W = Work In progress', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'STATUS'
GO
EXEC sp_addextendedproperty N'MS_Description', N'CustomerGroupCode', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'STR_CLIENT_GROUP'
GO
EXEC sp_addextendedproperty N'MS_Description', N'MarketSegment', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'STR_SEGMENT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR1', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'STR_SUSR1'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR2', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'STR_SUSR2'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR3', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'STR_SUSR3'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR4', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'STR_SUSR4'
GO
EXEC sp_addextendedproperty N'MS_Description', N'SUSR5', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'STR_SUSR5'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'TO_CLIENT_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'TO_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'TO_LOC'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'TO_LOT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'TO_SITE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'TPB_UPLOADED_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'TPB_UPLOADED_STATUS'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A = ACTIVITIES', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'TRANSACTION_TYPE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Update Date & Time', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'UPDATE_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'VehicleDate', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'VEHICLE_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'VehicleNumber', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'VEHICLE_NO'
GO
EXEC sp_addextendedproperty N'MS_Description', N'VesselKey', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'VESSEL_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'VoyageKey', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'VOYAGE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'', 'SCHEMA', N'dbo', 'TABLE', N'WMS_TPB_BASE', 'COLUMN', N'WEIGHT_UOM'
GO
