CREATE TABLE [dbo].[WORKORDERJOBRECON]
(
[JobKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WORKORDERJOBRECON_JobKey] DEFAULT (''),
[JobReconLineNumber] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WORKORDERJOBRECON_JobReconLineNumber] DEFAULT (''),
[WorkOrderkey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WORKORDERJOBRECON_WorkOrderKey] DEFAULT (''),
[Storerkey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WORKORDERJOBRECON_Storerkey] DEFAULT (''),
[Sku] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WORKORDERJOBRECON_Sku] DEFAULT (''),
[NonInvSku] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WORKORDERJOBRECON_NonInvSku] DEFAULT (''),
[Packkey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_Packkey] DEFAULT (''),
[UOM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_UOM] DEFAULT (''),
[QtyReserved] [int] NULL CONSTRAINT [DF_WORKORDERJOBRECON_QtyReserved] DEFAULT ((0)),
[WastageUOM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_WastageUOM] DEFAULT (''),
[QtyWastage] [int] NULL CONSTRAINT [DF_WORKORDERJOBRECON_QtyWastage] DEFAULT ((0)),
[WastageReason] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_WastageReason] DEFAULT (''),
[RejectUOM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_RejectUOM] DEFAULT (''),
[QtyReject] [int] NULL CONSTRAINT [DF_WORKORDERJOBRECON_QtyReject] DEFAULT ((0)),
[RejectReason] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_RejectReason] DEFAULT (''),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_AddWho] DEFAULT (suser_sname()),
[AddDate] [datetime] NULL CONSTRAINT [DF_WORKORDERJOBRECON_AddDate] DEFAULT (getdate()),
[EditWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_EditWho] DEFAULT (suser_sname()),
[EditDate] [datetime] NULL CONSTRAINT [DF_WORKORDERJOBRECON_EditDate] DEFAULT (getdate()),
[TrafficCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchiveCop] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RemainingUOM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WORKORDERJOBRECON_RemainingUOM] DEFAULT (''),
[QtyRemaining] [int] NULL CONSTRAINT [DF_WORKORDERJOBRECON_QtyRemaining] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WORKORDERJOBRECON] ADD CONSTRAINT [PK_WORKORDERJOBRECON] PRIMARY KEY CLUSTERED ([JobKey], [JobReconLineNumber]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[WORKORDERJOBRECON] TO [NSQL]
GO
GRANT INSERT ON  [dbo].[WORKORDERJOBRECON] TO [NSQL]
GO
GRANT SELECT ON  [dbo].[WORKORDERJOBRECON] TO [NSQL]
GO
GRANT UPDATE ON  [dbo].[WORKORDERJOBRECON] TO [NSQL]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Qty Remaining to return', 'SCHEMA', N'dbo', 'TABLE', N'WORKORDERJOBRECON', 'COLUMN', N'QtyRemaining'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Qty Remaining UOM', 'SCHEMA', N'dbo', 'TABLE', N'WORKORDERJOBRECON', 'COLUMN', N'RemainingUOM'
GO
