IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ALPHA\INDWMSTeam')
CREATE LOGIN [ALPHA\INDWMSTeam] FROM WINDOWS
GO
CREATE USER [ALPHA\INDWMSTeam] FOR LOGIN [ALPHA\INDWMSTeam]
GO
