IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ALPHA\JackGongXY')
CREATE LOGIN [ALPHA\JackGongXY] FROM WINDOWS
GO
CREATE USER [ALPHA\JackGongXY] FOR LOGIN [ALPHA\JackGongXY]
GO
