IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ALPHA\BEHTSUINEE')
CREATE LOGIN [ALPHA\BEHTSUINEE] FROM WINDOWS
GO
CREATE USER [ALPHA\BehTsuiNee] FOR LOGIN [ALPHA\BEHTSUINEE]
GO
