IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ALPHA\GTWMSinfosys')
CREATE LOGIN [ALPHA\GTWMSinfosys] FROM WINDOWS
GO
CREATE USER [ALPHA\GTWMSinfosys] FOR LOGIN [ALPHA\GTWMSinfosys] WITH DEFAULT_SCHEMA=[ALPHA\GTWMSinfosys]
GO
REVOKE CONNECT TO [ALPHA\GTWMSinfosys]
