IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ALPHA\GTWMSProject')
CREATE LOGIN [ALPHA\GTWMSProject] FROM WINDOWS
GO
CREATE USER [ALPHA\GTWMSProject] FOR LOGIN [ALPHA\GTWMSProject]
GO
