SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [BI].[V_ADJUSTMENTDETAIL] AS
SELECT *
  FROM [ADJUSTMENTDETAIL] WITH (NOLOCK)  
GO
GRANT SELECT ON  [BI].[V_ADJUSTMENTDETAIL] TO [JReportRole]
GO
