SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [BI].[V_LoadPlanDetail] AS 
SELECT * 
   FROM [LoadPlanDetail] WITH (NOLOCK)  
GO
GRANT SELECT ON  [BI].[V_LoadPlanDetail] TO [JReportRole]
GO
