SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
-- [CN] WMS Add View To BI Schema For JReport - CONTAINERDETAIL https://jiralfl.atlassian.net/browse/WMS-19568

CREATE OR ALTER VIEW [BI].[V_CONTAINERDETAIL] AS 
SELECT * 
   FROM dbo.CONTAINERDETAIL WITH (NOLOCK)  
GO
GRANT SELECT ON  [BI].[V_CONTAINERDETAIL] TO [JReportRole]
GO
/*
EXEC AS LOGIN = 'JReportUserCN'
SELECT SUSER_SNAME()
SELECT * FROM [BI].[V_CONTAINERDETAIL]

REVERT;
*/
