SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

--https://jiralfl.atlassian.net/browse/WMS-20039
CREATE OR ALTER VIEW  [BI].[V_TMS_SHIPMENT] AS
SELECT *
FROM dbo.TMS_SHIPMENT WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TMS_SHIPMENT] TO [JReportRole]
GO
/*
EXECUTE AS LOGIN ='JREPORTUSERPH'

SELECT SUSER_SNAME(), USER_NAME()

SELECT TOP 999 * FROM BI.V_TMS_SHIPMENT

REVERT

SELECT TOP 99 * FROM ExecutionLog ORDER BY 1 DESC

*/