SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [BI].[V_IDS_LP_Driver] 
AS 
SELECT * 
FROM dbo.IDS_LP_Driver WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_IDS_LP_Driver] TO [JReportRole]
GO
