SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW   [BI].[V_TaskManagerReason] AS 
SELECT * FROM dbo.TaskManagerReason WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TaskManagerReason] TO [JReportRole]
GO
