SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [BI].[V_INVENTORYHOLD] AS 
SELECT * 
   FROM [INVENTORYHOLD]  WITH (NOLOCK) 
GO
GRANT SELECT ON  [BI].[V_INVENTORYHOLD] TO [JReportRole]
GO
