SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [BI].[V_DAILYINVENTORY] AS 
SELECT * 
   FROM [DAILYINVENTORY] WITH (NOLOCK) 
GO
GRANT SELECT ON  [BI].[V_DAILYINVENTORY] TO [JReportRole]
GO
