SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_ADJUSTMENTDETAIL] AS
SELECT *
  FROM [ADJUSTMENTDETAIL] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_ADJUSTMENTDETAIL] TO [JReportRole]
GO
