SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_AllocShortageLog]
AS
SELECT *
FROM dbo.AllocShortageLog WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_AllocShortageLog] TO [JReportRole]
GO
