SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW   [BI].[V_AreaDetail] AS
SELECT * FROM dbo.AreaDetail WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_AreaDetail] TO [JReportRole]
GO
