SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_BillOfMaterial] AS
SELECT *
   FROM [BillOfMaterial] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_BillOfMaterial] TO [JReportRole]
GO
