SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW   [BI].[V_CARTONIZATION] AS 
SELECT * FROM dbo.CARTONIZATION WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_CARTONIZATION] TO [JReportRole]
GO
