SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_CartonTrack]
AS
SELECT *
FROM dbo.CartonTrack WITH (NOLOCK)
GO

GRANT SELECT ON  [BI].[V_CartonTrack] TO [JReportRole]
GO
