SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_CCDETAIL] AS
SELECT *
   FROM [CCDETAIL] WITH (NOLOCK)
GO

GRANT SELECT ON  [BI].[V_CCDETAIL] TO [JReportRole]
GO
