SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

--https://jiralfl.atlassian.net/browse/WMS-12777
CREATE OR ALTER VIEW [BI].[V_GUI]
AS
SELECT *
FROM [GUI] WITH (NOLOCK)

GO
GRANT SELECT ON  [BI].[V_GUI] TO [JReportRole]
GO
