SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_IDS_LP_VEHICLE]
AS
SELECT *
FROM dbo.IDS_LP_VEHICLE WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_IDS_LP_VEHICLE] TO [JReportRole]
GO
