SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_IDS_LP_Driver]
AS
SELECT *
FROM dbo.IDS_LP_Driver WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_IDS_LP_Driver] TO [JReportRole]
GO
