SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_INVENTORYHOLD] AS
SELECT *
   FROM [INVENTORYHOLD]  WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_INVENTORYHOLD] TO [JReportRole]
GO
