SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW   [BI].[V_InventoryQC] AS
SELECT * FROM dbo.InventoryQC WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_InventoryQC] TO [JReportRole]
GO
