SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_LotxLocxID] AS
SELECT *
   FROM [LotxLocxID] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_LotxLocxID] TO [JReportRole]
GO
