SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_LOTATTRIBUTE] AS
SELECT *
   FROM [LOTATTRIBUTE] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_LOTATTRIBUTE] TO [JReportRole]
GO
