SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_MBOLDetail] AS
SELECT *
   FROM [MBOLDetail] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_MBOLDetail] TO [JReportRole]
GO
