SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [BI].[V_OrderDetailRef]
AS
SELECT * 
FROM [dbo].[OrderDetailRef] with (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_OrderDetailRef] TO [JReportRole]
GO
