SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_OrderDetailRef]
AS
SELECT *
FROM [dbo].[OrderDetailRef] with (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_OrderDetailRef] TO [JReportRole]
GO
