SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_ORDERDetail] AS
SELECT *
   FROM [ORDERDetail] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_ORDERDetail] TO [JReportRole]
GO
