SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

--https://jiralfl.atlassian.net/browse/WMS-15455
CREATE VIEW [BI].[V_PACKLOG] 
AS 
SELECT * FROM PACKLOG WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_PACKLOG] TO [JReportRole]
GO
