SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_PALLETDETAIL] AS
SELECT *
   FROM [PALLETDETAIL] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_PALLETDETAIL] TO [JReportRole]
GO
