SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW   [BI].[V_PackSerialNo] AS
SELECT * FROM dbo.PackSerialNo WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_PackSerialNo] TO [JReportRole]
GO
