SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_PackDetail] AS
SELECT *
   FROM [PackDetail] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_PackDetail] TO [JReportRole]
GO
