SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_PickingInfo] AS
SELECT *
   FROM [PickingInfo] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_PickingInfo] TO [JReportRole]
GO
