SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_PickHeader] AS
SELECT *
   FROM [PickHeader] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_PickHeader] TO [JReportRole]
GO
