SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_PickDetail] AS
SELECT *
   FROM [PickDetail] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_PickDetail] TO [JReportRole]
GO
