SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_rdtPTLPieceLog]
AS
SELECT *
FROM rdt.rdtPTLPieceLog WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_rdtPTLPieceLog] TO [JReportRole]
GO