SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_rdtPTLStationLogQueue]
AS
SELECT *
FROM rdt.rdtPTLStationLogQueue WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_rdtPTLStationLogQueue] TO [JReportRole]
GO
