SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW   [BI].[V_REPLENISHMENT] AS
SELECT * FROM dbo.REPLENISHMENT WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_REPLENISHMENT] TO [JReportRole]
GO
