SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW   [BI].[V_REPLENISHMENT] AS 
SELECT * FROM dbo.REPLENISHMENT WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_REPLENISHMENT] TO [JReportRole]
GO
