SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_RouteMaster] AS
SELECT *
   FROM [RouteMaster] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_RouteMaster] TO [JReportRole]
GO
