SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

--https://jiralfl.atlassian.net/browse/WMS-15455
CREATE OR ALTER VIEW [BI].[V_SKU_Log]
AS
SELECT * FROM SKU_Log WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_SKU_Log] TO [JReportRole]
GO
