SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW   [BI].[V_StorerSODefault] AS 
SELECT * FROM dbo.StorerSODefault WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_StorerSODefault] TO [JReportRole]
GO
