SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW   [BI].[V_StorerSODefault] AS
SELECT * FROM dbo.StorerSODefault WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_StorerSODefault] TO [JReportRole]
GO
