SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_StorerConfig] AS
SELECT *
   FROM [StorerConfig] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_StorerConfig] TO [JReportRole]
GO
