SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW   [BI].[V_TaskManagerUser] AS
SELECT * FROM dbo.TaskManagerUser WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TaskManagerUser] TO [JReportRole]
GO
