SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW   [BI].[V_TaskManagerReason] AS
SELECT * FROM dbo.TaskManagerReason WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TaskManagerReason] TO [JReportRole]
GO
