SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_TaskDetail] AS
SELECT *
   FROM [TaskDetail] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TaskDetail] TO [JReportRole]
GO
