SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_TRANSFERDETAIL] AS
SELECT *
   FROM [TRANSFERDETAIL] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TRANSFERDETAIL] TO [JReportRole]
GO
