SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [BI].[V_TRANSMITLOG2] AS 
SELECT * 
   FROM [TRANSMITLOG2] WITH (NOLOCK)  
GO
GRANT SELECT ON  [BI].[V_TRANSMITLOG2] TO [JReportRole]
GO
