SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_TRANSMITLOG3] AS
SELECT *
   FROM [TRANSMITLOG3] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TRANSMITLOG3] TO [JReportRole]
GO
