SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_TRANSMITLOG2] AS
SELECT *
   FROM [TRANSMITLOG2] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TRANSMITLOG2] TO [JReportRole]
GO
