SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [BI].[V_TRANSMITLOG] AS
SELECT *
   FROM [TRANSMITLOG] WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_TRANSMITLOG] TO [JReportRole]
GO
