SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW   [BI].[V_WAVEDETAIL] AS
SELECT * FROM dbo.WAVEDETAIL WITH (NOLOCK)
GO
GRANT SELECT ON  [BI].[V_WAVEDETAIL] TO [JReportRole]
GO
