IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'RDT' AND TABLE_NAME = 'RDTLoginLog' AND COLUMN_NAME = 'SessionID')
BEGIN
  ALTER TABLE RDT.RDTLoginLog ADD SessionID NVARCHAR(60) NULL
END;
GO