CREATE TABLE [RDT].[RDTCfg_SYS]
(
[Function_ID] [int] NOT NULL,
[Config] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Description] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Value] [int] NOT NULL CONSTRAINT [DF_RDTCfg_SYS_Value] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [RDT].[RDTCfg_SYS] ADD CONSTRAINT [PK_RDTCfg_SYS] PRIMARY KEY CLUSTERED ([Function_ID], [Config]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [RDT].[RDTCfg_SYS] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[RDTCfg_SYS] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[RDTCfg_SYS] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[RDTCfg_SYS] TO [NSQL]
GO
