IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES
               WHERE TABLE_SCHEMA = 'RDT' AND TABLE_NAME = 'rdtFunctionCategory')
BEGIN
    CREATE TABLE [RDT].[rdtFunctionCategory]
    (
        [FunctionID]   [int]            NOT NULL,
        [StorerKey]    [nvarchar] (15)  NOT NULL CONSTRAINT [DF_rdtFunctionCategory_StorerKey]   DEFAULT (''),
        [Facility]     [nvarchar] (5)   NOT NULL CONSTRAINT [DF_rdtFunctionCategory_Facility]    DEFAULT (''),
        [Type]         [nvarchar] (50)  NOT NULL CONSTRAINT [DF_rdtFunctionCategory_Type]        DEFAULT ('Standard'),
        [Category]     [nvarchar] (100) NOT NULL CONSTRAINT [DF_rdtFunctionCategory_Category]    DEFAULT (''),
        [SubCategory]  [nvarchar] (100) NOT NULL CONSTRAINT [DF_rdtFunctionCategory_SubCategory] DEFAULT (''),
        [UDFCategory]  [nvarchar] (100) NOT NULL CONSTRAINT [DF_rdtFunctionCategory_UDFCategory] DEFAULT (''),
        [Active]       [nvarchar] (1)   NOT NULL CONSTRAINT [DF_rdtFunctionCategory_Active]      DEFAULT ('Y'),
        [AddDate]      [datetime]       NOT NULL CONSTRAINT [DF_rdtFunctionCategory_AddDate]     DEFAULT (getdate()),
        [AddWho]       [nvarchar] (128) NOT NULL CONSTRAINT [DF_rdtFunctionCategory_AddWho]      DEFAULT (suser_sname()),
        [EditDate]     [datetime]       NOT NULL CONSTRAINT [DF_rdtFunctionCategory_EditDate]    DEFAULT (getdate()),
        [EditWho]      [nvarchar] (128) NOT NULL CONSTRAINT [DF_rdtFunctionCategory_EditWho]     DEFAULT (suser_sname())
    ) ON [PRIMARY]

    ALTER TABLE [RDT].[rdtFunctionCategory] ADD CONSTRAINT [PKrdtFunctionCategory]
        PRIMARY KEY CLUSTERED ([FunctionID], [StorerKey], [Facility], [Category])
        ON [PRIMARY]

    ALTER TABLE [RDT].[rdtFunctionCategory] WITH NOCHECK ADD CONSTRAINT [CK_rdtFunctionCategory_Active]
        CHECK (([Active] IN ('Y', 'N')))

    CREATE NONCLUSTERED INDEX [IDX_rdtFunctionCategory_StorerFacility]
        ON [RDT].[rdtFunctionCategory] ([StorerKey], [Facility], [Category])
        ON [PRIMARY]

    GRANT DELETE ON [RDT].[rdtFunctionCategory] TO [NSQL]
    GRANT INSERT ON [RDT].[rdtFunctionCategory] TO [NSQL]
    GRANT SELECT ON [RDT].[rdtFunctionCategory] TO [NSQL]
    GRANT UPDATE ON [RDT].[rdtFunctionCategory] TO [NSQL]

    EXEC sp_addextendedproperty N'MS_Description', 'RDT function identifier', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'FunctionID'
    EXEC sp_addextendedproperty N'MS_Description', 'Storer/owner of the goods', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'StorerKey'
    EXEC sp_addextendedproperty N'MS_Description', 'Warehouse facility code', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'Facility'
    EXEC sp_addextendedproperty N'MS_Description', 'Function type classification (Standard, Retired or Customized)', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'Type'
    EXEC sp_addextendedproperty N'MS_Description', 'Function category', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'Category'
    EXEC sp_addextendedproperty N'MS_Description', 'Function sub-category', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'SubCategory'
    EXEC sp_addextendedproperty N'MS_Description', 'User-defined function category', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'UDFCategory'
    EXEC sp_addextendedproperty N'MS_Description', 'Indicates if this function category is active and available for use (Y/N)', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'Active'
    EXEC sp_addextendedproperty N'MS_Description', 'Date when the record was created. (System date)', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'AddDate'
    EXEC sp_addextendedproperty N'MS_Description', 'User who created the record', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'AddWho'
    EXEC sp_addextendedproperty N'MS_Description', 'Date when the record was last modified. (System date)', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'EditDate'
    EXEC sp_addextendedproperty N'MS_Description', 'User who last modified the record', 'SCHEMA', N'RDT', 'TABLE', N'rdtFunctionCategory', 'COLUMN', N'EditWho'
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES
           WHERE TABLE_SCHEMA = 'RDT' AND TABLE_NAME = 'rdtFunctionCategory')
BEGIN
    BEGIN TRY
        DELETE FROM [RDT].[rdtFunctionCategory]
        WHERE [StorerKey] = '' AND [Facility] = ''
    END TRY
    BEGIN CATCH
        PRINT 'Error occurred while deleting records from [RDT].[rdtFunctionCategory]: ' + ERROR_MESSAGE()
    END CATCH

    BEGIN TRY
        INSERT INTO [RDT].[rdtFunctionCategory] ([FunctionID], [StorerKey], [Facility], [Type], [Category], [SubCategory], [Active])
        VALUES
        (510  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (511  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (512  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (513  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (514  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (515  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (516  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (517  , '', '', 'Custom'      , 'Warehouse'   , 'Move'                                    , 'Y'),
        (518  , '', '', 'Custom'      , 'Warehouse'   , 'Move'                                    , 'Y'),
        (519  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (520  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (521  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (522  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (523  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (525  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (526  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (528  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (529  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (532  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (533  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (534  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (535  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (536  , '', '', 'Custom'      , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (537  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (539  , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (540  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (541  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (542  , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (543  , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (544  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (545  , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (546  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (547  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (548  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (550  , '', '', 'Retired'     , 'Inbound'     , 'Receive'                                 , 'N'),
        (551  , '', '', 'Retired'     , 'Inbound'     , 'Receive'                                 , 'N'),
        (552  , '', '', 'Standard'    , 'Inbound'     , 'Return'                                  , 'Y'),
        (553  , '', '', 'Standard'    , 'Inbound'     , 'Return'                                  , 'Y'),
        (554  , '', '', 'Retired'     , 'Inbound'     , 'Receive'                                 , 'N'),
        (555  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (556  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (557  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (558  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (559  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (560  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (561  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (562  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (563  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (564  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (565  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (566  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (567  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (568  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (569  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (570  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (571  , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (572  , '', '', 'Standard'    , 'Outbound'    , 'Inquiry'                                 , 'Y'),
        (573  , '', '', 'Retired'     , 'Inbound'     , 'Receive'                                 , 'N'),
        (574  , '', '', 'Standard'    , 'Inbound'     , 'Inquiry'                                 , 'Y'),
        (575  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (577  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (579  , '', '', 'Standard'    , 'Outbound'    , 'Sorting'                                 , 'Y'),
        (580  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (581  , '', '', 'Standard'    , 'Inbound'     , 'Return'                                  , 'Y'),
        (587  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (588  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (590  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (592  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (593  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (594  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (595  , '', '', 'Standard'    , 'Inbound'     , 'Inquiry'                                 , 'Y'),
        (596  , '', '', 'Standard'    , 'Outbound'    , 'Inquiry'                                 , 'Y'),
        (597  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (598  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (599  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (600  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (605  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (606  , '', '', 'Standard'    , 'Inbound'     , 'Return'                                  , 'Y'),
        (607  , '', '', 'Standard'    , 'Inbound'     , 'Return'                                  , 'Y'),
        (608  , '', '', 'Standard'    , 'Inbound'     , 'Receive/Return'                          , 'Y'),
        (609  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (610  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (611  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (612  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (617  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (619  , '', '', 'Custom'      , 'Warehouse'   , 'Adjustment'                              , 'Y'),
        (620  , '', '', 'Retired'     , 'Outbound'    , 'Picking'                                 , 'N'),
        (621  , '', '', 'Retired'     , 'Outbound'    , 'Picking'                                 , 'N'),
        (622  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (624  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (625  , '', '', 'Custom'      , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (627  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (628  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (629  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (630  , '', '', 'Custom'      , 'Inbound'     , 'Return'                                  , 'Y'),
        (631  , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (632  , '', '', 'Custom'      , 'Warehouse'   , 'Kit'                                     , 'Y'),
        (633  , '', '', 'Custom'      , 'Warehouse'   , 'Move'                                    , 'Y'),
        (634  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (635  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (638  , '', '', 'Standard'    , 'Inbound'     , 'Return'                                  , 'Y'),
        (639  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (641  , '', '', 'Standard'    , 'Outbound'    , 'Sorting'                                 , 'Y'),
        (642  , '', '', 'Standard'    , 'Outbound'    , 'Sorting'                                 , 'Y'),
        (644  , '', '', 'Standard'    , 'Inbound'     , 'Sorting'                                 , 'Y'),
        (645  , '', '', 'Standard'    , 'Inbound'     , 'Data Capture'                            , 'Y'),
        (646  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (647  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (649  , '', '', 'Standard'    , 'Warehouse'   , 'Kit'                                     , 'Y'),
        (651  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (652  , '', '', 'Standard'    , 'Warehouse'   , 'Activity Tracker'                        , 'Y'),
        (653  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (656  , '', '', 'Custom'      , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (657  , '', '', 'Custom'      , 'Inbound'     , 'Return'                                  , 'Y'),
        (664  , '', '', 'Custom'      , 'Inbound'     , 'Move'                                    , 'Y'),
        (683  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (685  , '', '', 'Custom'      , 'Inbound'     , 'Receive'                                 , 'Y'),
        (701  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (704  , '', '', 'Standard'    , 'Overall'     , 'Data capture'                            , 'Y'),
        (706  , '', '', 'Standard'    , 'Overall'     , 'Data capture'                            , 'Y'),
        (707  , '', '', 'Standard'    , 'Overall'     , 'Data capture'                            , 'Y'),
        (724  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (726  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (727  , '', '', 'Standard'    , 'Overall'     , 'Inquiry'                                 , 'Y'),
        (728  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (729  , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (730  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (731  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (732  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (733  , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (740  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (741  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (743  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (745  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (747  , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (760  , '', '', 'Retired'     , 'Outbound'    , 'Put To Light'                            , 'N'),
        (761  , '', '', 'Custom'      , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (762  , '', '', 'Custom'      , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (777  , '', '', 'Custom'      , 'Outbound'    , 'Packing'                                 , 'Y'),
        (800  , '', '', 'Standard'    , 'Overall'     , 'Maintenance'                             , 'Y'),
        (801  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (802  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (803  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (804  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (805  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (806  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (807  , '', '', 'Standard'    , 'Inbound'     , 'Put To Light'                            , 'Y'),
        (808  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (809  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (810  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (813  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (814  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (815  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (816  , '', '', 'Retired'     , 'Outbound'    , 'Put To Light'                            , 'N'),
        (818  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light '                           , 'Y'),
        (819  , '', '', 'Standard'    , 'Outbound'    , 'Put To Light '                           , 'Y'),
        (821  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (822  , '', '', 'Custom'      , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (823  , '', '', 'Custom'      , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (824  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (825  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (826  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (830  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (831  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (832  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (833  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (835  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (836  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (837  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (838  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (839  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (840  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (841  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (842  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (843  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (844  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (847  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (848  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (849  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (850  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (851  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (852  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (853  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (854  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (855  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (856  , '', '', 'Standard'    , 'Inbound'     , 'Activity Tracking'                       , 'Y'),
        (857  , '', '', 'Standard'    , 'Inbound'     , 'Activity Tracking'                       , 'Y'),
        (858  , '', '', 'Standard'    , 'Inbound'     , 'Activity Tracking'                       , 'Y'),
        (859  , '', '', 'Standard'    , 'Outbound'    , 'Activity Tracking'                       , 'Y'),
        (860  , '', '', 'Retired'     , 'Outbound'    , 'Picking'                                 , 'N'),
        (861  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (862  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (863  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (864  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (866  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (867  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (868  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (869  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (870  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (871  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (872  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (873  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (874  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (875  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (876  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (877  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (878  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (880  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (881  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (882  , '', '', 'Standard'    , 'Warehouse'   , 'Inventory'                               , 'Y'),
        (883  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (884  , '', '', 'Custom'      , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (885  , '', '', 'Custom'      , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (886  , '', '', 'Custom'      , 'Warehouse'   , 'Inventory'                               , 'Y'),
        (889  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (890  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (891  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (892  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (893  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (894  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (895  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (896  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (897  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (898  , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (899  , '', '', 'Standard'    , 'Warehouse'   , 'Inventory'                               , 'Y'),
        (900  , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (903  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (904  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (905  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (906  , '', '', 'Standard'    , 'Outbound'    , 'Audit'                                   , 'Y'),
        (910  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (911  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (912  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (913  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (915  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (920  , '', '', 'Standard'    , 'Outbound'    , 'Data capture'                            , 'Y'),
        (921  , '', '', 'Standard'    , 'Outbound'    , 'Packing'                                 , 'Y'),
        (922  , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (923  , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (924  , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (925  , '', '', 'Custom'      , 'Outbound'    , 'Loading'                                 , 'Y'),
        (927  , '', '', 'Standard'    , 'Outbound'    , ''                                        , 'Y'),
        (930  , '', '', 'Custom'      , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (932  , '', '', 'Custom'      , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (940  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (941  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (942  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (943  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (944  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (949  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (950  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (951  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (952  , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (955  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (957  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (958  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (960  , '', '', 'Custom'      , 'Warehouse'   , 'Inventory'                               , 'Y'),
        (961  , '', '', 'Standard'    , 'Warehouse'   , 'Inventory'                               , 'Y'),
        (970  , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (971  , '', '', 'Retired'     , 'Warehouse'   , 'Label Printing'                          , 'N'),
        (972  , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (973  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (974  , '', '', 'Retired'     , 'Warehouse'   , 'Label Printing'                          , 'N'),
        (980  , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (990  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (991  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (992  , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (993  , '', '', 'Custom'      , 'Outbound'    , 'Packing'                                 , 'Y'),
        (1009 , '', '', 'Retired'     , 'Warehouse'   , 'Serialization'                           , 'N'),
        (1010 , '', '', 'Standard'    , 'Warehouse'   , 'Serialization'                           , 'Y'),
        (1012 , '', '', 'Standard'    , 'Warehouse'   , 'Serialization'                           , 'Y'),
        (1013 , '', '', 'Standard'    , 'Warehouse'   , 'Serialization'                           , 'Y'),
        (1014 , '', '', 'Standard'    , 'Warehouse'   , 'Serialization'                           , 'Y'),
        (1015 , '', '', 'Standard'    , 'Warehouse'   , 'Serialization'                           , 'Y'),
        (1016 , '', '', 'Standard'    , 'Warehouse'   , 'Serialization'                           , 'Y'),
        (1017 , '', '', 'Standard'    , 'Warehouse'   , 'Serialization '                          , 'Y'),
        (1019 , '', '', 'Standard'    , 'Warehouse'   , 'Serialization'                           , 'Y'),
        (1027 , '', '', 'Standard'    , 'Warehouse'   , 'UCC'                                     , 'Y'),
        (1036 , '', '', 'Standard'    , 'Warehouse'   , 'Close Tote'                              , 'Y'),
        (1201 , '', '', 'Custom'      , 'Outbound'    , 'VNA'                                     , 'Y'),
        (1202 , '', '', 'Custom'      , 'Outbound'    , 'VNA'                                     , 'Y'),
        (1203 , '', '', 'Custom'      , 'Inbound'     , 'VNA'                                     , 'Y'),
        (1570 , '', '', 'Standard'    , 'Outbound'    , 'XDOCK'                                   , 'Y'),
        (1580 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1581 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1582 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1583 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1584 , '', '', 'Custom'      , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1589 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1590 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1600 , '', '', 'Standard'    , 'Inbound'     , 'Return'                                  , 'Y'),
        (1610 , '', '', 'Retired'     , 'Warehouse'   , 'Label Printing'                          , 'N'),
        (1620 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1621 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1622 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1623 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1624 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1625 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1626 , '', '', 'Retired'     , 'Warehouse'   , 'Label Printing'                          , 'N'),
        (1628 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1629 , '', '', 'Custom'      , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (1630 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1631 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1632 , '', '', 'Custom'      , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (1633 , '', '', 'Custom'      , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1634 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1635 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1636 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1637 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1638 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1639 , '', '', 'Retired'     , 'Outbound'    , 'Label Printing'                          , 'N'),
        (1640 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1641 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1642 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1643 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1644 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1646 , '', '', 'Custom'      , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (1647 , '', '', 'Custom'      , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (1648 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1649 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1650 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1651 , '', '', 'Custom'      , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1652 , '', '', 'Custom'      , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1653 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1654 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1655 , '', '', 'Standard'    , 'Warehouse'   , 'Sorting'                                 , 'Y'),
        (1663 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1664 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1665 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1666 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1667 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1668 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1709 , '', '', 'Standard'    , 'Warehouse'   , 'Sorting'                                 , 'Y'),
        (1710 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1711 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1712 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1713 , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1715 , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1716 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1717 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1718 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1719 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1720 , '', '', 'Standard'    , 'Warehouse'   , 'Pallet Build'                            , 'Y'),
        (1721 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1722 , '', '', 'Custom'      , 'Warehouse'   , 'Pallet Build'                            , 'Y'),
        (1723 , '', '', 'Standard'    , 'Warehouse'   , 'Pallet Build'                            , 'Y'),
        (1730 , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1740 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1741 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1742 , '', '', 'Standard'    , 'Outbound'    , 'Pack and hold'                           , 'Y'),
        (1746 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1748 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1750 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1751 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1753 , '', '', 'Standard'    , 'Outbound'    , 'Loading'                                 , 'Y'),
        (1754 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1756 , '', '', 'Standard'    , 'Overall'     , 'Task Manager'                            , 'Y'),
        (1757 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1758 , '', '', 'Retired'     , 'Outbound'    , 'Picking'                                 , 'N'),
        (1759 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1760 , '', '', 'Retired'     , 'Outbound'    , 'Picking'                                 , 'N'),
        (1762 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1763 , '', '', 'Standard'    , 'Warehouse'   , 'Task Manager'                            , 'Y'),
        (1764 , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (1765 , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (1766 , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (1767 , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (1768 , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (1769 , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (1770 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1774 , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (1775 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1776 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1777 , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1778 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1780 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1781 , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (1783 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1786 , '', '', 'Standard'    , 'Overall'     , 'Maintenance'                             , 'Y'),
        (1787 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1789 , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (1790 , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (1791 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1792 , '', '', 'Standard'    , 'Warehouse'   , 'Label Printing'                          , 'Y'),
        (1794 , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (1795 , '', '', 'Standard'    , 'Warehouse'   , 'Cycle Count'                             , 'Y'),
        (1796 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1797 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1798 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1799 , '', '', 'Custom'      , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1801 , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1802 , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1804 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1805 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1806 , '', '', 'Retired'     , 'Outbound'    , 'Picking'                                 , 'N'),
        (1807 , '', '', 'Custom'      , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1808 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1809 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1810 , '', '', 'Custom'      , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1811 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1812 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1813 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1814 , '', '', 'Standard'    , 'Overall'     , 'Task Manager'                            , 'Y'),
        (1815 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1816 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1819 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1820 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1821 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1822 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1823 , '', '', 'Standard'    , 'Inbound'     , 'Receive'                                 , 'Y'),
        (1825 , '', '', 'Standard'    , 'Inbound'     , 'Sorting'                                 , 'Y'),
        (1826 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1827 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1828 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1829 , '', '', 'Standard'    , 'Inbound'     , 'Sorting'                                 , 'Y'),
        (1830 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1832 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1834 , '', '', 'Custom'      , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (1835 , '', '', 'Custom'      , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (1836 , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (1837 , '', '', 'Standard'    , 'Warehouse'   , 'Sorting'                                 , 'Y'),
        (1838 , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (1839 , '', '', 'Standard'    , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (1840 , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1841 , '', '', 'Standard'    , 'Inbound'     , 'Sorting'                                 , 'Y'),
        (1842 , '', '', 'Standard'    , 'Warehouse'   , 'Replenishment'                           , 'Y'),
        (1843 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1844 , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (1845 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1846 , '', '', 'Standard'    , 'Warehouse'   , 'Inquiry'                                 , 'Y'),
        (1847 , '', '', 'Standard'    , 'Warehouse'   , 'Move'                                    , 'Y'),
        (1848 , '', '', 'Standard'    , 'Warehouse'   , 'Audit'                                   , 'Y'),
        (1849 , '', '', 'Standard'    , 'Inbound'     , 'Putaway'                                 , 'Y'),
        (1850 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1851 , '', '', 'Custom'      , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (1852 , '', '', 'Standard'    , 'Inbound'     , 'Return Unloading'                        , 'Y'),
        (1853 , '', '', 'Custom'      , 'Warehouse'   , 'Data capture'                            , 'Y'),
        (1854 , '', '', 'Retired'    , 'Outbound'     , 'Picking'                                 , 'N'),
        (1855 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1856 , '', '', 'Standard'    , 'Outbound'    , 'MBOL'                                    , 'Y'),
        (1857 , '', '', 'Standard'    , 'Outbound'    , 'Put To Light'                            , 'Y'),
        (1858 , '', '', 'Standard'    , 'Inbound'     , 'Pallet build'                            , 'Y'),
        (1862 , '', '', 'Standard'    , 'Outbound'    , 'MBOL'                                    , 'Y'),
        (1863 , '', '', 'Standard'    , 'Outbound'    , 'MBOL'                                    , 'Y'),
        (1864 , '', '', 'Standard'    , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1865 , '', '', 'Standard'    , 'Inbound'     , 'Sorting'                                 , 'Y'),
        (1867 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1868 , '', '', 'Standard'    , 'Outbound'    , 'Pack And Pick'                           , 'Y'),
        (1869 , '', '', 'Custom'      , 'Inbound'     , 'Temperature Capture'                     , 'Y'),
        (1870 , '', '', 'Custom'      , 'Outbound'    , 'Temperature Capture'                     , 'Y'),
        (1871 , '', '', 'Custom'      , 'Inbound'     , 'Putaway'                                  , 'Y'),
        (1873 , '', '', 'Custom'      , 'Kit'         , 'Kitting'                                 , 'Y'),
        (1875 , '', '', 'Custom'      , 'Outbound'    , 'Picking'                                 , 'Y'),
        (1877 , '', '', 'Custom'      , 'Kit'         , 'Kitting'                                 , 'Y'),
        (1874 , '', '', 'Custom'      , 'Inbound'     , 'Sorting'                                 , 'Y')
    END TRY
    BEGIn CATCH
        PRINT 'Error inserting into RDTFunctionCategory: ' + ERROR_MESSAGE()
    END CATCH
END
GO
