CREATE TABLE [RDT].[RDTGSICartonLabel_XML]
(
[SeqNo] [int] NOT NULL IDENTITY(1, 1),
[LineText] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPID] [int] NULL,
[Adddate] [datetime] NOT NULL CONSTRAINT [DF_RDTGSICartonLabel_XML_Adddate] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [RDT].[RDTGSICartonLabel_XML] ADD CONSTRAINT [PKGSI_XML] PRIMARY KEY CLUSTERED ([SeqNo]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_GSI_SPID] ON [RDT].[RDTGSICartonLabel_XML] ([SPID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [RDT].[RDTGSICartonLabel_XML] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[RDTGSICartonLabel_XML] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[RDTGSICartonLabel_XML] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[RDTGSICartonLabel_XML] TO [NSQL]
GO
