CREATE TABLE [RDT].[RDTMESSAGE]
(
[SeqNo] [int] NOT NULL IDENTITY(1, 1),
[Mobile] [int] NOT NULL,
[Message] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MessageOut] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddDate] [datetime] NULL CONSTRAINT [DF_RDTMESSAGE_AddDate] DEFAULT (getdate()),
[InFunc] [int] NULL,
[InScn] [int] NULL,
[InStep] [int] NULL,
[TrafficCop] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchiveCop] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashValue] [tinyint] NOT NULL CONSTRAINT [DF_RDTMessage_HashValue] DEFAULT (abs(checksum(newid())%(256)))
) ON [PRIMARY]
GO
ALTER TABLE [RDT].[RDTMESSAGE] ADD CONSTRAINT [PKRDTMESSAGE] PRIMARY KEY NONCLUSTERED ([SeqNo]) WITH (FILLFACTOR=80, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [IX_RDTMessage_HashValue] ON [RDT].[RDTMESSAGE] ([HashValue], [SeqNo]) ON [PRIMARY]
GO
GRANT DELETE ON  [RDT].[RDTMESSAGE] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[RDTMESSAGE] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[RDTMESSAGE] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[RDTMESSAGE] TO [NSQL]
GO
