CREATE TABLE [RDT].[RDTPPA_DELLOG]
(
[Rowref] [int] NOT NULL IDENTITY(1, 1),
[RowRefSource] [int] NOT NULL,
[Status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTPPA_DELLOG_Status] DEFAULT ('0'),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_RDTPPA_DELLOG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTPPA_DELLOG_AddWho] DEFAULT (suser_sname()),
[ArchiveCop] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [RDT].[RDTPPA_DELLOG] ADD CONSTRAINT [PK__RDTPPA_D__78C97797775213FE] PRIMARY KEY CLUSTERED ([Rowref]) ON [PRIMARY]
GO
GRANT DELETE ON  [RDT].[RDTPPA_DELLOG] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[RDTPPA_DELLOG] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[RDTPPA_DELLOG] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[RDTPPA_DELLOG] TO [NSQL]
GO
