CREATE TABLE [RDT].[RDTSessionData]
(
[Mobile] [int] NOT NULL,
[XML] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [RDT].[RDTSessionData] ADD CONSTRAINT [PK_RDTSessionData] PRIMARY KEY CLUSTERED ([Mobile]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [RDT].[RDTSessionData] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[RDTSessionData] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[RDTSessionData] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[RDTSessionData] TO [NSQL]
GO
