
IF NOT EXISTS (SELECT 1
FROM sys.tables
WHERE name = 'RDTTempUCC' AND type = 'U')
BEGIN
   CREATE TABLE [RDT].[RDTTempUCC]
   (
   [RowRef] [int] NOT NULL IDENTITY(1, 1),
   [TaskType] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
   [PickSlipNo] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_PickSlipNo] DEFAULT (''),
   [StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
   [UCCNo] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
   [SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
   [LOT] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
   [LOC] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
   [ID] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
   [Lottable01] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable01] DEFAULT (''),
   [Lottable02] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable02] DEFAULT (''),
   [Lottable03] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable03] DEFAULT (''),
   [Lottable04] [datetime] NULL,
   [Lottable05] [datetime] NULL,
   [AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_AddWho] DEFAULT (suser_sname()),
   [AddDate] [datetime] NOT NULL CONSTRAINT [DF_RDTTempUCC_AddDate] DEFAULT (getdate()),
   [Lottable06] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable06] DEFAULT (''),
   [Lottable07] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable07] DEFAULT (''),
   [Lottable08] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable08] DEFAULT (''),
   [Lottable09] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable09] DEFAULT (''),
   [Lottable10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable10] DEFAULT (''),
   [Lottable11] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable11] DEFAULT (''),
   [Lottable12] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_Lottable12] DEFAULT (''),
   [Lottable13] [datetime] NULL,
   [Lottable14] [datetime] NULL,
   [Lottable15] [datetime] NULL,

   [UCCLottable01] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable01] DEFAULT (''),
   [UCCLottable02] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable02] DEFAULT (''),
   [UCCLottable03] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable03] DEFAULT (''),
   [UCCLottable04] [datetime] NULL,
   [UCCLottable05] [datetime] NULL,
   [UCCLottable06] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable06] DEFAULT (''),
   [UCCLottable07] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable07] DEFAULT (''),
   [UCCLottable08] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable08] DEFAULT (''),
   [UCCLottable09] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable09] DEFAULT (''),
   [UCCLottable10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable10] DEFAULT (''),
   [UCCLottable11] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable11] DEFAULT (''),
   [UCCLottable12] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_RDTTempUCC_UCCLottable12] DEFAULT (''),
   [UCCLottable13] [datetime] NULL,
   [UCCLottable14] [datetime] NULL,
   [UCCLottable15] [datetime] NULL
   ) ON [PRIMARY]

   ALTER TABLE [RDT].[RDTTempUCC] ADD CONSTRAINT [PKRDTTempUCC] PRIMARY KEY CLUSTERED ([RowRef]) WITH (FILLFACTOR=90) ON [PRIMARY]

   CREATE NONCLUSTERED INDEX [IDX_RDTTempUCC_TaskType_StorerKey_SKU_LOC] ON [RDT].[RDTTempUCC] ([TaskType], [StorerKey], [SKU], [LOC]) WITH (FILLFACTOR=90) ON [PRIMARY]
   CREATE NONCLUSTERED INDEX [IDX_RDTTempUCC_UCCNo] ON [RDT].[RDTTempUCC] ([UCCNo]) WITH (FILLFACTOR=90) ON [PRIMARY]

   GRANT DELETE ON  [RDT].[RDTTempUCC] TO [NSQL]
   GRANT INSERT ON  [RDT].[RDTTempUCC] TO [NSQL]
   GRANT SELECT ON  [RDT].[RDTTempUCC] TO [NSQL]
   GRANT UPDATE ON  [RDT].[RDTTempUCC] TO [NSQL]
END
ELSE
BEGIN
   --FCR-2519
   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable01')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable01 NVARCHAR(18)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable01 DEFAULT('')
   
   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable02')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable02 NVARCHAR(18)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable02 DEFAULT('')
   
   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable03')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable03 NVARCHAR(18)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable03 DEFAULT('')

   IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable04')
      ALTER TABLE rdt.RDTTempUCC ADD UCCLottable04 DATETIME NULL
   
   IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable05')
      ALTER TABLE rdt.RDTTempUCC ADD UCCLottable05 DATETIME NULL

   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable06')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable06 NVARCHAR(30)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable06 DEFAULT('')
   
   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable07')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable07 NVARCHAR(30)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable07 DEFAULT('')
   
   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable08')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable08 NVARCHAR(30)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable08 DEFAULT('')

   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable09')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable09 NVARCHAR(30)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable09 DEFAULT('')
   
   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable10')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable10 NVARCHAR(30)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable10 DEFAULT('')
   
   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable11')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable11 NVARCHAR(30)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable11 DEFAULT('')
   
   IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable12')
      ALTER TABLE RDT.RDTTempUCC ADD UCCLottable12 NVARCHAR(30)  NULL CONSTRAINT DF_RDTTempUCC_UCCLottable12 DEFAULT('')

   IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable13')
      ALTER TABLE rdt.RDTTempUCC ADD UCCLottable13 DATETIME NULL

   IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable14')
      ALTER TABLE rdt.RDTTempUCC ADD UCCLottable14 DATETIME NULL

   IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RDTTempUCC' AND COLUMN_NAME = 'UCCLottable15')
      ALTER TABLE rdt.RDTTempUCC ADD UCCLottable15 DATETIME NULL
END
GO

