CREATE TABLE [RDT].[RDTTRace]
(
[Mobile] [int] NOT NULL,
[InFunc] [int] NOT NULL CONSTRAINT [DF_RDTTRace_InFunc] DEFAULT ((0)),
[InScn] [int] NOT NULL CONSTRAINT [DF_RDTTRace_InScn] DEFAULT ((0)),
[InStep] [int] NOT NULL CONSTRAINT [DF_RDTTRace_InStep] DEFAULT ((0)),
[OutFunc] [int] NOT NULL CONSTRAINT [DF_RDTTRace_OutFunc] DEFAULT ((0)),
[OutScn] [int] NOT NULL CONSTRAINT [DF_RDTTRace_OutScn] DEFAULT ((0)),
[OutStep] [int] NOT NULL CONSTRAINT [DF_RDTTRace_OutStep] DEFAULT ((0)),
[Usr] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_RDTTRace_Usr] DEFAULT (suser_sname()),
[StartTime] [datetime] NOT NULL CONSTRAINT [DF_RDTTRace_StartTime] DEFAULT (getdate()),
[EndTime] [datetime] NOT NULL CONSTRAINT [DF_RDTTRace_EndTime] DEFAULT (getdate()),
[TimeTaken] [int] NULL CONSTRAINT [DF_RDTTRace_TimeTaken] DEFAULT ((0)),
[ROWREF] [int] NOT NULL IDENTITY(1, 1),
[ScnTime] [int] NULL CONSTRAINT [DF_RDTTRace_ScnTime] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [RDT].[RDTTRace] ADD CONSTRAINT [PKRDTTRace] PRIMARY KEY CLUSTERED ([ROWREF]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT SELECT ON  [RDT].[RDTTRace] TO [JReportRole]
GO
GRANT DELETE ON  [RDT].[RDTTRace] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[RDTTRace] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[RDTTRace] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[RDTTRace] TO [NSQL]
GO
