CREATE TABLE [RDT].[RDTXML]
(
[Mobile] [int] NOT NULL,
[Type] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[XML] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [RDT].[RDTXML] ADD CONSTRAINT [PK_RDTXML] PRIMARY KEY CLUSTERED ([Mobile], [Type]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [RDT].[RDTXML] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[RDTXML] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[RDTXML] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[RDTXML] TO [NSQL]
GO
