CREATE TABLE [RDT].[RDTXML_Root]
(
[mobile] [int] NOT NULL,
[focus] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [RDT].[RDTXML_Root] ADD CONSTRAINT [PK_tordt] PRIMARY KEY CLUSTERED ([mobile]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [RDT].[RDTXML_Root] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[RDTXML_Root] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[RDTXML_Root] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[RDTXML_Root] TO [NSQL]
GO
