SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
  
  
    
CREATE VIEW [RDT].[V_RDTPPA]        
AS        
SELECT *      
FROM [RDT].[RDTPPA]  (NOLOCK)    
    
GO
GRANT DELETE ON  [RDT].[V_RDTPPA] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_RDTPPA] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_RDTPPA] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_RDTPPA] TO [NSQL]
GO
