SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [RDT].[V_rdtPTLStationLog] 
AS 
SELECT *
FROM [RDT].[rdtPTLStationLog] (NOLOCK) 
GO
GRANT DELETE ON  [RDT].[V_rdtPTLStationLog] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_rdtPTLStationLog] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_rdtPTLStationLog] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_rdtPTLStationLog] TO [NSQL]
GO
