SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE VIEW [RDT].[V_rdtCSAudit_Batch] AS
SELECT * FROM RDT.rdtCSAudit_Batch (NOLOCK)

GO
GRANT DELETE ON  [RDT].[V_rdtCSAudit_Batch] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_rdtCSAudit_Batch] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_rdtCSAudit_Batch] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_rdtCSAudit_Batch] TO [NSQL]
GO
