SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [RDT].[V_rdtScanToTruck]
AS Select *
FROM [RDT].[rdtScanToTruck] with (NOLOCK)
GO
GRANT DELETE ON  [RDT].[V_rdtScanToTruck] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_rdtScanToTruck] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_rdtScanToTruck] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_rdtScanToTruck] TO [NSQL]
GO
