SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [RDT].[V_RDTCSAudit_BatchPO] AS
SELECT * FROM RDT.RDTCSAudit_BatchPO (NOLOCK)
GO

GRANT DELETE ON  [RDT].[V_RDTCSAudit_BatchPO] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_RDTCSAudit_BatchPO] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_RDTCSAudit_BatchPO] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_RDTCSAudit_BatchPO] TO [NSQL]
GO
