SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [RDT].[V_rdtCSAudit] AS
   SELECT * FROM rdt.rdtCSAudit (NOLOCK)

GO
GRANT DELETE ON  [RDT].[V_rdtCSAudit] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_rdtCSAudit] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_rdtCSAudit] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_rdtCSAudit] TO [NSQL]
GO
