SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [RDT].[V_rdtPTLStationLog]
AS
SELECT *
FROM [RDT].[rdtPTLStationLog] (NOLOCK)
GO
GRANT DELETE ON  [RDT].[V_rdtPTLStationLog] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_rdtPTLStationLog] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_rdtPTLStationLog] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_rdtPTLStationLog] TO [NSQL]
GO
