SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE VIEW [RDT].[V_rdtFPKLog]      
AS      
SELECT *    
FROM [RDT].[rdtFPKLog]  (NOLOCK)  
  
GO
GRANT DELETE ON  [RDT].[V_rdtFPKLog] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_rdtFPKLog] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_rdtFPKLog] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_rdtFPKLog] TO [NSQL]
GO
