SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [RDT].[V_RDTTrace]
AS
SELECT * FROM RDT.RDTTrace WITH (NOLOCK)
GO
GRANT DELETE ON  [RDT].[V_RDTTrace] TO [NSQL]
GO
GRANT INSERT ON  [RDT].[V_RDTTrace] TO [NSQL]
GO
GRANT SELECT ON  [RDT].[V_RDTTrace] TO [NSQL]
GO
GRANT UPDATE ON  [RDT].[V_RDTTrace] TO [NSQL]
GO
