SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE OR ALTER VIEW [PTL].[V_PTLTran]
AS SELECT *
FROM [PTL].[PTLTran] WITH (NOLOCK)
GO
GRANT DELETE ON  [PTL].[V_PTLTran] TO [NSQL]
GO
GRANT INSERT ON  [PTL].[V_PTLTran] TO [NSQL]
GO
GRANT SELECT ON  [PTL].[V_PTLTran] TO [NSQL]
GO
GRANT UPDATE ON  [PTL].[V_PTLTran] TO [NSQL]
GO
