-- nspItrnAddDepositCheck (range 61831 - 61900)
  
execute rdt.rdtAddMsg 61831, 10, '61831 nsp_GetRight ALLOWOVERALLOCATIONS (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61832, 10, '61832 Insert Trigger On ITRN Failed Because An Attempt To Update StorerKey Failed. (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61833, 10, '61833 Update To Table ITRN Returned Zero Rows Affected. (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61834, 10, '61834 Storerkey is blank or null - not allowed! (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61835, 10, '61835 Insert Trigger On ITRN Failed Because An Attempt To Update SKU Failed. (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61836, 10, '61836 Update To Table ITRN Returned Zero Rows Affected. (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61837, 10, '61837 Default SKU Is Not Allowed And SKU Passed Is Blank! (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61838, 10, '61838 Execute nsp_lotgen Failed (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61839, 10, '61839 Execute nsp_lotlookup Failed (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61840, 10, '61840 Lot Number Is Not Unique Or Does Not Exist In The LOTATTRIBUTE Table! (nspItrnAddMoveCheck)', 'us_english'   
execute rdt.rdtAddMsg 61841, 10, '61841 Lot Number and SKU Passed Do Not Match The Definition In The LOTATTRIBUTE Table! (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61842, 10, '61842 Insert Failed On Table LOT. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61843, 10, '61843 Update Failed On Table LOT. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61844, 10, '61844 Update To Table LOT Returned Zero Rows Affected. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61845, 10, '61845 Lot Table Did Not Return Expected Unique Row In Response To Query. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61846, 10, '61846 Insert Failed On Table ID. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61847, 10, '61847 Update Failed On Table ID. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61848, 10, '61848 Update To Table ID Returned Zero Rows Affected. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61849, 10, '61849 Update Failed On Table ID. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61850, 10, '61850 ID Table Did Not Return Expected Unique Row In Response To Query. (nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61851, 10, '61851 Insert Failed On Table SKUxLOC. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61852, 10, '61852 Update Failed On Table SKUxLOC. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61853, 10, '61853 Update To Table SKUxLOC Returned Zero Rows Affected.(nspItrnAddMoveCheck)', 'us_english'  
execute rdt.rdtAddMsg 61854, 10, '61854 SKUxLOC Table Did Not Return Expected Unique Row In Response To Query. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61855, 10, '61855 Insert Failed On Table LOTxLOCxID. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61856, 10, '61856 Update Failed On TableLOTxLOCxID. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61857, 10, '61857 Update To Table LOTxLOCxID Returned Zero Rows Affected. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61858, 10, '61858 LOTxLOCxID Table Did Not Return Expected Unique Row In Response To Query. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61859, 10, '61859 Update Failed On Table Itrn. (nspItrnAddMoveCheck)', 'us_english'
execute rdt.rdtAddMsg 61859, 10, '61860 Execute nspInventoryHold Failed (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61860, 10, '61861 Update Failed On Table LOT. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61861, 10, '61862 Execute nspItrnAddDWBill Failed (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61862, 10, '61863 nsp_GetRight UPDATE RECEIPTDETAIL TOLOC (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61864, 10, '61864 Update Failed On Table ReceiptDetail. (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61865, 10, '61865 nsp_GetRight ReAllocatePickDetail (nspItrnAddMoveCheck)', 'us_english' 
execute rdt.rdtAddMsg 61866, 10, '61866 Execute ispReAllocPickDetail Failed (nspItrnAddMoveCheck)', 'us_english' 



