-- nspItrnAddAdjustmentCheck (range 61961 - 62000)
  
execute rdt.rdtAddMsg 61961, 10, '61961 nsp_GetRight ALLOWOVERALLOCATIONS (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61962, 10, '61962 Storerkey is blank or null - not allowed! (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61963, 10, '61963 Insert Trigger On ITRN Failed Because An Attempt To Update StorerKey Failed. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61964, 10, '61964 Update To Table ITRN Returned Zero Rows Affected. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61965, 10, '61965 Storerkey is blank or null - not allowed! (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61966, 10, '61966 Insert Trigger On ITRN Failed Because An Attempt To Update SKU Failed. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61967, 10, '61967 Update To Table ITRN Returned Zero Rows Affected. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61968, 10, '61968 Default SKU Is Not Allowed And SKU Passed Is Blank! (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61969, 10, '61969 Lot Number Does Not Exist In The LOTATTRIBUTE Table!(nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61970, 10, '61970 Execute nsp_lotlookup Failed (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61971, 10, '61971 Lot Number Is Not Unique Or Does Not Exist In The LOTATTRIBUTE Table!(nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61972, 10, '61972 Lot Number and SKU Passed Do Not Match The Definition In The LOTATTRIBUTE Table! (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61973, 10, '61973 Insert Failed On Table Itrn. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61974, 10, '61974 Update Failed On Table LOT. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61975, 10, '61975 Update To Table LOT Returned Zero Rows Affected. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61976, 10, '61976 Lot Table Did Not Return Expected Unique Row In Response To Query. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61977, 10, '61977 Insert Failed On Table ID. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61978, 10, '61978 Update Failed On Table ID. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61979, 10, '61979 Update To Table ID Returned Zero Rows Affected. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61980, 10, '61980 ID Table Did Not Return Expected Unique Row In Response To Query. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61981, 10, '61981 Update Failed On Table ID. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61982, 10, '61982 Insert Failed On Table SKUxLOC. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61983, 10, '61983 Update Failed On Table SKUxLOC. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61984, 10, '61984 Update To Table SKUxLOC Returned Zero Rows Affected. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61985, 10, '61985 SKUxLOC Table Did Not Return Expected Unique Row In Response To Query. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61986, 10, '61986 Insert Failed On Table LOTxLOCxID. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61987, 10, '61987 Update Failed On Table LOTxLOCxID. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61988, 10, '61988 Update To Table LOTxLOCxID Returned Zero Rows Affected. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61989, 10, '61989 LOTxLOCxID Table Did Not Return Expected Unique Row In Response To Query. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61990, 10, '61990 Update Failed on Table LOT. (nspItrnAddAdjustmentCheck)', 'us_english'
execute rdt.rdtAddMsg 61991, 10, '61991 Update Failed on Table Itrn. (nspItrnAddAdjustmentCheck)', 'us_english'
