IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[fnc_LTRIM]')  AND type in (N'FN', N'IF', N'TF', N'FS', N'FT')) 
DROP FUNCTION [dbo].[fnc_LTRIM]
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE FUNCTION [dbo].[fnc_LTRIM] (@cString NVARCHAR(max))  
RETURNS NVARCHAR(max) AS  
BEGIN 
   RETURN CASE WHEN LTRIM(@cString) = '' THEN NULL ELSE LTRIM(@cString) END
END
GO
GRANT EXECUTE ON [dbo].[fnc_LTRIM] TO nSQL 
GO
