CREATE ROLE [NSQL]
AUTHORIZATION [dbo]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\AjayKumarPal]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\AlexHoWY]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\BehTsuiNee]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\ChuanJingOoi]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\DUWMSTeam]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\GanHweeLing]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\GTWMSProject]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\INDWMSTeam]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\JackGongXY]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\JijoGeorge]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\VivekDubey]
GO
ALTER ROLE [NSQL] ADD MEMBER [ALPHA\YingShanWong]
GO
ALTER ROLE [NSQL] ADD MEMBER [ay]
GO
ALTER ROLE [NSQL] ADD MEMBER [cgregory]
GO
ALTER ROLE [NSQL] ADD MEMBER [DidHuiUng]
GO
ALTER ROLE [NSQL] ADD MEMBER [dts]
GO
ALTER ROLE [NSQL] ADD MEMBER [iml]
GO
ALTER ROLE [NSQL] ADD MEMBER [imlwebuser1]
GO
ALTER ROLE [NSQL] ADD MEMBER [james]
GO
ALTER ROLE [NSQL] ADD MEMBER [LITUser]
GO
ALTER ROLE [NSQL] ADD MEMBER [nazrul]
GO
ALTER ROLE [NSQL] ADD MEMBER [omswebuser1]
GO
ALTER ROLE [NSQL] ADD MEMBER [omswebuser2]
GO
ALTER ROLE [NSQL] ADD MEMBER [omswebuser3]
GO
ALTER ROLE [NSQL] ADD MEMBER [RDT]
GO
ALTER ROLE [NSQL] ADD MEMBER [RESET]
GO
ALTER ROLE [NSQL] ADD MEMBER [WMConnect]
GO
ALTER ROLE [NSQL] ADD MEMBER [wmsgt]
GO
