

---    ALTER SEQUENCE ORDBATCHNO RESTART WITH 425 ;  

--   SELECT NEXT VALUE FOR dbo.[ORDBATCHNO]   

--  SELECT * FROM dbo.NCOUNTER WHERE keyname = 'ORDBATCHNO'


CREATE SEQUENCE dbo.[ORDBATCHNO] 
 AS [BIGINT]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999
 CYCLE
 CACHE 100
GO

grant Update on dbo.[ORDBATCHNO]  to NSQL


