 

 
---    ALTER SEQUENCE PREOPRUN RESTART WITH 1759347 ;  

--   SELECT NEXT VALUE FOR dbo.[PREOPRUN]  

--   SELECT * from ncounter (NOLOCK) WHERE keyname = 'PREOPRUN'

CREATE SEQUENCE dbo.[PREOPRUN] 
 AS [BIGINT]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 9999989999
 CYCLE
 CACHE 50
GO

grant Update on dbo.[PREOPRUN]  to NSQL

/*
SELECT current_value, * FROM sys.sequences WHERE name = 'PREOPRUN' ;


SELECT TOP 100 * FROM [PREOPRUN] Order by adddate
 


*/
