-- PVHLBLNO

--  SELECT  top 10 * FROM Ncounter where keyname  = 'PVHLBLNO'
 

IF NOT EXISTS ( SELECT 1 FROM sys.sequences WHERE name = 'PVHLBLNO' ) 
AND NOT EXISTS ( SELECT 1 FROM Ncounter where keyname  = 'PVHLBLNO' ) 
BEGIN
CREATE SEQUENCE dbo.[PVHLBLNO] 
 AS [BIGINT]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999989999
 CYCLE
 CACHE 50
 
grant Update on dbo.[PVHLBLNO]  to NSQL

END
GO
 


/*

 SELECT NEXT VALUE FOR dbo.[PVHLBLNO] 

ALTER SEQUENCE PVHLBLNO INCREMENT BY 30173935;
 
 SELECT NEXT VALUE FOR dbo.[PVHLBLNO] 
 
ALTER SEQUENCE PVHLBLNO  INCREMENT BY 1;

*/
/*
SELECT current_value, * FROM sys.sequences WHERE name = 'PVHLBLNO' ;
 
*/
