 
---    ALTER SEQUENCE REPLENISHGROUP RESTART WITH 1349 ;  

--   SELECT NEXT VALUE FOR dbo.[REPLENISHGROUP]  

--   SELECT * from ncounter (NOLOCK) WHERE keyname = 'REPLENISHGROUP'

CREATE SEQUENCE dbo.[REPLENISHGROUP] 
 AS [BIGINT]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 9999989999
 CYCLE
 CACHE 50
GO

grant Update on dbo.[REPLENISHGROUP]  to NSQL

/*
SELECT current_value, * FROM sys.sequences WHERE name = 'REPLENISHGROUP' ;


SELECT TOP 100 * FROM REPLENISH Order by adddate
 


*/