 
 /*  reset seq to current value
 
 SELECT NEXT VALUE FOR dbo.[REPLENGROUP] 

ALTER SEQUENCE REPLENGROUP INCREMENT BY 10000;
 
 SELECT NEXT VALUE FOR dbo.[REPLENGROUP] 
 
ALTER SEQUENCE REPLENGROUP INCREMENT BY 1;


*/ 

--   SELECT NEXT VALUE FOR dbo.[REPLENGROUP]  

--   SELECT * from ncounter (NOLOCK) WHERE keyname = 'REPLENGROUP'


CREATE SEQUENCE dbo.REPLENGROUP 
 AS [BIGINT]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 9999989999
 CYCLE
 CACHE 50
GO

grant Update on dbo.REPLENGROUP  to NSQL

/*
SELECT current_value, * FROM sys.sequences WHERE name = 'REPLENGROUP' ;

 


*/
