-- UCCKey_IKEA

--  SELECT  top 10 * FROM UCCCounter where Storerkey  = 'IKEA'
  
 
IF NOT EXISTS ( SELECT 1 FROM sys.sequences WHERE name = 'UCCKey_IKEA' ) 
AND NOT EXISTS ( SELECT 1 FROM UCCCounter WHERE keyname  = 'UCCKey_IKEA' ) 
BEGIN
CREATE SEQUENCE dbo.[UCCKey_IKEA] 
 AS [BIGINT]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999 
 CYCLE
 CACHE 50
 GRANT UPDATE ON dbo.[UCCKey_IKEA] TO NSQL 

END
GO
 


/*

 SELECT NEXT VALUE FOR dbo.[UCCKey_IKEA] 

ALTER SEQUENCE UCCKey_IKEA INCREMENT BY 4394;
 
 SELECT NEXT VALUE FOR dbo.[UCCKey_IKEA] 
 
ALTER SEQUENCE UCCKey_IKEA  INCREMENT BY 1;

*/
/*
SELECT current_value, * FROM sys.sequences WHERE name = 'UCCKey_IKEA' ;
 
*/
