CREATE TABLE [WM].[WMS_TABLE_EVENT_CONFIG]
(
[RowRefNo] [bigint] NOT NULL IDENTITY(1, 1),
[StorerKey] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TABLE_EVENT_CONFIG_StorerKey] DEFAULT ('ALL'),
[Module] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TABLE_EVENT_CONFIG_Module] DEFAULT (''),
[TableName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TABLE_EVENT_CONFIG_TableName] DEFAULT (''),
[Event] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TABLE_EVENT_CONFIG_Event] DEFAULT (''),
[StepNo] [int] NOT NULL CONSTRAINT [DF_WMS_TABLE_EVENT_CONFIG_StepNo] DEFAULT ((1)),
[StoredProcedure] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TABLE_EVENT_CONFIG_StoredProcedure] DEFAULT (''),
[AddDate] [datetime] NOT NULL CONSTRAINT [DF_WMS_TABLE_EVENT_CONFIG_AddDate] DEFAULT (getdate()),
[AddWho] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_TABLE_EVENT_CONFIG_AddWho] DEFAULT (suser_sname())
) ON [PRIMARY]
GO
ALTER TABLE [WM].[WMS_TABLE_EVENT_CONFIG] ADD CONSTRAINT [PK_WMS_TABLE_EVENT_CONFIG] PRIMARY KEY CLUSTERED ([RowRefNo]) ON [PRIMARY]
GO
GRANT DELETE ON  [WM].[WMS_TABLE_EVENT_CONFIG] TO [NSQL]
GO
GRANT INSERT ON  [WM].[WMS_TABLE_EVENT_CONFIG] TO [NSQL]
GO
GRANT SELECT ON  [WM].[WMS_TABLE_EVENT_CONFIG] TO [NSQL]
GO
GRANT UPDATE ON  [WM].[WMS_TABLE_EVENT_CONFIG] TO [NSQL]
GO
