CREATE TABLE [WM].[WMS_USER_CREATION_STATUS]
(
[USER_NAME] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USER_TYPE] [int] NOT NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_USER_TYPE] DEFAULT ((1)),
[LDAP_DOMAIN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_LDAP_DOMAIN] DEFAULT (''),
[STATUS] [int] NOT NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_STATUS] DEFAULT ((1)),
[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_CREATED_DATE] DEFAULT (suser_sname()),
[UPDATED_DATE] [datetime] NULL,
[WMS_USER_NAME] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_WMS_USER_NAME] DEFAULT (''),
[WMS_LOGIN_SYNC] [int] NOT NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_WMS_LOGIN_SYNC] DEFAULT ((0)),
[WMS_LOGIN_CREATED_DATE] [datetime] NULL,
[SYNC_ERROR_NO] [int] NOT NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_SYNC_ERROR_NO] DEFAULT ((0)),
[SYNC_ERROR_MESSAGE] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_SYNC_ERROR_MESSAGE] DEFAULT (''),
[SYNC_LAST_RUN_DATE] [datetime] NULL,
[SYNC_NO_OF_TRY] [int] NOT NULL CONSTRAINT [DF_WMS_USER_CREATION_STATUS_SYNC_NO_OF_TRY] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [WM].[WMS_USER_CREATION_STATUS] ADD CONSTRAINT [PK_WMS_USER_CREATION_STATUS] PRIMARY KEY CLUSTERED ([USER_NAME]) ON [PRIMARY]
GO
GRANT DELETE ON  [WM].[WMS_USER_CREATION_STATUS] TO [NSQL]
GO
GRANT INSERT ON  [WM].[WMS_USER_CREATION_STATUS] TO [NSQL]
GO
GRANT SELECT ON  [WM].[WMS_USER_CREATION_STATUS] TO [NSQL]
GO
GRANT UPDATE ON  [WM].[WMS_USER_CREATION_STATUS] TO [NSQL]
GO
