IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[V_ORDERDETAIL_SUM]')) 
   DROP VIEW [dbo].[V_ORDERDETAIL_SUM]
GO 

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE VIEW DBO.V_ORDERDETAIL_SUM
AS SELECT ORDERS.Orderkey,
ORDERS.StorerKey,
TotalOrderQty = SUM(Orderdetail.Openqty),
NoOrderLine = COUNT(1) 
FROM ORDERS WITH (NOLOCK)
LEFT JOIN ORDERDETAIL WITH (NOLOCK) ON ORDERDETAIL.orderkey = ORDERS.orderkey
GROUP BY ORDERS.Orderkey,
ORDERS.StorerKey
GO
GRANT SELECT ON [dbo].[V_ORDERDETAIL_SUM] TO NSQL
GO
