IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[V_WMS_INVHOLD_ID]')) 
   DROP VIEW [dbo].[V_WMS_INVHOLD_ID]
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE VIEW V_WMS_INVHOLD_ID AS

SELECT ID 
     --, Storerkey = SUBSTRING( MAX(RIGHT('0000000000' + CONVERT(VARCHAR(10),qty),10) + CONVERT(VARCHAR(23), EditDate, 121) + Storerkey),34, LEN(MAX(Storerkey))) --INC1100039
     , Storerkey = STUFF(MAX(RIGHT('0000000000' + CONVERT(VARCHAR(10),qty),10) + CONVERT(VARCHAR(23), EditDate, 121) + Storerkey),1,33,'')                        --INC1100039
FROM LOTXLOCXID WITH (NOLOCK)
WHERE ID <> ''
GROUP BY ID

GO

Grant SELECT ON [V_OTM_Table_Mapping] to NSQL
GO

