CREATE TABLE [BI].[OrderSum]
(
[OrderKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StorerKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExternOrderKey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DeliveryDate] [date] NOT NULL,
[ConsigneeKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C_City] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Type] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OrderGroup] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AddDate] [smalldatetime] NOT NULL,
[EditDate] [smalldatetime] NOT NULL,
[ModifyDate] [smalldatetime] NOT NULL CONSTRAINT [DF_OrderSum_ModifyDate] DEFAULT (getdate()),
[AllocDate] [smalldatetime] NULL,
[PickDate] [smalldatetime] NULL,
[ShipDate] [smalldatetime] NULL,
[CancDate] [smalldatetime] NULL,
[Lines] [bigint] NOT NULL,
[Units] [bigint] NOT NULL,
[PickDet_Lines] [bigint] NOT NULL,
[Orders_Open] [bigint] NOT NULL,
[Lines_Open] [bigint] NOT NULL,
[Units_Open] [bigint] NOT NULL,
[Orders_ALLOC] [bigint] NOT NULL,
[Lines_ALLOC] [bigint] NOT NULL,
[Units_ALLOC] [bigint] NOT NULL,
[Orders_Pick_Packed] [bigint] NOT NULL,
[Lines_Pick_Packed] [bigint] NOT NULL,
[Units_Pick_Packed] [bigint] NOT NULL,
[Orders_Shipped] [bigint] NOT NULL,
[Lines_Shipped] [bigint] NOT NULL,
[Units_Shipped] [bigint] NOT NULL,
[Orders_Cancelled] [bigint] NOT NULL,
[Lines_Cancelled] [bigint] NOT NULL,
[Units_Cancelled] [bigint] NOT NULL,
[PickDetails_Inserted] [bigint] NOT NULL,
[Orders_OverRun] [bigint] NULL,
[Orders_PendBuildLoad] [int] NOT NULL,
[MBOL_NotValid] [int] NOT NULL,
[MBOLKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoadKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Facility] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ShipperKey] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DocType] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TrackingNo] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ECOM_PRESALE_FLAG] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PreSale] [bit] NOT NULL,
[ECOM_SINGLE_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UserDefine01] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UserDefine02] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UserDefine03] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [BI].[OrderSum] ADD CONSTRAINT [PK_OrderSum] PRIMARY KEY CLUSTERED ([OrderKey]) WITH (FILLFACTOR=80, PAD_INDEX=ON) ON [PRIMARY]
GO
