SELECT * FROM [LFL_SECURE_UAT].dbo.LF_CORE_COUNTRY (NOLOCK)
WHERE Country_Code like '%CN%' or COUNTRY_CODE like '%CHN'

SELECT * FROM GTAPPs.dbo.CODELKUP (NOLOCK) 

SELECT * FROM GTAPPs.dbo.LWMS_WebApiConfig (NOLOCK) 

USE GTAPPS 
INSERT INTO dbo.LWMS_WebApiConfig (OperationType, TargetDB, TargetSchema, WSPostingSP01, SPTJSON, SPTXML, [Descr], ResponseOriContent)
SELECT 'SCE_ConvertCountryCode', 'GTAPPS', 'dbo', 'isp_SCE_ConvertCountryCode', 'Y', 'N', 'Convert SCE 3-char country code to 2-char', 1

USE GTAPPS
--ROW
INSERT INTO dbo.CODELKUP (LISTNAME, Code, Short)
SELECT 
'CTRY_CODE','TWN', 'TW'
UNION ALL SELECT 'CTRY_CODE','HKG', 'HK'
UNION ALL SELECT 'CTRY_CODE','KOR', 'KR'
UNION ALL SELECT 'CTRY_CODE','PHL', 'PH'
UNION ALL SELECT 'CTRY_CODE','THA', 'TH'
UNION ALL SELECT 'CTRY_CODE','JPN', 'JP'
UNION ALL SELECT 'CTRY_CODE','SGP', 'SG'
UNION ALL SELECT 'CTRY_CODE','IDN', 'ID'
UNION ALL SELECT 'CTRY_CODE','IND', 'IN'
UNION ALL SELECT 'CTRY_CODE','MYS', 'MY'
UNION ALL SELECT 'CTRY_CODE','VNM', 'VN'
UNION ALL SELECT 'CTRY_CODE','AUS', 'AU'
UNION ALL SELECT 'CTRY_CODE','DUB', 'DU'

--CN
INSERT INTO dbo.CODELKUP (LISTNAME, Code, Short)
SELECT 
'CTRY_CODE', 'CHN' , 'CN'
UNION ALL SELECT 'CTRY_CODE', 'CN_HM1' , 'CN_HNM'
UNION ALL SELECT 'CTRY_CODE', 'CN_HM2' , 'CN_HNM'
UNION ALL SELECT 'CTRY_CODE', 'CN_HM'  , 'CN_HNM'
UNION ALL SELECT 'CTRY_CODE', 'CN_NKE' , 'CN_NKE'
UNION ALL SELECT 'CTRY_CODE', 'CN_UA'  , 'CN_UA'
UNION ALL SELECT 'CTRY_CODE', 'CN_SKE' , 'CN_SKE'
UNION ALL SELECT 'CTRY_CODE', 'CN_SEP' , 'CN_SEP'

