IF EXISTS (SELECT name FROM dbo.sysobjects WHERE name = 'nspAL01_7D' AND type = 'P')
   DROP PROC nspAL01_7D
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

CREATE  PROC nspAL01_7D
@c_lot NVARCHAR(10) ,
@c_uom NVARCHAR(10) ,
@c_HostWHCode NVARCHAR(10),
@c_Facility NVARCHAR(5),
@n_uombase int ,
@n_qtylefttofulfill int
AS
BEGIN
   SET NOCOUNT ON 
    
   
DECLARE  CURSOR_CANDIDATES  CURSOR FAST_FORWARD READ_ONLY
FOR SELECT LOTxLOCxID.LOC,LOTxLOCxID.ID,
QTYAVAILABLE = (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED), '1'
FROM LOTxLOCxID (NOLOCK),LOC (NOLOCK),ID (NOLOCK), LOT(NOLOCK)
WHERE LOTxLOCxID.Lot = @c_lot
AND LOTxLOCxID.Loc = LOC.LOC
AND LOTxLOCxID.Id = ID.ID
AND LOTXLOCXID.LOT = LOT.LOT --added by ang (SOS131215)
AND LOC.Locationflag <>"HOLD"
AND LOC.Locationflag <> "DAMAGE"
AND LOC.Status <> "HOLD"
AND LOC.Facility = @c_Facility
AND ID.STATUS <> "HOLD"
AND LOT.STATUS <> "HOLD" --added by ang (SOS131215)
ORDER BY loc.locationtype desc ,  LOC.LOC 
END

GO

GRANT EXECUTE ON nspAL01_7D TO NSQL 
GO


