IF EXISTS (SELECT name FROM dbo.sysobjects WHERE name = 'nspALIDS01' AND type = 'P')
   DROP PROC nspALIDS01
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF
GO  

CREATE  PROC    nspALIDS01
@c_lot NVARCHAR(10) ,
@c_uom NVARCHAR(10) ,
@c_HostWHCode NVARCHAR(10),
@c_Facility NVARCHAR(5),
@n_uombase int ,
@n_qtylefttofulfill int,  
@c_OtherParms NVARCHAR(200) = ''
AS
BEGIN
   SET NOCOUNT ON 
    
   
DECLARE  CURSOR_CANDIDATES CURSOR FAST_FORWARD READ_ONLY
FOR SELECT LOTxLOCxID.LOC, LOTxLOCxID.ID,
QTYAVAILABLE = (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED), '1'
FROM LOTxLOCxID (NOLOCK), LOC (NOLOCK), ID (NOLOCK)
WHERE LOTxLOCxID.Lot = @c_lot
AND LOTxLOCxID.Loc = LOC.LOC
AND LOTxLOCxID.ID = ID.ID
AND ID.Status <> "HOLD"
AND LOC.Locationflag <> "HOLD"
AND LOC.Locationflag <> "DAMAGE"
AND (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED) >= @n_uombase
AND LOC.Status <> "HOLD"
AND LOC.Facility = @c_Facility
ORDER BY LOTxLOCxID.LOC
END

GO 
GRANT EXECUTE ON nspALIDS01 TO NSQL 
GO
