if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[nspALSTDE2]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[nspALSTDE2]
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

CREATE PROC    nspALSTDE2
@c_lot NVARCHAR(10) ,
@c_uom NVARCHAR(10) , 
@c_HostWHCode NVARCHAR(10),
@c_Facility NVARCHAR(5),
@n_uombase int ,
@n_qtylefttofulfill int
AS
BEGIN 
   SET NOCOUNT ON 
    
   
DECLARE  CURSOR_CANDIDATES CURSOR FAST_FORWARD READ_ONLY
FOR SELECT LOTxLOCxID.LOC, LOTxLOCxID.ID,
QTYAVAILABLE = (LOTxLOCxID.QTY - LOTxLOCxID.QTYALLOCATED - LOTxLOCxID.QTYPICKED), '1'
FROM LOTxLOCxID (NOLOCK), LOC (NOLOCK), SKUxLOC (NOLOCK) 
WHERE LOTxLOCxID.Lot = @c_lot 
AND LOTxLOCxID.Loc = LOC.LOC
AND LOTxLOCxID.Storerkey = SKUxLOC.Storerkey 
AND LOTxLOCxID.Sku = SKUxLOC.Sku
AND LOTxLOCxID.Loc = SKUxLOC.Loc
AND SKUxLOC.Locationtype NOT IN ('CASE', 'PICK')
AND LOC.Facility = @c_Facility 
AND LOC.Locationflag <>'HOLD'
AND LOC.Locationflag <> 'DAMAGE'
AND LOC.Status <> 'HOLD'
ORDER BY SKUxLOC.QTY, LOC.LOC 
END




GO
 
GO
SET ANSI_NULLS OFF 
GO

GRANT EXECUTE ON nspALSTDE2 to nSQL
GO
