--UWP-59498
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMERDATETRACKER](
    [Storerkey] [varchar](15) NOT NULL,
    [ConsigneeKey] [varchar](15) NOT NULL,
    [Sku] [varchar](20) NOT NULL,
    [LastBestBeforeDate] [datetime2](3) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[CUSTOMERDATETRACKER] ADD  CONSTRAINT [PK_CUSTOMERDATETRACKER] PRIMARY KEY CLUSTERED
(
    [Storerkey] ASC,
    [ConsigneeKey] ASC,
    [Sku] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CUSTOMERDATETRACKER_LastBestBeforeDate] ON [dbo].[CUSTOMERDATETRACKER]
(
    [LastBestBeforeDate] ASC
)
INCLUDE([Storerkey],[ConsigneeKey],[Sku]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_CUSTOMERDATETRACKER_Sku] ON [dbo].[CUSTOMERDATETRACKER]
(
    [Sku] ASC
)
INCLUDE([Storerkey],[ConsigneeKey],[LastBestBeforeDate]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO
/*
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMERDATETRACKER_ARCHIVE](
    [Storerkey] [varchar](15) NOT NULL,
    [ConsigneeKey] [varchar](15) NOT NULL,
    [Sku] [varchar](20) NOT NULL,
    [LastBestBeforeDate] [datetime2](3) NOT NULL,
    [Date] [datetime2](3) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERDATETRACKER_ARCHIVE] ADD  CONSTRAINT [DF_CUSTOMERDATETRACKER_ARCHIVE_Date]  DEFAULT (sysdatetime()) FOR [Date]
GO*/
