IF EXISTS (SELECT * FROM sys.views WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[V_Codelkup2]'))
   DROP VIEW [dbo].[V_Codelkup2]
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE VIEW [dbo].[V_Codelkup2]
AS
SELECT CODELKUP.LISTNAME, CODELKUP.CODE, MAX(ISNULL(RTRIM(CODELKUP.[DESCRIPTION]),'')) AS [Description]
FROM dbo.CODELKUP CODELKUP WITH (NOLOCK)
GROUP BY CODELKUP.LISTNAME, CODELKUP.CODE

GO
GRANT SELECT ON [dbo].[V_Codelkup2] to NSQL
GO