name: cdt db deployment

on:
  workflow_dispatch:
    inputs:
      # environment:
      #   description: 'The environment to run (CDT, Stage, Americas, Europe, Asia)'
      #   required: true
      authToken:
        description: 'Authentication token for the API'
        required: true
        #default: ''

jobs:
  trigger-repo-a-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger  Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: 'Maersk-Global/fbm-infra-automation' 
          workflow: 'cdt-db-deploy.yaml'  
          ref: 'main' 
          inputs: |
            authToken: ${{ github.event.inputs.authToken }}
        env:
          GITHUB_TOKEN: ${{ secrets.db_token }}  