name: Auto Tag Releaser (DEV)

on:
#   push:
#     branches:
#       - dev

  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write
  security-events: write
  actions: write
  checks: write
  
jobs:
  code-analyze:
    timeout-minutes: 3
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Releaser
        uses: softprops/action-gh-release@v2
        with:
            tag_name: "v.0.0.${{ github.run_number }}"
            token: "${{ secrets.GITHUB_TOKEN }}"